Repository kyma-project/console, pull requests merged in 2018-10, with the labels that each got.

#192 Fix left navigation of Content UI
  content/src/components/MainPage/queries.js
Labels: area/documentation, bug, priority/critical

#197 Fix instance details error when instance doesn't have planSpec
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.component.js
  instances/src/components/ServiceInstances/ServiceInstances.component.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
Labels: area/console, area/service-catalog, bug, priority/critical

#193 Support namespaced ServiceClasses in Service Catalog UI
  catalog/src/components/Main/Main.component.js
  catalog/src/components/Main/Main.container.js
  catalog/src/components/Main/mutations.js
  catalog/src/components/Main/queries.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/BasicData.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.container.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassToolbar/ServiceClassToolbar.component.js
  catalog/src/components/ServiceClassDetails/queries.js
  catalog/src/components/ServiceClassDetails/styled.js
  catalog/src/components/ServiceClassList/ServiceClassList.component.js
  catalog/src/components/ServiceClassList/ServiceClassList.container.js
  catalog/src/components/ServiceClassList/queries.js
  catalog/src/store/Filter/defaults.js
  catalog/src/store/Filter/resolvers.js
  catalog/src/store/MainPage/defaults.js
  catalog/src/store/ServiceClassDetails/defaults.js
  catalog/src/store/index.js
  instances/src/components/ServiceInstanceDetails/queries.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/styled.js
  instances/src/components/ServiceInstances/queries.js
  instances/src/store/Filter/resolvers.js
Labels: area/console, area/service-catalog, enhancement

#209 Disable whitesource scan (temporarily)
  catalog/Jenkinsfile
  components/react/Jenkinsfile
  content/Jenkinsfile
  core/Jenkinsfile
  instances/Jenkinsfile
  lambda/Jenkinsfile
Labels: area/ci, bug

#194 Enable external links validation on PRs
  governance.Jenkinsfile
Labels: area/ci, area/documentation, enhancement

#185 Fix UI Acceptance tests
  CODEOWNERS
  content/src/components/Navigation/NavigationList.component.js
  tests/Dockerfile
  tests/package-lock.json
  tests/package.json
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/config.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
  tests/ui-tests/utils/address.js
  tests/ui-tests/utils/dex.js
  tests/ui-tests/utils/logging.js
  tests/ui-tests/utils/skip.js
  tests/ui-tests/utils/testContext.js
Labels: area/console, bug

#219 Enable WhiteSource in all Jenkinsfiles
  catalog/Jenkinsfile
  components/react/Jenkinsfile
  content/Jenkinsfile
  core/Jenkinsfile
  instances/Jenkinsfile
  lambda/Jenkinsfile
  tests/Jenkinsfile
Labels: area/ci

#220 Remove controversial words from name generator
  catalog/src/commons/random-names-data.js
Labels: area/console, bug

#218 investigate problems with local console development
  core/src/app/app.config.ts
Labels: area/console, bug

#221 Bump version of @kyma-project/react-components
  components/react/package-lock.json
  components/react/package.json
Labels: area/console

#216 Make nav footer sticky
  core/src/app/navigation/navigation.component.html
  core/src/app/navigation/navigation.component.scss
  core/src/styles/toolbar.scss
Labels: area/console, enhancement

#224 Remove unnecessary space in the environment list
  core/src/app/navigation/navigation.component.html
Labels: area/console, bug

#163 Multi view microfrontends
  core/src/app/extensibility/external-view/external-view.component.spec.ts
  core/src/app/extensibility/external-view/external-view.component.ts
  core/src/app/extensibility/services/extensions.service.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/app/navigation/app.navigation.data.ts
  core/src/app/navigation/header/header.component.ts
  core/src/app/navigation/navigation.component.html
  core/src/app/navigation/navigation.component.spec.ts
  core/src/app/navigation/navigation.component.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts
  core/src/app/shared/datamodel/k8s/microfrontend.ts
Labels: area/console, enhancement

#223 Add "Clear all filters" button and checked filters list in catalog ui
  catalog/src/components/ServiceClassList/ActiveFiltersList/ActiveFiltersList.component.js
  catalog/src/components/ServiceClassList/ActiveFiltersList/styled.js
  catalog/src/components/ServiceClassList/FilterList/Filter.component.js
  catalog/src/components/ServiceClassList/FilterList/FilterList.component.js
  catalog/src/components/ServiceClassList/FilterList/styled.js
  catalog/src/components/ServiceClassList/ServiceClassList.component.js
  catalog/src/components/ServiceClassList/ServiceClassList.container.js
  catalog/src/components/ServiceClassList/mutations.js
  catalog/src/components/ServiceClassList/queries.js
  catalog/src/store/Filter/resolvers.js
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/tests/catalog-ui-test.js
Labels: area/console, area/service-catalog, enhancement

#237 Add aerfio to CODEOWNERS
  CODEOWNERS
Labels: area/community

#228 Show metadata.labels in service-catalog ui
  catalog/OSBAContract.md
  catalog/assets/screen-catalog-page.png
  catalog/src/commons/helpers.js
  catalog/src/components/Main/queries.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/styled.js
  catalog/src/components/ServiceClassDetails/queries.js
  catalog/src/components/ServiceClassList/ActiveFiltersList/ActiveFiltersList.component.js
  catalog/src/components/ServiceClassList/Cards/Card.component.js
  catalog/src/components/ServiceClassList/Cards/Cards.component.js
  catalog/src/components/ServiceClassList/Cards/styled.js
  catalog/src/components/ServiceClassList/FilterList/Filter.component.js
  catalog/src/components/ServiceClassList/FilterList/FilterList.component.js
  catalog/src/components/ServiceClassList/ServiceClassList.component.js
  catalog/src/components/ServiceClassList/queries.js
  catalog/src/store/Filter/defaults.js
  catalog/src/store/Filter/resolvers.js
  components/react/src/components/Dropdown/components.js
  components/react/src/components/Tooltip/components.js
  components/react/src/components/Tooltip/index.js
Labels: area/console, area/documentation, area/service-catalog, enhancement

#238 Copy template for security issues
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  milv.config.yaml
Labels: area/documentation, area/security, enhancement, sig/core

#230 Tooltips for status in tables
  .prettierrc
  core/src/app/app.module.ts
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.html
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.html
  core/src/app/content/environments/operation/pods/pods-entry-renderer/pods-entry-renderer.component.html
  core/src/app/content/environments/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/environments/operation/pods/pods-header-renderer/pods-header-renderer.component.html
  core/src/app/content/environments/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.html
  core/src/app/content/environments/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.ts
  core/src/app/content/environments/operation/replica-sets/replica-sets-header-renderer/replica-sets-header-renderer.component.html
  core/src/app/content/environments/operation/services/services-entry-renderer/services-entry-renderer.component.html
  core/src/app/content/environments/operation/services/services-entry-renderer/services-entry-renderer.component.ts
  core/src/app/content/environments/operation/services/services-header-renderer/services-header-renderer.component.html
  core/src/app/content/settings/remote-environments/remote-environments-entry-renderer/remote-environments-entry-renderer.component.html
  core/src/app/content/settings/remote-environments/remote-environments-entry-renderer/remote-environments-entry-renderer.component.ts
  core/src/app/content/settings/remote-environments/remote-environments-header-renderer/remote-environments-header-renderer.component.html
  core/src/app/content/settings/service-brokers/services-entry-renderer/service-broker-entry-renderer.component.html
  core/src/app/content/settings/service-brokers/services-entry-renderer/service-broker-entry-renderer.component.ts
  core/src/app/content/settings/service-brokers/services-header-renderer/service-broker-header-renderer.component.html
  core/src/app/shared/components/status-label/status-label.component.html
  core/src/app/shared/components/status-label/status-label.component.scss
  core/src/app/shared/components/status-label/status-label.component.spec.ts
  core/src/app/shared/components/status-label/status-label.component.ts
  core/src/app/shared/components/tooltip/tooltip.component.html
  core/src/app/shared/components/tooltip/tooltip.component.scss
  core/src/app/shared/components/tooltip/tooltip.component.spec.ts
  core/src/app/shared/components/tooltip/tooltip.component.ts
Labels: area/console, enhancement

#244 Add user key to whitesource scan
  catalog/Jenkinsfile
  components/react/Jenkinsfile
  content/Jenkinsfile
  core/Jenkinsfile
  instances/Jenkinsfile
  tests/Jenkinsfile
Labels: area/ci

#240 Disable external links validation on master
  catalog/README.md
  content/README.md
  governance.Jenkinsfile
  instances/README.md
  orchestrator.Jenkinsfile
Labels: area/ci, area/community, enhancement, priority/critical

#261 Change cursor in dropdowns
  components/angular/generic-list/src/app/modules/list/list-element-actions/list-element-actions.component.scss
Labels: area/console, bug

#252 consistent loading indicators in generic list
  components/angular/generic-list/angular.json
  components/angular/generic-list/ng-package.json
  components/angular/generic-list/package-lock.json
  components/angular/generic-list/package.json
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.html
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.scss
  components/angular/generic-list/src/app/modules/list/list-element-actions/list-element-actions.component.scss
  components/angular/generic-list/src/app/modules/list/paging/paging.component.scss
  components/angular/generic-list/src/app/modules/list/plain-list/plain-list.component.html
  components/angular/generic-list/src/app/modules/list/plain-list/plain-list.component.scss
  components/angular/generic-list/src/app/modules/list/plain-table/plain-table.component.html
  components/angular/generic-list/src/app/modules/list/plain-table/plain-table.component.scss
  components/angular/generic-list/src/styles/_mixins.scss
  core/package.json
  core/src/styles/overrides.scss
Labels: area/console, enhancement

#265 Bump y-generic-list version
  core/package-lock.json
  core/package.json
Labels: area/console, enhancement

#264 Disable react/components job when committer is kyma.bot
  orchestrator.Jenkinsfile
Labels: area/ci, bug

#227 Display graphql error for remote environments creation and improve graphql errors handling
  components/angular/generic-list/package-lock.json
  components/angular/generic-list/package.json
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.ts
  components/angular/generic-list/src/app/modules/list/plain-list/plain-list.component.ts
  core/src/app/content/environments/operation/graphql-data-provider.ts
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.html
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.html
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.ts
  core/src/app/content/settings/remote-environments/edit-remote-environment-modal/edit-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/edit-remote-environment-modal/edit-remote-environment-modal.component.ts
  core/src/app/shared/components/labels-input/labels-input.component.html
  core/src/app/shared/components/labels-input/labels-input.component.spec.ts
  core/src/app/shared/components/labels-input/labels-input.component.ts
  core/src/app/shared/services/graphql-client-service.ts
Labels: area/console, bug

#31 Make nouns singular for one instance
  core/README.md
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/workspace-overview/environment-card/environment-card.component.html
Labels: area/console

#269 Add UI tests for Remote Environments
  tests/ui-tests/commands/console.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/utils/address.js
Labels: area/console, enhancement

#279 Update installation link
  README.md
Labels: area/community, area/documentation, bug

#267 Add prow presubmit configuration for brokers, content, catalog and instances ui
  brokers/.eslinterrc
  brokers/Makefile
  catalog/.eslinterrc
  catalog/Jenkinsfile
  catalog/Makefile
  content/.eslinterrc
  content/Jenkinsfile
  content/Makefile
  instances/.eslinterrc
  instances/Jenkinsfile
  instances/Makefile
Labels: area/ci, enhancement
