Repository kyma-project/console, pull requests merged in 2018-12, with the labels that each got.

#375 Migrate lambda to Prow
  lambda/Makefile
  lambda/tslint.json
Labels: area/ci

#357 Add 'resource quotas limit exceeded' details to the popup
  core/src/app/content/environments/environments-container/environments-container.component.html
  core/src/app/content/environments/environments-container/environments-container.component.ts
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/edit-remote-environment-modal/edit-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.spec.ts
  core/src/styles/_helper.scss
Labels: area/console, enhancement

#371 Add makefile for integration test (prow ci)
  tests/.eslinterrc
  tests/Makefile
  tests/ui-tests/tests/catalog-ui-test.js
Labels: area/console

#340 Add a status column to the list of bound services
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-binding-creator/lambda-instance-binding-creator.component.ts
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-bindings.component.html
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-bindings.component.ts
  lambda/src/app/shared/datamodel/instance-binding-info.ts
  lambda/src/app/shared/datamodel/k8s/generic/status.ts
  lambda/src/styles.scss
  lambda/src/styles/indicator.scss
Labels: area/console, area/serverless

#374 Replace phantomjs with chrome
  core/Jenkinsfile
  core/karma.conf.js
  core/package-lock.json
  core/package.json
Labels: area/console

#385 Hide bindings tab if instance not bindable
  instances/src/components/DataProvider/fragments.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateCredentialsModal/CreateCredentialsModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
Labels: area/console, area/service-catalog, bug

#397 Fix styling in service class documentation
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/styled.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  catalog/src/index.css
  components/react/src/components/Markdown/Readme.md
  components/react/src/components/Markdown/index.js
  components/react/src/components/index.js
  content/src/components/ContentWrapper/ContentWrapper.component.js
  content/src/index.css
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
  instances/src/index.css
Labels: area/console, area/service-catalog, bug

#396 Check exists of bindingCreateParameterSchema field
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateCredentialsModal/CreateCredentialsModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/styled.js
Labels: area/console, area/service-catalog, bug

#419 Fix bugs with global styles, status indicator of bindings and filtering in catalog
  catalog/package-lock.json
  catalog/src/components/App/styled.js
  instances/package-lock.json
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js
Labels: area/console, area/service-catalog, bug

#407 Hide service instances if Service Plan has bindable attribute set to false
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-binding-creator/lambda-instance-binding-creator.component.html
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-binding-creator/lambda-instance-binding-creator.component.ts
  lambda/src/app/service-instances/service-instances.service.spec.ts
  lambda/src/app/service-instances/service-instances.service.ts
  lambda/src/app/shared/datamodel/k8s/service-instance-list.ts
  lambda/src/app/shared/datamodel/k8s/service-instance-response.ts
  lambda/src/app/shared/datamodel/k8s/service-instance.ts
  lambda/src/app/shared/datamodel/k8s/service-instances-response.ts
Labels: area/console, area/serverless, enhancement

#426 Do not delete service binding usage of other functions using the same credentials
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
Labels: area/console, area/serverless, bug

#414 Rename Remote Environments in Console UI
  core/src/app/app.config.ts
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.html
  core/src/app/content/settings/remote-environments/edit-remote-environment-modal/edit-remote-environment-modal.component.html
  core/src/app/content/settings/remote-environments/remote-environment-details/edit-bindings-modal/edit-binding-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/edit-bindings-modal/edit-binding-modal.component.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-binding-service.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.html
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
  core/src/app/content/settings/remote-environments/remote-environments-entry-renderer/remote-environments-entry-renderer.component.ts
  core/src/app/content/settings/remote-environments/remote-environments.component.html
  core/src/app/content/settings/remote-environments/remote-environments.component.ts
  core/src/app/content/settings/remote-environments/services/remote-environments.service.spec.ts
  core/src/app/content/settings/remote-environments/services/remote-environments.service.ts
  core/src/app/content/workspace-overview/environment-card/environment-card.component.html
  core/src/app/content/workspace-overview/workspace-overview/environment-data-converter.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/app/navigation/app.navigation.data.ts
  core/src/app/shared/components/labels-input/labels-input.component.html
  tests/ui-tests/commands/console.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/utils/address.js
Labels: area/console

#423 Rename environments to namespaces
  core/package-lock.json
  core/src/app/content/environments/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.html
  core/src/app/content/environments/configuration/apis/apis.component.html
  core/src/app/content/environments/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.html
  core/src/app/content/environments/configuration/resources/resources.component.html
  core/src/app/content/environments/development/lambdas/lambdas.component.ts
  core/src/app/content/environments/environment-create/environment-create.component.html
  core/src/app/content/environments/environment-create/environment-create.component.ts
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/environments/environments-container/environments-container.component.ts
  core/src/app/content/environments/instances-container/instances-container.component.ts
  core/src/app/content/environments/operation/secrets/secret-detail/secret-detail.component.ts
  core/src/app/content/environments/operation/services/service-details/expose-api/expose-api.component.ts
  core/src/app/content/environments/operation/services/service-details/service-details.component.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/edit-bindings-modal/edit-binding-modal.component.html
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.html
  core/src/app/content/settings/remote-environments/remote-environments-header-renderer/remote-environments-header-renderer.component.html
  core/src/app/content/workspace-overview/environment-card/environment-card.component.html
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.html
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
  core/src/app/extensibility/directives/ext-app-listener.directive.ts
  core/src/app/extensibility/external-view/external-view.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/app/navigation/header/header.component.html
  core/src/app/navigation/header/header.component.ts
  core/src/app/navigation/navigation.component.html
  core/src/app/navigation/navigation.component.ts
Labels: area/console, enhancement

#427 Improve styles for docs on content-ui, instances-ui and catalog-ui
  components/react/src/components/Markdown/index.js
  content/src/components/ContentWrapper/ContentWrapper.component.js
  content/src/components/MainPage/MainPage.component.js
Labels: area/community, area/documentation, enhancement

#435 Fix UI tests and rename envs to namespaces in remaining views
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/Resources.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/InfoButton/variables.js
  tests/ui-tests/utils/address.js
Labels: area/console, bug

#437 Rename BUC CRs domain
  lambda/src/app/app.config.ts
  lambda/src/app/service-binding-usages/service-binding-usages.service.spec.ts
  lambda/src/app/service-binding-usages/service-binding-usages.service.ts
  lambda/src/app/service-bindings/service-bindings.service.spec.ts
Labels: enhancement

#440 Remove Jenkins configuration
  brokers/Jenkinsfile
  catalog/Jenkinsfile
  content/Jenkinsfile
  core/Jenkinsfile
  governance.Jenkinsfile
  instances/Jenkinsfile
  lambda/Jenkinsfile
  orchestrator.Jenkinsfile
  tests/Jenkinsfile
Labels: area/ci
