Repository kyma-project/console, pull requests merged in 2018-09, with the labels that each got.

#129 Fix usageKinds fetching
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateBindingModal/CreateBindingModal.component.js
Labels: area/console

#128 Move nagivation to dropdown, add global navigation in catalog
  catalog/Jenkinsfile
  catalog/OSBAContract.md
  catalog/package-lock.json
  catalog/package.json
  catalog/src/components/Main/Main.component.js
  catalog/src/components/Main/styled.js
  catalog/src/components/ServiceClassList/FilterList/Filter.component.js
  catalog/src/components/ServiceClassList/FilterList/FilterList.component.js
  catalog/src/components/ServiceClassList/FilterList/styled.js
  catalog/src/components/ServiceClassList/ServiceClassList.component.js
  catalog/src/components/ServiceClassList/ServiceClassList.container.js
  catalog/src/components/ServiceClassList/mutations.js
  catalog/src/components/ServiceClassList/queries.js
  catalog/src/components/ServiceClassList/styled.js
  catalog/src/store/Filter/defaults.js
  catalog/src/store/Filter/resolvers.js
  components/react/Jenkinsfile
  components/react/package-lock.json
  components/react/package.json
  components/react/src/components/Dropdown/components.js
  components/react/src/components/Dropdown/index.js
  components/react/src/components/Search/components.js
  components/react/src/components/Search/index.js
  components/react/src/components/Text/index.js
  content/Jenkinsfile
  content/package-lock.json
  content/package.json
  core/src/app/navigation/app-routing.module.ts
  instances/Jenkinsfile
  instances/package-lock.json
  instances/package.json
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/tests/catalog-ui-test.js
Labels: area/documentation

#130 Improve view with listing instances
  catalog/src/index.css
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/styled.js
  instances/src/components/ServiceInstances/queries.js
  instances/src/index.css
  instances/src/store/Filter/resolvers.js
Labels: area/console, area/service-catalog, enhancement

#160 Improve server response to send assets
  catalog/nginx.conf
  content/nginx.conf
  core/nginx/nginx.conf
  instances/nginx.conf
  lambda/nginx/nginx.conf
Labels: enhancement

#158 Reduce size of the React UI bundles
  catalog/package-lock.json
  catalog/package.json
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerConsole.component.js
  components/react/package-lock.json
  components/react/package.json
  components/react/webpack.config.js
  components/react/webpack.config.prod.js
  content/config-overrides.js
  content/package-lock.json
  content/package.json
  content/src/components/ContentWrapper/ContentWrapper.component.js
  instances/package-lock.json
  instances/package.json
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerConsole.component.js
Labels: area/console, area/service-catalog, bug

#157 Allow ServiceBinding without secret
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
Labels: area/console, area/service-catalog

#162 Update remote environments fields in core
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.html
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.scss
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
  core/src/app/content/settings/remote-environments/remote-environments-entry-renderer/remote-environments-entry-renderer.component.html
  core/src/app/content/settings/remote-environments/remote-environments-entry-renderer/remote-environments-entry-renderer.component.scss
  core/src/app/content/settings/remote-environments/remote-environments-header-renderer/remote-environments-header-renderer.component.html
  core/src/app/content/settings/remote-environments/remote-environments.component.ts
  core/src/app/content/settings/remote-environments/services/remote-environments.service.ts
Labels: area/console, enhancement

#155 #136 Make logo and title in console configurable
  core/src/app/app.config.ts
  core/src/app/navigation/header/header.component.html
  core/src/app/navigation/header/header.component.scss
  core/src/app/navigation/header/header.component.ts
Labels: area/console, enhancement

#169 Make catalog and instances UIs compatible with latest GraphQL API
  catalog/src/components/Main/Main.component.js
  catalog/src/components/Main/Main.container.js
  catalog/src/components/Main/queries.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/BasicData.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassToolbar/ServiceClassToolbar.component.js
  catalog/src/components/ServiceClassDetails/mutations.js
  catalog/src/components/ServiceClassDetails/queries.js
  catalog/src/components/ServiceClassList/ServiceClassList.component.js
  catalog/src/components/ServiceClassList/queries.js
  catalog/src/store/Filter/defaults.js
  catalog/src/store/Filter/resolvers.js
  catalog/src/store/MainPage/defaults.js
  catalog/src/store/ServiceClassDetails/defaults.js
  catalog/src/store/resolvers.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceDetails.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceToolbar/ServiceInstanceToolbar.component.js
  instances/src/components/ServiceInstanceDetails/queries.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
  instances/src/components/ServiceInstances/queries.js
  instances/src/store/Filter/resolvers.js
Labels: area/console, bug

#180 Change status build for Kyma Bot
  orchestrator.Jenkinsfile
Labels: area/console, bug

#171 Update node and nginx images version
  catalog/Dockerfile
  content/Dockerfile
  core/Dockerfile
  instances/Dockerfile
  lambda/Dockerfile
Labels: area/console, area/security, security/critical

#154 Add info that resource quota limit has been exceeded
  core/src/app/content/environments/environments-container/environments-container.component.html
  core/src/app/content/environments/environments-container/environments-container.component.scss
  core/src/app/content/environments/environments-container/environments-container.component.ts
  core/src/app/content/environments/services/environments.service.spec.ts
  core/src/app/content/environments/services/environments.service.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.service.spec.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.service.ts
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.ts
Labels: area/console, enhancement

#145 Bugfix infinite loop on 401 errors
  core/src/app/app.module.ts
  core/src/app/auth/token.interceptor.spec.ts
  core/src/app/auth/token.interceptor.ts
  core/src/app/content/logout/logout.component.html
  core/src/app/content/logout/logout.component.scss
  core/src/app/content/request-error/request-error.component.html
  core/src/app/content/request-error/request-error.component.scss
  core/src/app/content/request-error/request-error.component.ts
  core/src/app/navigation/app-routing.module.ts
Labels: area/console, bug

#188 Align new service bindings query in UI
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateBindingModal/CreateBindingModal.component.js
  instances/src/components/ServiceInstanceDetails/queries.js
Labels: area/console, area/service-catalog, enhancement
