Repository kyma-project/console, pull requests merged in 2018-11, with the labels that each got.

#304 Use short commit hash value as tag for docker images
  orchestrator.Jenkinsfile
Labels: area/console

#300 Change default page size for lists from 9999 to 50
  core/src/app/content/environments/operation/abstract-kubernetes-element-list.component.ts
Labels: area/console, enhancement

#302 Navigation through spa with luigi client reloads the whole app
  core/src/app/content/environments/environments-container/environments-container.component.ts
  core/src/app/extensibility/external-view/external-view.component.html
  core/src/app/extensibility/external-view/external-view.component.spec.ts
  core/src/app/extensibility/external-view/external-view.component.ts
  core/src/app/navigation/app-routing.module.ts
Labels: bug

#312 Test removed due to removal of default remote environments (#1458)
  tests/ui-tests/tests/console-basic-test.js
Labels: area/console

#311 Move `deploy new resource` link
  .angulardoc.json
  core/src/app/content/environments/configuration/resources/resources.component.html
  core/src/app/content/environments/configuration/resources/resources.component.scss
  core/src/app/content/environments/configuration/resources/resources.component.ts
Labels: area/console, enhancement

#310 Change domain of API CR
  config.js
  core/src/app/app.config.ts
  core/src/app/content/environments/operation/services/service-details/expose-api/expose-api.service.ts
  lambda/src/app/apis/apis.service.spec.ts
  lambda/src/app/apis/apis.service.ts
  lambda/src/app/app.config.ts
Labels: area/service-mesh, enhancement

#327 State set as dirty if lambda has dependencies - fixed.
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
Labels: bug

#335 Change "Select existing credentials" label
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindingsStep.component.js
Labels: area/console, bug

#324 Fix UI tests
  tests/package-lock.json
  tests/package.json
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
Labels: area/console, bug, priority/critical
