Repository kyma-project/console, pull requests merged in 2019-01, with the labels that each got.

#446 Adjust labels to be more usable
  core/src/app/content/environments/operation/abstract-kubernetes-entry-renderer.component.ts
  core/src/app/content/environments/operation/graphql-data-provider.ts
  core/src/app/content/environments/operation/services/service-details/service-details.component.html
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.ts
  core/src/app/content/settings/remote-environments/edit-remote-environment-modal/edit-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/edit-remote-environment-modal/edit-remote-environment-modal.component.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
  core/src/app/shared/components/labels-input/labels-input.component.spec.ts
  core/src/app/shared/components/labels-input/labels-input.component.ts
  core/src/app/shared/datamodel/k8s/generic/dashboard-meta-data-owner.ts
  core/src/app/shared/datamodel/k8s/generic/meta-data-owner.ts
  core/src/styles/overrides.scss
  lambda/package-lock.json
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/shared/datamodel/k8s/generic/meta-data-owner.ts
  lambda/src/styles/overrides.scss
Labels: area/console, bug

#461 Stabilize ui tests for variable network conditions
  tests/package.json
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/config.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
  tests/ui-tests/utils/testContext.js
  tests/ui-tests/utils/testIfWebResourceAvailable.js
  tests/ui-tests/utils/waitForNavigationAndContext.js
Labels: area/console, bug

#466 Disabled browser cache for ui tests execution
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
Labels: area/console, bug

#468 Fix UI tests after changing labels
  tests/ui-tests/commands/console.js
Labels: area/console, bug

#462 Add scrollSpy on content-ui
  brokers/package-lock.json
  catalog/package-lock.json
  content/package-lock.json
  content/src/App.css
  content/src/App.js
  content/src/commons/helpers.js
  content/src/commons/variables.js
  content/src/components/ColumnsWrapper/ColumnsWrapper.component.js
  content/src/components/ContentWrapper/ContentWrapper.component.js
  content/src/components/ContentWrapper/ContentWrapper.container.js
  content/src/components/DocsContent/DocsContent.component.js
  content/src/components/DocsContent/DocsContent.container.js
  content/src/components/DocsContent/DocsProcessor.js
  content/src/components/DocsContent/mutations.js
  content/src/components/DocsContent/queries.js
  content/src/components/DocsContent/styled.js
  content/src/components/MainPage/MainPage.component.js
  content/src/components/MainPage/MainPage.container.js
  content/src/components/MainPage/queries.js
  content/src/components/MainPage/styled.js
  content/src/components/Navigation/LeftNavigation/LeftNavigation.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationGroup.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationList.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationSections.js
  content/src/components/Navigation/LeftNavigation/NavigationList/styled.js
  content/src/components/Navigation/LeftNavigation/styled.js
  content/src/components/Navigation/NavigationList.component.js
  content/src/components/Navigation/RightNavigation/RightNavigation.js
  content/src/components/Navigation/ScrollSpy/ScrollSpy.component.js
  content/src/components/Navigation/ScrollSpy/ScrollSpy.container.js
  content/src/components/Navigation/ScrollSpy/queries.js
  content/src/index.js
  content/src/store/ContentWrapper/defaults.js
  content/src/store/ContentWrapper/resolvers.js
  content/src/store/DocsContent/defaults.js
  content/src/store/DocsContent/resolvers.js
  content/src/store/defaults.js
  content/src/store/index.js
  content/src/store/resolvers.js
  core/src/assets/luigi-config.js
  instances/package-lock.json
Labels: area/documentation, enhancement

#470 Double navigation timeout for ui tests
  tests/ui-tests/commands/common.js
  tests/ui-tests/config.js
Labels: area/console, bug

#471 Fix console-basic-test
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
Labels: area/console, bug

#475 Fix Luigi imports in CreateCredentialsModal
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateCredentialsModal/CreateCredentialsModal.component.js
Labels: area/console, bug

#474 Upgrade luigi version
  brokers/package-lock.json
  brokers/package.json
  catalog/package-lock.json
  catalog/package.json
  content/package-lock.json
  content/package.json
  core/package-lock.json
  core/package.json
  instances/package-lock.json
  instances/package.json
  lambda/package-lock.json
  lambda/package.json
Labels: area/console, enhancement

#465 Add icons for nodes and categories
  core/src/assets/luigi-config.js
Labels: area/console, enhancement

#481 Cannot configure title, logo and favicon in luigified console
  core/src/assets/luigi-config.js
Labels: area/console, bug

#473 Update react-jsonschema-form package
  catalog/package-lock.json
  catalog/package.json
  components/react/package-lock.json
  components/react/package.json
  components/react/src/components/Forms/JSONSchema/index.js
Labels: area/console, enhancement

#493 Include fiori fundamentals and fundamental ngx in console
  core/angular.json
  core/package-lock.json
  core/package.json
  core/src/app/app.module.ts
Labels: area/console, enhancement

#484 Stabilise UI tests in variable network conditions
  core/package-lock.json
  core/package.json
  tests/ui-tests/commands/common.js
  tests/ui-tests/utils/testContext.js
Labels: area/console, enhancement

#497 Add list of backend modules to the context
  core/src/app/app.component.ts
  core/src/assets/luigi-config.js
Labels: area/console, enhancement

#503 Apply backend modules data to deployments view
  core/src/app/app.module.ts
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.html
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.scss
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.spec.ts
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.html
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.spec.ts
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.ts
  core/src/app/shared/services/luigi-client.service.spec.ts
  core/src/app/shared/services/luigi-client.service.ts
  core/src/tsconfig.app.json
  core/src/tsconfig.spec.json
  core/tsconfig.json
  core/tslint.json
Labels: area/console, enhancement

#494 add johannesdoberer to codeowners list
  CODEOWNERS
Labels: area/console

#509 Fix the info displayed on UI
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
Labels: area/documentation

#506 Rename environments to namespaces in ui-api-layer under application domain
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-binding-service.ts
  lambda/src/app/event-activations/event-activations.service.spec.ts
  lambda/src/app/event-activations/event-activations.service.ts
Labels: area/application-connector, enhancement

#498 Fiori ngx for details views
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/environments/environment-details/environment-details.component.scss
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/settings/organisation/organisation.component.html
  core/src/app/content/settings/organisation/organisation.component.scss
Labels: area/console

#514 fix runtime errors
  core/src/assets/luigi-config.js
Labels: area/console, bug

#511 Extract all modular microfrontends from static console configuration into clustermicrofrontends c rs
  catalog/src/components/App/App.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  core/package-lock.json
  core/package.json
  core/src/app/content/environments/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.ts
  core/src/app/content/environments/configuration/apis/apis.component.ts
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/environments/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/environments/operation/services/service-details/expose-api/expose-api.component.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
  core/src/assets/luigi-config.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceToolbar/ServiceInstanceToolbar.component.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  tests/ui-tests/utils/address.js
Labels: area/console, enhancement

#520 Add babel-based transpilation for luigi config file
  core/.babelrc
  core/.gitignore
  core/package-lock.json
  core/package.json
  core/src/index.html
  core/src/luigi-config/luigi-config.js
  core/webpack-generateConfig.config.js
Labels: area/console, enhancement

#521 Fiori ngx for details views (improvement)
  core/angular.json
  core/package-lock.json
  core/package.json
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/environments/environment-details/environment-details.component.scss
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/settings/organisation/organisation.component.html
  core/src/app/content/settings/organisation/organisation.component.scss
  core/src/app/content/settings/organisation/organisation.component.ts
Labels: area/console
