Repository kyma-project/console, pull requests merged in 2019-04, with the labels that each got.

#733 Fix a dead link
  README.md
Labels: area/documentation, bug

#737 Use Dex internal jwks uri when exposing dex-secured APIs
  core/src/app/app.config.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.ts
Labels: area/console, bug

#720 Improve login error behavior
  core/package.json
  core/src/logout.html
  core/src/luigi-config/luigi-config.js
Labels: area/console

#732 add prefix to IDP Presets issuer by default
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.html
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.spec.ts
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts
Labels: area/console, enhancement

#728 673 make all console views more consistent
  components/angular/generic-list/src/app/modules/list/list-filter/list-filter.component.html
  components/angular/generic-list/src/app/modules/list/list-filter/list-filter.component.scss
  components/angular/generic-list/src/app/modules/list/list-search/list-search.component.html
  core/src/app/content/namespaces/configuration/apis/apis.component.html
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-entry-renderer/resource-quota-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-entry-renderer/resource-quota-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/configmaps/configmaps-entry-renderer/configmaps-entry-renderer.component.html
  core/src/app/content/namespaces/operation/configmaps/configmaps-entry-renderer/configmaps-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.html
  core/src/app/content/namespaces/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.html
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.html
  core/src/app/content/namespaces/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.html
  core/src/app/content/namespaces/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.ts
  core/src/app/content/namespaces/operation/services/services-entry-renderer/services-entry-renderer.component.html
  core/src/app/content/namespaces/operation/services/services-entry-renderer/services-entry-renderer.component.ts
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.ts
  core/src/app/content/settings/applications/applications-entry-renderer/applications-entry-renderer.component.html
  core/src/app/content/settings/applications/applications-entry-renderer/applications-entry-renderer.component.ts
  core/src/app/shared/components/permissions/role-details/role-details.component.html
  core/src/app/shared/components/permissions/role-details/role-details.component.ts
  core/src/app/shared/constants/constants.ts
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.html
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.ts
  lambda/src/app/shared/constants/constants.ts
  logging/src/app/search-form/search-form.component.html
Labels: area/console

#744 console with luigi 0.4.11 rc
  core/package-lock.json
  core/package.json
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/luigi-config/luigi-config.js
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/lambdas/lambda-details/lambda-details.component.html
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.ts
  lambda/src/app/lambdas/list/lambdas.component.ts
  lambda/src/main.ts
Labels: area/console, enhancement

#740 Update GQL mutations for creating service instances and service instance binding usages
  catalog/src/components/ServiceClassDetails/mutations.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateBindingModal/CreateBindingModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.container.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/mutations.js
Labels: area/console, enhancement

#752 Update CODEOWNERS
  CODEOWNERS
Labels: area/community, enhancement

#745 Catalog and Instance UI to support Headless CMS
  catalog/package-lock.json
  catalog/package.json
  catalog/src/commons/helpers.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/BasicData.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  catalog/src/components/ServiceClassDetails/queries.js
  components/react-odata/src/ODataFiles/SAPodata.ts
  components/react-odata/src/ODataFiles/index.ts
  components/react-odata/src/ODataFiles/temp.xml
  components/react-odata/src/ODataReact.tsx
  components/react-odata/src/index.tsx
  components/react/package-lock.json
  components/react/package.json
  components/react/src/commons/style-utils.js
  components/react/src/components/NotePanel/index.js
  components/react/src/components/NotePanel/styled.js
  components/react/src/components/ReactMarkdown/components/Blockquote.js
  components/react/src/components/ReactMarkdown/components/Code/CopyButton.js
  components/react/src/components/ReactMarkdown/components/Code/index.js
  components/react/src/components/ReactMarkdown/components/Theme.js
  components/react/src/components/ReactMarkdown/helpers.js
  components/react/src/components/ReactMarkdown/index.js
  components/react/src/components/ReactMarkdown/parseHTML/Tabs.js
  components/react/src/components/ReactMarkdown/parseHTML/index.js
  components/react/src/components/ReactMarkdown/styled.js
  components/react/src/components/Tabs/Tab/components.js
  components/react/src/components/Tabs/Tab/index.js
  components/react/src/components/Tabs/components.js
  components/react/src/components/Tabs/index.js
  components/react/src/components/index.js
  instances/package-lock.json
  instances/package.json
  instances/src/commons/helpers.js
  instances/src/components/DataProvider/fragments.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindingsStep.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/Resources.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
Labels: area/console, area/documentation, enhancement

#726 Show docs-ui from headless cms
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/BasicData.component.js
  components/react/package-lock.json
  components/react/package.json
  components/react/src/components/ReactMarkdown/components/Code/CopyButton.js
  components/react/src/components/ReactMarkdown/components/Code/index.js
  components/react/src/components/ReactMarkdown/styled.js
  content/Dockerfile
  content/README.md
  content/package.json
  content/src/components/DocsContent/DocsContent.component.js
  content/src/components/DocsContent/DocsContent.container.js
  content/src/components/DocsContent/DocsProcessor.js
  content/src/components/DocsContent/mutations.js
  content/src/components/DocsContent/queries.js
  content/src/components/MainPage/MainPage.component.js
  content/src/components/MainPage/MainPage.container.js
  content/src/components/MainPage/queries.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationGroup.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationList.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationSections.js
  content/src/components/Navigation/ScrollSpy/ScrollSpy.component.js
  content/src/components/Navigation/ScrollSpy/ScrollSpy.container.js
  content/src/store/DocsContent/defaults.js
  content/src/store/DocsContent/resolvers.js
  content/src/store/resolvers.js
Labels: area/core-and-supporting, enhancement

#755 Make Docs-ui tests more stable
  tests/ui-tests/tests/docs-ui-test.js
Labels: area/console, bug, priority/critical

#741 Enable Log-UI tests
  tests/package.json
  tests/ui-tests/config.js
  tests/ui-tests/tests/logging-test.js
Labels: area/console, enhancement

#764 Fix React OData component license
  catalog/package.json
  components/react-odata/package.json
  instances/package.json
Labels: area/console, bug

#772 console with luigi 0.4.11
  core/package-lock.json
  core/package.json
Labels: area/console, enhancement

#770 Fix empty CMF issue
  core/src/luigi-config/luigi-config.js
Labels: area/console, bug

#779 create button: avoid save when button state is disabled
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.html
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.html
Labels: area/console, bug

#767 762 improvements for responsiveness on mobile devices
  core/src/index.html
  core/src/luigi-config/luigi-config.js
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/src/styles/fiori-fundamentals-overrides.scss
Labels: WIP, area/console, enhancement

#777 768 fiorification phase 3
  components/angular/generic-list/angular.json
  components/angular/generic-list/package-lock.json
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.html
  components/angular/generic-list/src/app/modules/list/generic-table/generic-table.component.html
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/apis.component.html
  core/src/app/content/namespaces/configuration/resources/resources.component.html
  core/src/app/content/namespaces/configuration/resources/resources.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resources.component.ts
  core/src/app/content/namespaces/namespace-details/namespace-details.component.html
  core/src/app/content/namespaces/operation/kubernetes-element-list.component.html
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.html
  core/src/app/content/namespaces/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.html
  core/src/app/content/namespaces/operation/services/services-entry-renderer/services-entry-renderer.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/applications.component.html
  core/src/app/content/settings/idp-presets/idp-presets.component.html
  core/src/app/content/settings/organisation/organisation.component.html
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.html
  core/src/app/shared/components/edit-resource/edit-resource.component.html
  core/src/app/shared/components/permissions/permissions.component.html
  core/src/app/shared/components/permissions/role-details/role-details.component.html
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/src/app/lambdas/lambda-details/lambda-details.component.html
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.html
  lambda/src/app/lambdas/list/lambdas.component.html
  lambda/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, enhancement

#765 Update react-fundamental library to 0.5.0
  components/react/package-lock.json
  components/react/package.json
  components/react/src/components/Panel/index.js
  components/react/src/components/Table/styled.js
  components/react/src/components/Tile/index.js
  components/react/src/components/Toolbar/styled.js
  components/react/src/components/index.js
  tests/ui-tests/tests/catalog-ui-test.js
Labels: area/console, area/service-catalog, enhancement

#797 Make Content-UI more versatile
  content/package-lock.json
  content/package.json
  content/public/index.html
  content/src/App.js
  content/src/commons/helpers.js
  content/src/components/DocsContent/DocsContent.component.js
  content/src/components/DocsContent/DocsContent.container.js
  content/src/components/MainPage/MainPage.component.js
  content/src/components/MainPage/MainPage.container.js
  content/src/components/MainPage/queries.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationGroup.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationList.js
  content/src/components/Navigation/LeftNavigation/NavigationList/NavigationSections.js
  content/src/components/Navigation/LeftNavigation/NavigationList/styled.js
  content/src/components/Navigation/RightNavigation/RightNavigation.js
  content/src/components/Navigation/ScrollSpy/ScrollSpy.component.js
Labels: area/console, enhancement
