Repository kyma-project/console, pull requests merged in 2019-03, with the labels that each got.

#600 Fix icons in catalog, instances and react-components
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/SchemaData.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/styled.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/styled.js
  catalog/src/components/ServiceClassList/Cards/Card.component.js
  catalog/src/components/ServiceClassList/Cards/styled.js
  components/react/src/components/Icon/Readme.md
  components/react/src/components/Notification/index.js
  components/react/src/components/NotificationMessage/index.js
  components/react/src/components/Search/components.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateCredentialsModal/CreateCredentialsModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateCredentialsModal/SchemaData.component.js
Labels: area/console, bug

#613 Role binding for users
  core/src/app/shared/components/permissions/bindings/binding-header-renderer/binding-header-renderer.component.html
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.html
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.spec.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.ts
  core/src/app/shared/services/rbac.service.ts
Labels: area/console, enhancement

#617 Reminder for npm run bootstrap
  package.json
  scripts/pre-start-warning.sh
Labels: area/console

#615 Csp
  core/nginx/nginx.conf
Labels: area/console, enhancement

#622 Remove Whitesource references
  brokers/Makefile
  catalog/Makefile
  components/react/Makefile
  content/Makefile
  core/Makefile
  instances/Makefile
  lambda/Makefile
  logging/Makefile
  tests/Makefile
Labels: area/console

#618 Add Makefile for react-odata component
  components/react-odata/Makefile
  components/react-odata/package-lock.json
  components/react-odata/package.json
  components/react-odata/src/components/Table/ServiceDocumentationTable/ServiceDocumentationTable.tsx
  components/react-odata/src/react-app-env.d.ts
  components/react-odata/src/serviceWorker.ts
  components/react-odata/tslint.json
  components/react-odata/yarn.lock
  components/react/Jenkinsfile
Labels: area/ci, area/console, enhancement

#653 Filter out module disabled errors
  core/src/app/shared/services/graphql-client-service.ts
  lambda/src/app/graphql-client/graphql-client.service.ts
Labels: area/console, bug

#634 Hide kyma related view parts non env namespaces
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/environments/environment-details/environment-details.component.spec.ts
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.html
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.spec.ts
  core/src/app/content/environments/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.html
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.spec.ts
  core/src/app/content/environments/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.ts
  core/src/app/content/environments/operation/services/service-details/service-details.component.html
  core/src/app/content/environments/operation/services/service-details/service-details.component.ts
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#655 Upgrade luigi 0.4.9
  brokers/package-lock.json
  brokers/package.json
  catalog/package-lock.json
  catalog/package.json
  content/package-lock.json
  content/package.json
  core/package-lock.json
  core/package.json
  instances/package-lock.json
  instances/package.json
  lambda/package-lock.json
  lambda/package.json
Labels: area/console, enhancement

#656 Information modal with an error message is not shown on creating new namespace
  core/src/app/content/environments/environment-create/environment-create.component.ts
Labels: area/console, bug

#665 Modals content not being reset when closing and reopening
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.html
  components/angular/generic-list/src/app/modules/list/generic-table/generic-table.component.html
  core/src/app/content/environments/configuration/apis/apis.component.html
  core/src/app/content/environments/configuration/apis/filtered-apis/filtered-apis.component.html
  core/src/app/content/environments/configuration/resources/limit-ranges/limit-ranges.component.html
  core/src/app/content/environments/configuration/resources/resource-quotas/resource-quotas.component.html
  core/src/app/content/environments/operation/kubernetes-element-list.component.html
  core/src/app/content/environments/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.html
  core/src/app/content/environments/operation/services/services-entry-renderer/services-entry-renderer.component.html
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.spec.ts
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts
  core/src/app/content/settings/idp-presets/idp-presets.component.html
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.ts
  core/src/app/content/settings/remote-environments/remote-environments.component.html
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.html
  core/src/app/shared/components/json-editor-modal/json-editor-modal.component.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.spec.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.ts
  lambda/src/app/lambdas/list/lambdas.component.html
Labels: area/console, bug

#670 Add namespace caching
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#677 List of applications is not loaded after editing one entry
  core/src/app/content/environments/operation/secrets/secret-detail/secret-detail.component.html
  core/src/app/content/environments/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/environments/operation/services/service-details/service-details.component.html
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.html
  core/src/app/shared/components/permissions/role-details/role-details.component.html
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/src/app/lambdas/lambda-details/lambda-details.component.html
  lambda/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, bug

#676 Fix Safari bug with Popovers
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, bug, priority/critical

#675 Enable autocomplete for inputs without dropdowns for consistency
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.html
  core/src/app/content/settings/remote-environments/create-remote-environment-modal/create-remote-environment-modal.component.html
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.html
Labels: area/console

#681 Hide 'expose api' action for system namespaces
  core/src/app/content/environments/operation/services/services-entry-renderer/services-entry-renderer.component.ts
Labels: area/console, bug

#687 Change the codeowners file
  CODEOWNERS
Labels: area/documentation

#686 Cleanup after remote environments renaming
  core/src/app/app.config.ts
  core/src/app/app.module.ts
  core/src/app/content/environments/environment-details/environment-details.component.html
  core/src/app/content/environments/environment-details/environment-details.component.ts
  core/src/app/content/settings/applications/application-details/application-binding-service.ts
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.spec.ts
  core/src/app/content/settings/applications/application-details/application-details.component.ts
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.html
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.scss
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.spec.ts
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.ts
  core/src/app/content/settings/applications/application-details/services/event.service.ts
  core/src/app/content/settings/applications/applications-entry-renderer/applications-entry-renderer.component.html
  core/src/app/content/settings/applications/applications-entry-renderer/applications-entry-renderer.component.ts
  core/src/app/content/settings/applications/applications-header-renderer/applications-header-renderer.component.html
  core/src/app/content/settings/applications/applications-header-renderer/applications-header-renderer.component.ts
  core/src/app/content/settings/applications/applications.component.html
  core/src/app/content/settings/applications/applications.component.ts
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.html
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.scss
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.spec.ts
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.ts
  core/src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.html
  core/src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.scss
  core/src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.spec.ts
  core/src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.ts
  core/src/app/content/settings/applications/services/applications.service.spec.ts
  core/src/app/content/settings/applications/services/applications.service.ts
  core/src/app/content/settings/remote-environments/remote-environments-header-renderer/remote-environments-header-renderer.component.ts
  core/src/app/content/workspace-overview/environment-card/environment-card.component.html
  core/src/app/content/workspace-overview/workspace-overview/environment-data-converter.ts
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/app/shared/datamodel/k8s/environment.ts
  core/src/app/shared/datamodel/k8s/kyma-api/application.ts
  core/src/app/shared/datamodel/k8s/kyma-api/remote-environment.ts
  tests/ui-tests/commands/console.js
  tests/ui-tests/config.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/utils/address.js
Labels: area/console

#689 Use graphql for pods
  core/src/app/content/environments/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/environments/operation/pods/pods-entry-renderer/pods-entry-renderer.component.html
  core/src/app/content/environments/operation/pods/pods-entry-renderer/pods-entry-renderer.component.spec.ts
  core/src/app/content/environments/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/environments/operation/pods/pods-header-renderer/pods-header-renderer.component.html
  core/src/app/content/environments/operation/pods/pods.component.ts
Labels: area/console, enhancement

#696 Change UI API URL to Console Backend Service
  README.md
  config.js
  core/src/app/app.config.ts
  core/src/luigi-config/luigi-config.js
  lambda/src/app/app.config.ts
Labels: area/console, area/documentation, enhancement

#680 Fix lambda modal close
  components/angular/generic-list/angular.json
  components/angular/generic-list/package.json
  core/package-lock.json
  core/package.json
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/fetch-token-modal/fetch-token-modal.component.ts
  lambda/src/app/lambdas/lambda-details/event-trigger-chooser/event-trigger-chooser.component.ts
  lambda/src/app/lambdas/lambda-details/http-trigger/http-trigger.component.ts
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-binding-creator/lambda-instance-binding-creator.component.ts
  lambda/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, bug

#695 Use improved empty list placeholder from generic list
  components/angular/generic-list/src/app/modules/list/empty-list/empty-list.component.html
  components/angular/generic-list/src/app/modules/list/plain-table/plain-table.component.html
  components/angular/generic-list/src/app/modules/list/plain-table/plain-table.component.ts
  core/src/app/content/namespaces/configuration/apis/apis.component.html
  core/src/app/content/namespaces/configuration/apis/apis.component.ts
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis.component.html
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis.component.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.html
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.html
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.ts
  core/src/app/content/namespaces/operation/abstract-kubernetes-element-list.component.ts
  core/src/app/content/namespaces/operation/configmaps/configmaps.component.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.ts
  core/src/app/content/namespaces/operation/kubernetes-element-list-compact.component.html
  core/src/app/content/namespaces/operation/kubernetes-element-list.component.html
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/content/namespaces/operation/replica-sets/replica-sets.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.ts
  core/src/app/content/namespaces/operation/services/services.component.ts
  core/src/app/content/settings/applications/applications.component.html
  core/src/app/content/settings/applications/applications.component.ts
  core/src/app/content/settings/idp-presets/idp-presets.component.html
  core/src/app/content/settings/idp-presets/idp-presets.component.ts
  core/src/app/content/settings/service-brokers/service-brokers.component.ts
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.html
  core/src/app/shared/components/permissions/bindings/bindings.component.html
  core/src/app/shared/components/permissions/bindings/bindings.component.ts
  core/src/app/shared/components/permissions/roles/roles.component.ts
  core/src/app/shared/datamodel/empty-list-data.ts
  core/src/app/shared/datamodel/index.ts
  lambda/src/app/lambdas/list/lambdas.component.html
  lambda/src/app/lambdas/list/lambdas.component.ts
Labels: area/console, enhancement

#702 Clear binding modal data after closing it
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.ts
Labels: area/console, bug

#700 Log ui for lambdas and pods
  core/src/app/content/namespaces/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.ts
  lambda/src/app/lambdas/list/lambdas.component.ts
  lerna.json
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.spec.ts
  logging/src/app/search-form/search-form.component.ts
  logging/src/styles.scss
Labels: area/console, enhancement

#711 Implement graphql for cluster service brokers
  core/src/app/content/namespaces/namespaces-container/namespaces-container.component.ts
  core/src/app/content/namespaces/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/content/namespaces/operation/replica-sets/replica-sets.component.ts
  core/src/app/content/settings/service-brokers/service-brokers.component.ts
  core/src/app/content/settings/service-brokers/services-entry-renderer/service-broker-entry-renderer.component.html
  core/src/app/content/settings/service-brokers/services-entry-renderer/service-broker-entry-renderer.component.ts
Labels: area/console, enhancement

#712 Deployment deletion does not delete related replica set and pods
  core/src/app/app.config.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.ts
Labels: area/console, bug

#719 Log UI breaks regex expressions in search query
  logging/src/app/search-form/data/search-form-data.ts
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.ts
  logging/src/app/search-form/service/custom-http-parameter-codec.ts
  logging/src/app/search-form/service/search-service.ts
Labels: area/console, bug

#716 Add word-break rule for all cells in tables
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, bug

#707 Add graphql for configmaps
  core/src/app/content/namespaces/operation/configmaps/configmaps-entry-renderer/configmaps-entry-renderer.component.html
  core/src/app/content/namespaces/operation/configmaps/configmaps.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  logging/src/assets/config/config.js
Labels: area/console, enhancement

#721 redirection and alert message when namespace doesn't exist
  core/src/luigi-config/luigi-config.js
Labels: area/console, bug

#723 Refactor Logging UI
  logging/angular.json
  logging/e2e/protractor.conf.js
  logging/e2e/src/app.e2e-spec.ts
  logging/e2e/src/app.po.ts
  logging/e2e/tsconfig.e2e.json
  logging/package-lock.json
  logging/package.json
  logging/src/app/search-form/data/index.ts
  logging/src/app/search-form/data/plain-log-query.ts
  logging/src/app/search-form/data/search-form-data.ts
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.spec.ts
  logging/src/app/search-form/search-form.component.ts
  logging/src/app/search-form/service/search-service.ts
  logging/src/polyfills.ts
  logging/src/test.ts
  logging/src/tsconfig.app.json
  logging/src/tsconfig.spec.json
  logging/tsconfig.json
  logging/tslint.json
  tests/ui-tests/commands/logging.js
  tests/ui-tests/tests/logging-test.js
Labels: area/console, enhancement
