Repository kyma-project/console, pull requests merged in 2019-09, with the labels that each got.

#1209 Make application description optional
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.html
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.spec.ts
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.ts
Labels: area/console

#1195 Add MetadataDefinitions UI tests
  compass/.eslinterrc
  compass/Makefile
  compass/package-lock.json
  compass/package.json
  compass/src/Mock.test.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/MetadataDefinitionDetails.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/MetadataDefinitionDetails.ui.test.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/MetadataDefinitionDetails.unit.test.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/__snapshots__/MetadataDefinitionDetails.ui.test.js.snap
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/__snapshots__/MetadataDefinitionDetails.unit.test.js.snap
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/mock.js
  compass/src/components/MetadataDefinitions/test/MetadataDefinitions.ui.test.js
  compass/src/components/MetadataDefinitions/test/mock.js
  compass/src/setupTests.js
  compass/src/shared/components/ModalWithForm/test/ModalWithForm.test.js
  compass/src/store/index.js
Labels: area/console, quality/testability

#1217 Add missing constant in config for local development
  config.js
Labels: area/console, bug

#1223 Fix root Readme and Readme in tests dir
  README.md
  tests/README.md
Labels: area/documentation, bug

#1221 Faster and stable UI tests
  content/src/constants.ts
  package.json
  tests/package.json
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/config.js
  tests/ui-tests/setup/k8s-api/k8s-api-deployment.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
  tests/ui-tests/tests/logging-test.js
  tests/ui-tests/utils/address.js
  tests/ui-tests/utils/catalogConfig.js
  tests/ui-tests/utils/testContext.js
Labels: area/console, enhancement, quality/testability

#1222 Add generic component for preloading (Service Catalog UIs)
  common/src/constants.ts
  common/src/utils/preloadingStrategy.ts
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/microfrontend-converter.js
  service-catalog-ui/brokers/src/index.js
  service-catalog-ui/catalog/src/index.js
  service-catalog-ui/instances/src/index.js
Labels: area/console, enhancement

#1240 Display FQDN instead of hostname in httpTrigger
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
Labels: area/console, bug

#1264 Send stringified json schema
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.container.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/MetadataDefinitionDetails.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/MetadataDefinitionDetails.container.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/mock.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.container.js
  compass/src/components/Scenarios/Scenarios.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  compass/src/setupTests.js
Labels: area/console

#1248 Clean up after Gulp introduction
  compass/Dockerfile
  compass/Makefile
  compass/package-lock.json
  compass/package.json
  compass/src/App.component.js
  compass/src/App.scss
  compass/src/components/Shared/FileInput/style.scss
  compass/src/setupTests.js
  components/angular/generic-list/package-lock.json
  components/angular/generic-list/package.json
  components/generic-documentation/src/layouts/CompassUI.tsx
  core/Makefile
  core/angular.json
  core/package-lock.json
  core/package.json
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.spec.ts
  core/src/styles.scss
  core/tslint.json
  lambda/Makefile
  lambda/package-lock.json
  lambda/package.json
  lambda/tslint.json
  package-lock.json
  package.json
Labels: area/console

#1263 Update documentation-component to 0.3.0 with asyncapi-react 0.3.0
  common/package.json
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/generic-documentation/src/index.tsx
  components/generic-documentation/src/layouts/styled.ts
  components/generic-documentation/src/loader/loader.ts
  components/generic-documentation/src/render-engines/async-api/index.tsx
  components/generic-documentation/src/render-engines/async-api/theme.ts
  components/generic-documentation/src/render-engines/markdown/headers-toc/HeadersComponent.tsx
  components/generic-documentation/src/render-engines/markdown/headers-toc/styled.ts
  components/generic-documentation/src/render-engines/open-api/styles/index.ts
  components/generic-documentation/src/renderers/Group.renderer.tsx
  components/generic-documentation/src/renderers/styled.ts
  components/react/package-lock.json
  components/shared/package.json
  package-lock.json
  service-catalog-ui/Dockerfile
  service-catalog-ui/catalog/package-lock.json
  service-catalog-ui/catalog/package.json
  service-catalog-ui/catalog/postinstall.js
  service-catalog-ui/instances/package-lock.json
  service-catalog-ui/instances/package.json
  service-catalog-ui/instances/postinstall.js
  service-catalog-ui/postinstall.js
Labels: area/documentation, enhancement

#1267 Save window location after relogin
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation-helpers.js
Labels: area/console, bug

#1280 Fix context switcher/preloading issues
  service-catalog-ui/catalog/src/commons/builder.js
  service-catalog-ui/catalog/src/index.js
  service-catalog-ui/instances/src/commons/builder.js
  service-catalog-ui/instances/src/index.js
Labels: area/console, bug

#1287 Add missing code owners
  CODEOWNERS
Labels: area/console

#1293 Add dex auth to compass
  compass/README.md
  compass/public-luigi/index.html
  compass/public-luigi/logout.html
  compass/public-luigi/signout.svg
  compass/src/commons/builder.js
  compass/src/config/luigi-config/auth.js
  compass/src/config/luigi-config/main.js
  compass/src/config/luigi-config/navigation.js
  compass/src/index.js
  compass/src/store/index.js
  package-lock.json
  package.json
Labels: area/console, enhancement
