Repository kyma-project/console, pull requests merged in 2019-06, with the labels that each got.

#892 Display event trigger schema example
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/event-activations/event-activations.service.spec.ts
  lambda/src/app/event-activations/event-activations.service.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.html
  lambda/src/app/lambdas/lambda-details/lambda-details.component.scss
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/shared/datamodel/event-trigger-with-schema.ts
  lambda/src/app/shared/datamodel/event-trigger.ts
  lambda/src/app/shared/datamodel/event.ts
Labels: area/console, area/serverless, enhancement, quality/devx

#883 Expose APIs accessibility
  core/src/app/app.module.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-header-renderer/api-definition-header-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-header-renderer/filtered-apis-header-renderer.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.scss
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.ts
  core/src/app/shared/constants/constants.ts
  core/src/app/shared/services/generic-helpers.service.spec.ts
  core/src/app/shared/services/generic-helpers.service.ts
  core/src/styles.scss
  core/src/styles/fiori-fundamentals-overrides.scss
  lambda/package-lock.json
Labels: area/console, enhancement, quality/devx

#899 Change namespace creation modal to let user define its limits etc
  core/src/app/content/namespaces/namespace-create/namespace-create.component.html
  core/src/app/content/namespaces/namespace-create/namespace-create.component.scss
  core/src/app/content/namespaces/namespace-create/namespace-create.component.ts
  core/src/app/content/namespaces/namespace-details/namespace-details.component.html
  core/src/app/content/namespaces/namespace-details/namespace-details.component.spec.ts
  core/src/app/content/namespaces/namespace-details/namespace-details.component.ts
  core/src/app/content/namespaces/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.spec.ts
  core/src/app/content/namespaces/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.spec.ts
  core/src/app/content/namespaces/operation/deployments/deployment-header-renderer/deployment-header-renderer.component.ts
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.ts
  core/src/app/content/namespaces/operation/services/services-entry-renderer/services-entry-renderer.component.ts
  core/src/app/content/namespaces/services/namespaces.service.spec.ts
  core/src/app/content/namespaces/services/namespaces.service.ts
  core/src/app/content/workspace-overview/namespace-card/namespace-card.component.html
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
  core/src/app/shared/services/graphql-client-service.ts
  core/src/luigi-config/luigi-config.js
  core/src/styles/fiori-fundamentals-overrides.scss
Labels: WIP, area/console

#923 Fix istio label
  core/src/app/content/namespaces/namespace-create/namespace-create.component.ts
Labels: area/console, bug

#888 Adjust tabs rendering in catalog and instances views to fetching errors
  catalog/src/commons/helpers.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  catalog/src/variables.js
  components/react/package-lock.json
  components/react/package.json
  components/react/src/components/ReactMarkdown/parseHTML/Image.js
  components/react/src/components/ReactMarkdown/parseHTML/Link.js
  components/react/src/components/ReactMarkdown/parseHTML/index.js
  components/react/src/components/Tabs/index.js
  instances/src/commons/helpers.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/styled.js
  instances/src/variables.js
Labels: area/console, bug

#938 Fix tabs in content-ui
  components/react/src/components/ReactMarkdown/helpers.js
Labels: area/console, area/documentation, bug

#830 Disable create instance button in case not all fields are required
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/SchemaData.component.js
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/utils/catalogConfig.js
Labels: area/console

#946 Change namespace create modal size
  core/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, bug

#947 Log streams only for newest lambda pod
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  logging/package-lock.json
  logging/package.json
  logging/src/app/app.component.spec.ts
  logging/src/app/app.config.ts
  logging/src/app/app.module.ts
  logging/src/app/auth/token.interceptor.spec.ts
  logging/src/app/auth/token.interceptor.ts
  logging/src/app/search-form/data/log-stream.ts
  logging/src/app/search-form/data/pod-query.ts
  logging/src/app/search-form/data/search-form-data.ts
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.scss
  logging/src/app/search-form/search-form.component.spec.ts
  logging/src/app/search-form/search-form.component.ts
  logging/src/app/search-form/service/graphql-client-service.ts
  logging/src/app/search-form/service/pods-subscription/pods-subscription.service.ts
  logging/src/app/ws.ts
  logging/src/tsconfig.app.json
Labels: area/console, area/serverless, bug

#948 Update namespace details header
  core/src/app/content/namespaces/configuration/resources/resources.component.html
  core/src/app/content/namespaces/namespace-details/namespace-details.component.html
  core/src/app/content/namespaces/namespace-details/namespace-details.component.scss
  core/src/app/content/namespaces/namespace-details/namespace-details.component.ts
  core/src/app/content/namespaces/namespace-info.ts
  core/src/app/content/namespaces/services/namespaces.service.ts
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#895 Remove old dependencies
  brokers/package-lock.json
  content/package-lock.json
  lambda/package-lock.json
  tests/package-lock.json
  tests/package.json
Labels: area/console

#924 Fetch APIs via gql
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-header-renderer/api-definition-header-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/apis.component.html
  core/src/app/content/namespaces/configuration/apis/apis.component.ts
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis.component.ts
  core/src/app/content/namespaces/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/content/settings/applications/applications.component.ts
Labels: area/console, enhancement

#979 Add parostatkiem to codeowners
  CODEOWNERS
Labels: area/console

#974 Add polling of fresh log lines for log UI
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.scss
  logging/src/app/search-form/search-form.component.ts
  logging/src/app/search-form/shared/constants.ts
Labels: area/console, enhancement, quality/devx

#965 Add a possibility to hide navigation nodes
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation-helpers.js
Labels: area/console, enhancement

#980 Add polling of fresh log lines for log UI
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, enhancement, quality/devx

#978 Fix CreateBindingModal test
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.spec.ts
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts
Labels: area/console, test-failing

#955 Rework service class details header
  catalog/src/components/ServiceClassDetails/ProvisionOnlyOnceInfo/styled.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/styled.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/styled.js
  catalog/src/components/ServiceClassDetails/ServiceClassToolbar/ServiceClassToolbar.component.js
  catalog/src/variables.js
  components/react/src/components/Breadcrumb/index.js
  components/react/src/components/Tile/index.js
  components/react/src/components/Toolbar/index.js
  components/react/src/components/index.js
Labels: area/console, enhancement

#973 Store selected labels from workspace overview in the web storage
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.ts
  components/angular/generic-list/src/app/modules/list/list-filter/list-filter.component.ts
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.html
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
Labels: area/console, enhancement

#983 Fix disabledNavigationNodes
  core/src/luigi-config/luigi-config.js
Labels: area/console, bug

#984 Fix ui tests
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.html
Labels: area/console, wontfix

#985 Fix subscriptions query to match the initial query
  core/src/app/content/settings/applications/applications.component.ts
Labels: area/console, bug

#982 Fix service binding prefix
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/Resources.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/InfoButton/variables.js
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-binding-creator/lambda-instance-binding-creator.component.html
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-binding-creator/lambda-instance-binding-creator.component.ts
  lambda/src/app/lambdas/lambda-details/lambda-instance-bindings/lambda-instance-bindings.component.html
Labels: area/console, bug
