Repository kyma-project/console, pull requests merged in 2019-02, with the labels that each got.

#525 Rename environment to namespace
  brokers/src/components/ServiceBrokers/ServiceBrokers.container.js
  brokers/src/components/ServiceBrokers/queries.js
  catalog/src/components/Main/Main.container.js
  catalog/src/components/Main/mutations.js
  catalog/src/components/Main/queries.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.container.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/queries.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  catalog/src/components/ServiceClassDetails/mutations.js
  catalog/src/components/ServiceClassDetails/queries.js
  catalog/src/components/ServiceClassList/ServiceClassList.container.js
  catalog/src/store/Filter/resolvers.js
  core/src/app/content/environments/configuration/apis/filtered-apis/filtered-apis.component.ts
  core/src/app/content/environments/configuration/resources/limit-ranges/limit-ranges.component.ts
  core/src/app/content/environments/configuration/resources/resource-quotas/resource-quotas.component.ts
  core/src/app/content/environments/operation/deployments/deployments.component.ts
  core/src/app/content/environments/services/environments.service.spec.ts
  core/src/app/content/environments/services/environments.service.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/edit-bindings-modal/edit-binding-modal.component.spec.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/edit-bindings-modal/edit-binding-modal.component.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-binding-service.ts
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
  core/src/app/content/settings/remote-environments/remote-environments.component.ts
  core/src/app/content/settings/remote-environments/services/remote-environments.service.spec.ts
  core/src/app/content/settings/remote-environments/services/remote-environments.service.ts
  instances/src/components/DataProvider/DataProvider.js
  instances/src/components/DataProvider/fragments.js
  instances/src/components/DataProvider/queries.js
  instances/src/components/DataProvider/subscriptions.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.container.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/queries.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateBindingModal/CreateBindingModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.container.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/mutations.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceDetails.container.js
  instances/src/components/ServiceInstanceDetails/queries.js
  instances/src/components/ServiceInstances/ServiceInstances.container.js
  instances/src/components/ServiceInstances/mutations.js
  instances/src/components/ServiceInstances/queries.js
  instances/src/store/Filter/resolvers.js
  lambda/src/app/lambdas/lambda-details/lambda-details.service.ts
  lambda/src/app/service-instances/service-instances.service.spec.ts
  lambda/src/app/service-instances/service-instances.service.ts
Labels: enhancement

#528 Setup Test bundle for service catalog tests and do a clean up after them
  tests/Dockerfile
  tests/README.md
  tests/jest-setup.js
  tests/package-lock.json
  tests/package.json
  tests/ui-tests/config.js
  tests/ui-tests/setup/helm-broker/config.js
  tests/ui-tests/setup/helm-broker/configurer.js
  tests/ui-tests/setup/kubeconfig.js
  tests/ui-tests/setup/namespace-manager.js
  tests/ui-tests/setup/test-bundle-installer.js
  tests/ui-tests/tests/catalog-ui-test.js
Labels: area/console, enhancement

#523 Determine if the user can see the admin views
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#537 Browser cache invalidation improvements
  brokers/nginx.conf
  catalog/nginx.conf
  content/nginx.conf
  core/nginx/nginx.conf
  instances/nginx.conf
  lambda/nginx/nginx.conf
Labels: area/console, bug

#541 Retry login in all UI tests
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
  tests/ui-tests/utils/logging.js
  tests/ui-tests/utils/retry.js
Labels: area/console, enhancement

#542 Skip UI tests if a required UI API Layer module is disabled
  tests/ui-tests/setup/kubeconfig.js
  tests/ui-tests/setup/test-bundle-installer.js
  tests/ui-tests/setup/test-pluggable.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
Labels: area/console, enhancement

#538 Adjust service-catalog and content views for ui-api modularisation
  brokers/package-lock.json
  brokers/package.json
  brokers/src/commons/builder.js
  brokers/src/commons/helpers.js
  brokers/src/components/App/App.component.js
  brokers/src/store/index.js
  brokers/src/store/transformers.js
  catalog/package-lock.json
  catalog/package.json
  catalog/src/commons/asyncapi.js
  catalog/src/commons/builder.js
  catalog/src/commons/helpers.js
  catalog/src/components/App/App.component.js
  catalog/src/components/Main/Main.container.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  catalog/src/components/ServiceClassDetails/styled.js
  catalog/src/components/ServiceClassList/Cards/Card.component.js
  catalog/src/components/ServiceClassList/ServiceClassList.component.js
  catalog/src/components/ServiceClassList/ServiceClassList.container.js
  catalog/src/components/ServiceClassList/styled.js
  catalog/src/store/Filter/resolvers.js
  catalog/src/store/defaults.js
  catalog/src/store/index.js
  catalog/src/store/resolvers.js
  catalog/src/store/transformers.js
  components/react/package-lock.json
  components/react/src/components/BackendModuleDisabled/index.js
  components/react/src/components/BackendModuleDisabled/styled.js
  components/react/src/components/index.js
  content/package-lock.json
  content/package.json
  content/src/App.js
  content/src/commons/builder.js
  content/src/commons/helpers.js
  content/src/commons/manifest.yaml
  content/src/components/DocsContent/DocsContent.container.js
  content/src/components/DocsContent/styled.js
  content/src/components/MainPage/MainPage.container.js
  content/src/components/MainPage/styled.js
  content/src/store/index.js
  content/src/store/transformers.js
  core/src/luigi-config/luigi-config.js
  instances/package-lock.json
  instances/package.json
  instances/src/commons/asyncapi.js
  instances/src/commons/builder.js
  instances/src/commons/helpers.js
  instances/src/components/App/App.component.js
  instances/src/components/App/RouteWrapper.js
  instances/src/components/DataProvider/DataProvider.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceDetails.component.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
  instances/src/store/ServiceInstances/events.js
  instances/src/store/index.js
  tests/package-lock.json
Labels: area/console, enhancement

#545 Test Service Bindings and Service Binding Usages in UI tests
  catalog/src/components/App/App.component.js
  catalog/src/components/App/queries.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/mutations.js
  catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  components/react/src/components/Label/index.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindingsStep.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/Resources.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/DeleteBindingModal/DeleteBindingModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ParametersDataModal/ParametersDataModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.component.js
  instances/src/components/ServiceInstances/ServiceInstancesTable/ServiceInstancesTable.component.js
  instances/src/components/ServiceInstances/ServiceInstancesToolbar/FilterDropdown.component.js
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/tests/catalog-ui-test.js
  tests/ui-tests/utils/catalogConfig.js
  tests/ui-tests/utils/serviceClassConfig.js
Labels: area/console, enhancement

#550 Show connected namespaces fix
  core/src/app/content/settings/remote-environments/remote-environment-details/edit-bindings-modal/edit-binding-modal.component.ts
  core/src/app/content/settings/remote-environments/remote-environments-entry-renderer/remote-environments-entry-renderer.component.ts
Labels: area/console, bug

#557 Update Content UI manifest
  content/src/commons/manifest.yaml
Labels: area/console, enhancement

#559 Fix a dead link
  README.md
Labels: area/documentation

#570 Fix view refresh for namespace unbinding in application details view
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
Labels: area/console, bug

#575 Checkbox and text input fixes
  core/src/assets/vendor/techne.min-2.0.0-alpha-4-modified-fiorified.css
  core/src/consoleapp.html
  core/src/styles.scss
  core/src/styles/techne-fiorification-overrides.scss
  lambda/src/assets/vendor/techne.min-2.0.0-alpha-4-modified-fiorified.css
  lambda/src/index.html
  lambda/src/styles.scss
  lambda/src/styles/_wtf-overrides.scss
  lambda/src/styles/techne-fiorification-overrides.scss
Labels: area/console

#588 Create component for rendering OData spec as a static reference docs
  components/react-odata/.gitignore
  components/react-odata/.prettierrc
  components/react-odata/README.md
  components/react-odata/package.json
  components/react-odata/public/favicon.ico
  components/react-odata/public/index.html
  components/react-odata/src/ODataFiles/ODataFav1.ts
  components/react-odata/src/ODataFiles/ODataFav11.ts
  components/react-odata/src/ODataFiles/ODataFav21.ts
  components/react-odata/src/ODataFiles/ODataFav3.ts
  components/react-odata/src/ODataFiles/ODataFav5.ts
  components/react-odata/src/ODataFiles/ODataFavourite3.ts
  components/react-odata/src/ODataFiles/ODataFile.ts
  components/react-odata/src/ODataFiles/ODataFile2.ts
  components/react-odata/src/ODataFiles/ODataNext.ts
  components/react-odata/src/ODataFiles/ODataNorthWindV2.ts
  components/react-odata/src/ODataFiles/ODataProductV2.ts
  components/react-odata/src/ODataFiles/ODataProductV4.ts
  components/react-odata/src/ODataFiles/ODataProductsV3.ts
  components/react-odata/src/ODataFiles/ODataTripV4.ts
  components/react-odata/src/ODataFiles/SAPodata.ts
  components/react-odata/src/ODataFiles/index.ts
  components/react-odata/src/ODataFiles/temp.xml
  components/react-odata/src/ODataReact.tsx
  components/react-odata/src/components/ErrorComponent/ErrorComponent.tsx
  components/react-odata/src/components/Table/MainDataTable/CollapsibleRow.tsx
  components/react-odata/src/components/Table/MainDataTable/HideableSubTable.tsx
  components/react-odata/src/components/Table/MainDataTable/Table.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/CollapsibleAnnotation.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/CollapsibleTable.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/ServiceDocumentationTable.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/SimpleTable.tsx
  components/react-odata/src/components/Table/TableContainer.tsx
  components/react-odata/src/components/Table/styled/styled.ts
  components/react-odata/src/components/Table/utils.ts
  components/react-odata/src/globalStyle.ts
  components/react-odata/src/index.tsx
  components/react-odata/src/react-app-env.d.ts
  components/react-odata/src/serviceWorker.ts
  components/react-odata/src/theme/theme.ts
  components/react-odata/src/theme/types.ts
  components/react-odata/src/tools/Parser.ts
  components/react-odata/src/tools/Transformer.ts
  components/react-odata/src/tools/V2V3toV4.ts
  components/react-odata/src/types.ts
  components/react-odata/tsconfig.json
  components/react-odata/tslint.json
  components/react-odata/yarn.lock
Labels: WIP, area/console, enhancement

#586 Add nosniff setting for MIME types on all console components
  brokers/nginx.conf
  catalog/nginx.conf
  content/nginx.conf
  core/nginx/nginx.conf
  instances/nginx.conf
  lambda/nginx/nginx.conf
Labels: area/console, area/security

#583 Read replicasets from ui-api-layer
  core/src/app/app.config.ts
  core/src/app/app.module.ts
  core/src/app/content/environments/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/environments/operation/abstract-kubernetes-element-list.component.ts
  core/src/app/content/environments/operation/kubernetes-element-list.component.html
  core/src/app/content/environments/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.html
  core/src/app/content/environments/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.spec.ts
  core/src/app/content/environments/operation/replica-sets/replica-sets-entry-renderer/replica-sets-entry-renderer.component.ts
  core/src/app/content/environments/operation/replica-sets/replica-sets-header-renderer/replica-sets-header-renderer.component.html
  core/src/app/content/environments/operation/replica-sets/replica-sets.component.ts
  core/src/app/shared/components/json-editor-modal/graphql-mutator-modal.component.ts
  core/src/app/shared/components/json-editor-modal/json-editor-modal.component.ts
  core/src/app/shared/components/json-editor-modal/json-editor/json-editor.component.ts
  core/src/app/shared/datamodel/k8s/replica-set.ts
Labels: area/console, enhancement

#593 Conditional app management
  core/package-lock.json
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.html
  core/src/app/content/settings/remote-environments/remote-environment-details/remote-environment-details.component.ts
  core/src/app/content/settings/remote-environments/remote-environments.component.html
  core/src/app/content/settings/remote-environments/remote-environments.component.ts
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#584 csp for console
  core/nginx/nginx.conf
Labels: area/console, area/security, enhancement
