Repository kyma-project/console, pull requests merged in 2019-07, with the labels that each got.

#993 Amend empty state handling in bound services and events modal
  core/src/app/content/settings/applications/application-details/bindings-details-modal/bindings-details-modal.component.html
  core/src/app/content/settings/applications/application-details/bindings-details-modal/bindings-details-modal.component.ts
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.html
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.html
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.ts
Labels: area/console, enhancement

#989 Extended header component for service instance details view
  instances/src/components/ServiceInstanceDetails/ServiceInstanceDetails.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceToolbar/ServiceInstanceToolbar.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceToolbar/styled.js
  instances/src/variables.js
Labels: area/console, enhancement

#999 Add license pulling
  add-ons/Dockerfile
  add-ons/Makefile
  brokers/Dockerfile
  brokers/Makefile
  catalog/Dockerfile
  catalog/Makefile
  content/Dockerfile
  content/Makefile
  core/Dockerfile
  core/Makefile
  instances/Dockerfile
  instances/Makefile
  lambda/Dockerfile
  lambda/Makefile
  logging/Dockerfile
  logging/Makefile
  tests/Dockerfile
  tests/Makefile
Labels: area/ci, area/community, enhancement

#1001 [Adjustment] Extended header component for service instance details view
  catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/styled.js
Labels: area/console, enhancement

#994 Move tabs to header components on service class details
  catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/styled.js
  components/react/src/components/Tabs/components.js
  components/react/src/components/Tabs/index.js
Labels: area/console

#1003 [Adjustment] Extended header component for service instance details view
  components/react/src/components/Toolbar/index.js
  components/react/src/components/Toolbar/styled.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.component.js
Labels: area/console, enhancement

#1000 Organize LogUI toggles
  logging/src/app/app.component.spec.ts
  logging/src/app/app.module.ts
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.spec.ts
  logging/src/app/search-form/search-form.component.ts
  logging/src/app/search-form/shared/appAriaDisabled.directive.ts
Labels: area/console

#997 Extended header for Application details
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.scss
  core/src/app/content/settings/applications/application-details/application-details.component.ts
  core/src/app/content/settings/applications/services/applications.service.ts
Labels: area/console, enhancement

#1014 Add ability to show health checks in Lambda logs
  logging/src/app/search-form/data/search-form-data.ts
  logging/src/app/search-form/data/search-result.ts
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.spec.ts
  logging/src/app/search-form/search-form.component.ts
  logging/src/styles.scss
Labels: area/console, area/logging, area/serverless, quality/devx

#1015 Fix left navigation
  core/src/luigi-config/navigation-helpers.js
Labels: area/console, bug

#1008 [Adjustment] Extended header component for service instance details view
  components/react/src/components/Toolbar/index.js
  components/react/src/components/Toolbar/styled.js
  core/src/app/content/settings/applications/application-details/application-details.component.html
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/styled.js
Labels: area/console, enhancement

#1016 Fix render labels in table of add-ons-ui
  add-ons/src/components/Table/FilterPopover/FilterPopover.component.tsx
  add-ons/src/components/Table/FilterPopover/FilterPopover.container.tsx
  add-ons/src/components/Table/TableContent.component.tsx
  add-ons/src/components/Table/styled.ts
  add-ons/src/constants.ts
  add-ons/src/services/Labels.service.ts
  add-ons/src/types.ts
Labels: bug

#966 Customize OpenAPI component styling
  catalog/package-lock.json
  catalog/package.json
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerApiConsole.component.js
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerConsole.component.js
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/CustomSwaggerStyles.js
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/ModelCollapse.jsx
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/Models.jsx
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/OperationTag.jsx
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/SchemesWrapper.jsx
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/assets/content-type-select-background-image.png
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/assets/responsesSelect.png
  catalog/src/components/ServiceClassDetails/SwaggerApi/SwaggerCustomComponents/assets/schemes-background-image.png
  catalog/src/components/ServiceClassDetails/SwaggerApi/plugins.js
  components/react/package-lock.json
  instances/package-lock.json
  instances/package.json
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerApiReference.component.js
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerConsole.component.js
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/CustomSwaggerStyles.js
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/ModelCollapse.jsx
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/Models.jsx
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/OperationTag.jsx
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/SchemesWrapper.jsx
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/assets/content-type-select-background-image.png
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/assets/responsesSelect.png
  instances/src/components/ServiceInstanceDetails/SwaggerApi/SwaggerCustomComponents/assets/schemes-background-image.png
  instances/src/components/ServiceInstanceDetails/SwaggerApi/plugins.js
Labels: area/console, enhancement

#1018 Lock version of fiori-fundamentals and fundamental-react
  components/react/package-lock.json
  components/react/package.json
Labels: area/console, priority/critical

#1007 Add edit namespace modal
  core/src/app/app.module.ts
  core/src/app/content/namespaces/namespace-details/namespace-details.component.html
  core/src/app/content/namespaces/namespace-details/namespace-details.component.ts
  core/src/app/content/namespaces/namespace-edit/namespace-edit.component.html
  core/src/app/content/namespaces/namespace-edit/namespace-edit.component.scss
  core/src/app/content/namespaces/namespace-edit/namespace-edit.component.spec.ts
  core/src/app/content/namespaces/namespace-edit/namespace-edit.component.ts
  core/src/app/content/namespaces/services/namespaces.service.ts
  core/src/styles/fiori-fundamentals-overrides.scss
Labels: area/console, enhancement

#1026 Add multitenancy support
  compass/package-lock.json
  compass/package.json
  compass/src/commons/builder.js
  compass/src/components/Runtimes/RuntimeList/RuntimeList.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  compass/src/config/luigi-config/main.js
  compass/src/config/luigi-config/navigation.js
  compass/src/config/luigi-config/navitagion.js
  compass/src/index.js
  compass/src/store/index.js
Labels: area/console, enhancement

#1020 Implement first dummy test for compass cockpit
  compass/src/App.test.js
  compass/src/Mock.test.js
Labels: enhancement

#1038 Fix log ui for pods without labels
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, bug

#1025 Switching to different namespace redirects to namespace details view
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.ts
  core/package-lock.json
  core/package.json
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.ts
  core/src/app/content/namespaces/namespace-details/namespace-details.component.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.ts
  core/src/app/content/namespaces/operation/services/services.component.ts
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
  core/src/app/shared/components/permissions/bindings/bindings.component.ts
  core/src/app/shared/components/permissions/roles/roles.component.ts
  core/src/luigi-config/luigi-config.js
  lambda/src/app/lambdas/list/lambdas.component.ts
Labels: area/console, bug

#1051 Create application details view
  compass/src/App.js
  compass/src/App.scss
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/styles.scss
  compass/src/components/Application/ApplicationDetails/ApplicationNotFoundMessage/ApplicationNotFoundMessage.js
  compass/src/components/Application/applicationUtility.js
  compass/src/components/Application/gql.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.js
  compass/src/components/Shared/LabelDisplay.js
  compass/src/config/luigi-config/navigation.js
  compass/src/index.js
Labels: area/console

#1049 Service broker provisioning form bug
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  catalog/src/components/ServiceClassDetails/CreateInstanceModal/SchemaData.component.js
  components/react/package-lock.json
  components/react/package.json
Labels: area/console, bug

#1057 Fix a bug with MFs not shown
  core/src/luigi-config/luigi-config.js
Labels: area/console, bug

#1046 CI build pipeline for Compass UI
  compass/.eslinterrc
  compass/.eslintignore
  compass/.prettierrc
  compass/Dockerfile
  compass/Makefile
  compass/nginx.conf
  compass/package-lock.json
  compass/package.json
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationNotFoundMessage/ApplicationNotFoundMessage.js
  compass/src/components/Overview/Overview.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.js
  compass/src/components/Runtimes/RuntimeList/RuntimeList.js
  compass/src/components/Runtimes/Runtimes.js
  compass/src/components/Runtimes/gql.js
  compass/src/components/Shared/LabelDisplay.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  compass/src/config/luigi-config/main.js
  compass/src/config/luigi-config/navigation.js
  compass/src/index.css
  compass/src/serviceWorker.js
  compass/src/store/index.js
  content/package-lock.json
  core/package-lock.json
Labels: enhancement

#1071 Create application modal
  compass/package-lock.json
  compass/package.json
  compass/src/App.component.js
  compass/src/App.container.js
  compass/src/App.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.container.js
  compass/src/components/Applications/CreateApplicationModal/labelsSchema.js
  compass/src/components/Applications/CreateApplicationModal/styles.scss
  compass/src/components/Applications/gql.js
  compass/src/components/Runtimes/RuntimeList/RuntimeList.js
  compass/src/components/Runtimes/gql.js
  compass/src/components/Shared/JSONEditor.js
  compass/src/gql.js
  compass/src/index.js
  compass/src/store/Notification/defaults.js
  compass/src/store/Notification/resolvers.js
  compass/src/store/defaults.js
  compass/src/store/index.js
  compass/src/store/resolvers.js
Labels: area/console, enhancement

#1094 Fix critical Core error
  core/src/app/content/settings/organisation/organisation.component.html
Labels: area/console, bug

#1098 Correct a dead link
  tests/README.md
Labels: area/documentation

#1106 Update compass query
  compass/src/components/Application/gql.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.container.js
  compass/src/components/Runtimes/gql.js
Labels: area/application-connector

#1091 Optimize Compass CI scripts
  compass/.gitignore
  compass/.prettierignore
  compass/Dockerfile
  compass/Makefile
Labels: area/console

#1110 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community

#1109 UUID in header
  compass/package-lock.json
  compass/package.json
  compass/src/commons/builder.js
  compass/src/components/Runtimes/gql.js
Labels: bug

#1105 Show proper data in runtimes list and details views
  compass/package-lock.json
  compass/src/App.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/styles.scss
  compass/src/components/Application/ApplicationDetails/ApplicationNotFoundMessage/ApplicationNotFoundMessage.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/test/Applications.test.js
  compass/src/components/Applications/test/__snapshots__/Applications.test.js.snap
  compass/src/components/Applications/test/mock.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.container.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Runtimes/RuntimeList/RuntimeList.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Runtimes/Runtimes.container.js
  compass/src/components/Runtimes/Runtimes.js
  compass/src/components/Runtimes/gql.js
  compass/src/components/Shared/ResourceNotFound.component.js
  compass/src/components/Shared/StatusBadge/StatusBadge.js
  compass/src/components/Shared/StatusBadge/test/StatusBadge.test.js
  compass/src/components/Shared/StatusBadge/test/__snapshots__/StatusBadge.test.js.snap
  compass/src/config/luigi-config/navigation.js
  compass/src/shared/components/GenericList/GenericList.js
  compass/src/shared/constants.js
  compass/src/shared/styles/header.scss
  compass/src/store/index.js
Labels: area/console, enhancement

#1107 Create runtime modal
  compass/src/App.scss
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.component.js
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.container.js
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.js
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.scss
  compass/src/components/Runtimes/CreateRuntimeForm/test/CreateRuntimeForm.test.js
  compass/src/components/Runtimes/CreateRuntimeForm/test/__snapshots__/CreateRuntimeForm.test.js.snap
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Runtimes/gql.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.component.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.container.js
  compass/src/shared/components/ModalWithForm/test/ModalWithForm.test.js
  compass/src/shared/components/ModalWithForm/test/__snapshots__/ModalWithForm.test.js.snap
  compass/src/shared/typechecking/CustomPropTypes.js
  compass/src/shared/typechecking/CustomPropTypes.test.js
  compass/src/shared/typechecking/__snapshots__/CustomPropTypes.test.js.snap
Labels: enhancement

#1118 Fix not hiding backdrop issue in lambdas
  lambda/src/app/lambdas/lambda-details/event-trigger-chooser/event-trigger-chooser.component.ts
  lambda/src/app/lambdas/lambda-details/http-trigger/http-trigger.component.ts
Labels: area/console, bug

#1093 Application details & APIs CD [Compass]
  compass/package-lock.json
  compass/package.json
  compass/src/App.scss
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.container.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.container.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationScenarioDisplay/ApplicationScenarioDisplay.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/APICreationHelper.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/APIUploadHelper.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/CreateAPIModal.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/CreateAPIModal.container.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/APIUploadHelper.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/ApiDataForm.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/CredentialsForm.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/FileInput.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/TextFormItem.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/style.scss
  compass/src/components/Application/applicationUtility.js
  compass/src/components/Application/gql.js
  compass/src/components/Shared/LabelDisplay.js
  compass/src/config/luigi-config/navigation.js
  compass/src/shared/components/GenericList/GenericList.js
  compass/src/store/Notification/resolvers.js
  compass/src/store/index.js
Labels: area/console, enhancement
