Repository kyma-project/console, pull requests merged in 2019-08, with the labels that each got.

#1121 Add compass-system to the list of system namespaces
  core/src/luigi-config/luigi-config.js
Labels: area/console

#1117 Assign Application To Scenario [Compass]
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.container.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationScenarioModal.container.js
  compass/src/components/Application/ApplicationDetails/ApplicationScenarioDisplay/ApplicationScenarioDisplay.js
  compass/src/components/Application/gql.js
  compass/src/components/Shared/AssignScenarioModal/AssignScenarioModal.component.js
  compass/src/components/Shared/AssignScenarioModal/style.scss
  compass/src/components/Shared/gql.js
Labels: area/console

#1134 Fix links
  .github/pull-request-template.md
  tests/README.md
Labels: area/documentation

#1112 Update codeowners in console
  CODEOWNERS
Labels: area/console

#1137 Fix audit vulnerabilities
  catalog/package-lock.json
  compass/package-lock.json
  components/angular/generic-list/package-lock.json
  components/react-odata/package-lock.json
  components/react/package-lock.json
  content/package-lock.json
  core/package-lock.json
  core/package.json
  instances/package-lock.json
  lambda/package-lock.json
  lambda/package.json
  logging/package-lock.json
  logging/package.json
  tests/package-lock.json
Labels: area/console

#1113 Fix for lambda ui not preloading
  core/angular.json
  core/src/luigi-config/local-development-node-converter.js
  core/src/luigi-config/microfrontend-converter.js
  core/src/luigi-config/navigation-helpers.js
  core/src/luigi-config/rbac-rules-matcher.js
Labels: area/console

#1145 Create Label Definition [Compass]
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/ApiDataForm.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/style.scss
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.container.js
  compass/src/components/Labels/CreateLabelModal/LabelSpecificationUploadHelper.js
  compass/src/components/Labels/gql.js
  compass/src/components/Shared/FileInput/FileInput.js
  compass/src/components/Shared/FileInput/style.scss
Labels: area/console

#1133 Remove odata component
  add-ons/src/core/styled.ts
  catalog/.gitignore
  components/react-odata/.gitignore
  components/react-odata/Makefile
  components/react-odata/README.md
  components/react-odata/package-lock.json
  components/react-odata/package.json
  components/react-odata/public/favicon.ico
  components/react-odata/public/index.html
  components/react-odata/src/ODataFiles/ODataFav1.ts
  components/react-odata/src/ODataFiles/ODataFav11.ts
  components/react-odata/src/ODataFiles/ODataFav21.ts
  components/react-odata/src/ODataFiles/ODataFav3.ts
  components/react-odata/src/ODataFiles/ODataFav5.ts
  components/react-odata/src/ODataFiles/ODataFavourite3.ts
  components/react-odata/src/ODataFiles/ODataFile.ts
  components/react-odata/src/ODataFiles/ODataFile2.ts
  components/react-odata/src/ODataFiles/ODataNext.ts
  components/react-odata/src/ODataFiles/ODataNorthWindV2.ts
  components/react-odata/src/ODataFiles/ODataProductV2.ts
  components/react-odata/src/ODataFiles/ODataProductV4.ts
  components/react-odata/src/ODataFiles/ODataProductsV3.ts
  components/react-odata/src/ODataFiles/ODataTripV4.ts
  components/react-odata/src/ODataFiles/index.ts
  components/react-odata/src/ODataReact.tsx
  components/react-odata/src/components/ErrorComponent/ErrorComponent.tsx
  components/react-odata/src/components/Table/MainDataTable/CollapsibleRow.tsx
  components/react-odata/src/components/Table/MainDataTable/HideableSubTable.tsx
  components/react-odata/src/components/Table/MainDataTable/Table.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/CollapsibleAnnotation.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/CollapsibleTable.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/ServiceDocumentationTable.tsx
  components/react-odata/src/components/Table/ServiceDocumentationTable/SimpleTable.tsx
  components/react-odata/src/components/Table/TableContainer.tsx
  components/react-odata/src/components/Table/utils.ts
  components/react-odata/src/components/styled/styled.ts
  components/react-odata/src/index.tsx
  components/react-odata/src/react-app-env.d.ts
  components/react-odata/src/tools/Parser.ts
  components/react-odata/src/tools/Transformer.ts
  components/react-odata/src/tools/V2V3toV4.ts
  components/react-odata/src/types.ts
  components/react-odata/tsconfig.json
  components/react-odata/tslint.json
  instances/.gitignore
  lerna.json
  package.json
  scripts/prepare-react-odata.sh
Labels: enhancement

#1149 Fix compass reload bug
  compass/package.json
Labels: area/console, bug

#1143 Add label definitions list view
  compass/src/App.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitions.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitions.container.js
  compass/src/components/MetadataDefinitions/gql.js
  compass/src/config/luigi-config/navigation.js
Labels: area/console, enhancement

#1142 Refactor credentials form [Compass]
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/APICreationHelper.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/CreateAPIModal.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/CredentialForms/OAuthCredentialsForm.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/CredentialsForm.js
  compass/src/components/Shared/AssignScenarioModal/style.scss
Labels: area/console

#1154 Clear idppreset modal form after closing it
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts
Labels: area/console, bug

#1162 Fix create metadata definition bug
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.container.js
  compass/src/components/Labels/gql.js
Labels: area/console

#1148 Searching Applications ( Runtimes/ Scenarios) (no longer) breaks the page
  compass/package-lock.json
  compass/package.json
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/CredentialsForm.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/shared/components/GenericList/GenericList.js
  compass/src/shared/components/GenericList/SearchInput.js
  compass/src/shared/components/GenericList/helpers.js
  compass/src/shared/components/GenericList/style.scss
  compass/src/shared/components/GenericList/test/GenericList.test.js
  compass/src/shared/components/GenericList/test/__snapshots__/GenericList.test.js.snap
Labels: area/console

#1141 Enable Scenario for a Runtime [Compass]
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationScenarioModal.container.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarioDecorator.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarioModal.container.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.container.js
  compass/src/components/Runtimes/gql.js
  compass/src/components/Shared/AssignScenario/AssignScenarioForm.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioForm.container.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  compass/src/components/Shared/AssignScenario/style.scss
  compass/src/components/Shared/AssignScenarioModal/AssignScenarioModal.component.js
Labels: area/console

#1135 Fix dropdowns in console core
  components/angular/generic-list/src/app/modules/list/list-element-actions/list-element-actions.component.scss
  core/package-lock.json
  core/package.json
  core/src/app/app.module.ts
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.html
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.scss
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.spec.ts
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.html
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.spec.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.ts
  core/src/app/shared/directives/filter-all-on-selected/filter-all-on-selected.directive.spec.ts
  core/src/app/shared/directives/filter-all-on-selected/filter-all-on-selected.directive.ts
Labels: area/console, bug

#1166 Fix link and formatting
  README.md
Labels: area/documentation

#1155 Enable addons-ui in namespace scope
  add-ons/README.md
  add-ons/package-lock.json
  add-ons/package.json
  add-ons/public/index.html
  add-ons/src/components/Modals/AddNewConfigurationModal/AddNewConfigurationModal.container.tsx
  add-ons/src/components/Table/TableContent.component.tsx
  add-ons/src/components/Table/styled.ts
  add-ons/src/components/Toolbar/Toolbar.component.tsx
  add-ons/src/constants.ts
  add-ons/src/core/app-initializer.ts
  add-ons/src/services/Configurations.service.ts
  add-ons/src/services/Mutations.service.ts
  add-ons/src/services/Queries.service.ts
  add-ons/src/services/Subscriptions.service.ts
  core/src/app/app.config.ts
  core/src/luigi-config/local-development-node-converter.js
  core/src/luigi-config/luigi-config.js
Labels: enhancement

#1151 Label definition details
  compass/package-lock.json
  compass/package.json
  compass/src/App.component.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/MetadataDefinitionDetails.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/MetadataDefinitionDetails.container.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/MetadataDefinitionDetails.test.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/__snapshots__/MetadataDefinitionDetails.test.js.snap
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/mock.js
  compass/src/components/MetadataDefinitions/MetadataDefinitions.component.js
  compass/src/components/MetadataDefinitions/gql.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Scenarios/Scenarios.component.js
  compass/src/config/luigi-config/navigation.js
Labels: area/console, enhancement

#1160 Fix remaining npm audit vulnerabilities
  add-ons/package-lock.json
  components/react/package-lock.json
  content/package-lock.json
  package-lock.json
  service-catalog-ui/brokers/package-lock.json
  service-catalog-ui/catalog/package-lock.json
  service-catalog-ui/instances/package-lock.json
Labels: area/console

#1165 Add scenario to application at creation
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
Labels: area/console, enhancement

#1168 Add missing fd-panel-title directive in many places
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.html
  components/angular/generic-list/src/app/modules/list/generic-table/generic-table.component.html
  core/src/app/content/namespaces/namespace-details/namespace-details.component.html
  core/src/app/content/namespaces/operation/kubernetes-element-list-compact.component.html
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.scss
  core/src/app/shared/components/permissions/bindings/bindings.component.html
  core/src/app/shared/components/permissions/role-details/role-details.component.html
Labels: area/console, bug

#1170 Fix dropdowns behaviour on outsideclick event
  core/src/app/shared/directives/filter-all-on-selected/filter-all-on-selected.directive.ts
Labels: area/console, bug

#1176 Permanently display "show istio proxy logs" toggle
  logging/src/app/search-form/data/search-form-data.ts
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.spec.ts
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, enhancement

#1157 Create Scenario
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationScenarioModal.container.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/CreateAPIModal.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/style.scss
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.container.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarioModal.container.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioForm/CreateScenarioForm.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioForm/CreateScenarioForm.container.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioForm/style.scss
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.container.js
  compass/src/components/Scenarios/Scenarios.component.js
  compass/src/components/Scenarios/gql.js
  compass/src/components/Shared/AssignScenario/AssignScenarioForm.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioForm.container.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.container.js
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
  compass/src/components/Shared/MultiChoiceList/style.scss
  compass/src/components/Shared/MultiChoiceList/test/MultiChoiceList.test.js
  compass/src/components/Shared/MultiChoiceList/test/__snapshots__/MultiChoiceList.test.js.snap
  compass/src/components/Shared/MultiChoiceList/test/mockData.js
Labels: area/console

#1181 Fix multi-choice list [Compass]
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
  compass/src/components/Shared/MultiChoiceList/test/MultiChoiceList.test.js
  compass/src/components/Shared/MultiChoiceList/test/__snapshots__/MultiChoiceList.test.js.snap
Labels: area/console

#1173 Display "show" category whenever "function" label is present
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, bug

#1171 Improve tab counter appearance in Instances
  .gitignore
  components/react/src/components/Tabs/Tab/index.js
  service-catalog-ui/catalog/src/commons/helpers.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/styled.js
Labels: area/console, bug

#1175 Sort logs
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, bug

#1184 Empty plans
  components/react/src/components/Forms/Select/index.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/CreateInstanceModal/BasicData.component.js
Labels: area/console, bug

#1178 Disable Bind application button in case no applications are available
  service-catalog-ui/instances/package-lock.json
  service-catalog-ui/instances/package.json
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/Resources.component.js
Labels: area/console, area/service-catalog, enhancement

#1174 Delete API from API Details View
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.ts
Labels: area/console, enhancement

#1172 Disable metrics button if there is no grafana backendmodule
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/app.module.ts
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.html
  lambda/src/app/lambdas/list/lambdas-entry-renderer/lambdas-entry-renderer.component.ts
  lambda/src/app/lambdas/list/lambdas-header-renderer/lambdas-header-renderer.component.html
  lambda/src/app/lambdas/list/lambdas-header-renderer/lambdas-header-renderer.component.spec.ts
  lambda/src/app/lambdas/list/lambdas-header-renderer/lambdas-header-renderer.component.ts
  lambda/src/app/shared/services/luigi-client.service.ts
Labels: area/console, bug

#1177 Bump lodash.template to 4.5.0
  compass/package-lock.json
  package-lock.json
  service-catalog-ui/brokers/package-lock.json
Labels: area/console, dependencies

#1198 Duplicated Service Classes on Catalog View in case add-on applied twice
  service-catalog-ui/catalog/src/store/Filter/resolvers.js
Labels: area/console, bug

#1192 Edit API for Application
  compass/package-lock.json
  compass/package.json
  compass/src/App.component.js
  compass/src/App.scss
  compass/src/components/Api/APICreationHelper.js
  compass/src/components/Api/APIUploadHelper.js
  compass/src/components/Api/EditApi/APIGeneralInformationForm.js
  compass/src/components/Api/EditApi/APISpecForm/APISpecForm.js
  compass/src/components/Api/EditApi/APISpecForm/style.scss
  compass/src/components/Api/EditApi/APIViewModel.js
  compass/src/components/Api/EditApi/EditApi.component.js
  compass/src/components/Api/EditApi/EditApi.container.js
  compass/src/components/Api/EditApi/EditApiTabs.component.js
  compass/src/components/Api/EditApi/Header/EditApiHeader.component.js
  compass/src/components/Api/EditApi/Header/EditApiHeader.container.js
  compass/src/components/Api/EditApi/gql.js
  compass/src/components/Api/EditApi/style.scss
  compass/src/components/Api/Forms/ApiDataForm.js
  compass/src/components/Api/Forms/CredentialForms/CredentialsForm.js
  compass/src/components/Api/Forms/CredentialForms/OAuthCredentialsForm.js
  compass/src/components/Api/Forms/CredentialForms/style.scss
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/CreateAPIModal.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/Forms/APIUploadHelper.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioForm/CreateScenarioForm.component.js
  compass/src/components/Shared/ResourceNotFound.component.js
  compass/src/components/Shared/TextFormItem.js
  compass/src/config/luigi-config/navigation.js
Labels: area/console

#1206 Apis details
  compass/package-lock.json
  compass/package.json
  compass/src/App.component.js
  compass/src/components/Api/ApiDetails/ApiDetails.component.js
  compass/src/components/Api/ApiDetails/ApiDetails.container.js
  compass/src/components/Api/ApiDetails/ApiDetails.scss
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/ApiDetailsHeader.js
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/test/ApiDetailsHeader.test.js
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/test/__snapshots__/ApiDetailsHeader.test.js.snap
  compass/src/components/Api/ApiDetails/test/ApiDetails.test.js
  compass/src/components/Api/gql.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Overview/Overview.js
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Shared/StatusBadge/StatusBadge.js
  compass/src/config/luigi-config/navigation.js
  compass/src/shared/components/DocumentationComponent/DocumentationComponent.js
  compass/src/shared/components/GenericList/GenericList.js
  compass/src/shared/components/GenericList/internalRenderers.js
  compass/src/shared/components/InProgressMessage/InProgressMessage.component.js
  compass/src/shared/components/InProgressMessage/InProgressMessage.scss
  compass/src/shared/components/ModalWithForm/ModalWithForm.component.js
  compass/src/shared/components/PanelEntry/PanelEntry.component.js
  compass/src/shared/components/PanelEntry/test/PanelEntry.test.js
  compass/src/shared/components/PanelEntry/test/__snapshots__/PanelEntry.test.js.snap
  compass/src/shared/styles/header.scss
  compass/src/shared/typechecking/CustomPropTypes.js
  compass/src/shared/typechecking/CustomPropTypes.test.js
  compass/src/shared/typechecking/__snapshots__/CustomPropTypes.test.js.snap
Labels: area/console, enhancement

#1194 Configure logoutUrl to break infinite redirection loop
  core/package-lock.json
  core/package.json
  core/src/luigi-config/luigi-config.js
Labels: area/console, bug
