Repository kyma-project/console, pull requests merged in 2019-12, with the labels that each got.

#1429 Add 'charset' setting to Core and Compass
  compass/public-luigi/index.html
  core/src/index.html
Labels: area/console, bug

#1440 Change SearchInput behaviour
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/ScenarioApplications.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/test/__snapshots__/ScenarioApplications.test.js.snap
  compass/src/components/Scenarios/ScenarioDetails/ScenarioDetails.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioDetails.scss
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/ScenarioRuntimes.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/test/__snapshots__/ScenarioRuntimes.test.js.snap
  compass/src/components/Scenarios/ScenarioDetails/test/__snapshots__/ScenarioDetails.test.js.snap
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/style.scss
  shared/components/GenericList/test/__snapshots__/GenericList.test.js.snap
Labels: area/console, enhancement

#1427 Tenant chooser doesn't change the current tenant for the current view in Compass UI
  compass/package-lock.json
  compass/package.json
  compass/public-luigi/config/config.js
  compass/src/ApolloClientProvider.js
  compass/src/commons/builder.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  compass/src/config/luigi-config/navigation.js
  compass/src/index.js
  compass/src/store/index.js
  shared/contexts/ApplicationContext.js
  shared/index.js
Labels: area/console, bug

#1453 Add support for open API, fix proptypes error in compass
  compass/src/components/Api/ApiDetails/ApiDetails.component.js
  components/generic-documentation/src/render-engines/open-api/plugins.tsx
Labels: area/console, enhancement

#1454 Service Instance Details view not refetching Instance data
  service-catalog-ui/instances/src/store/index.js
Labels: area/console, bug

#1441 Select Auth method if login form is not available
  tests/ui-tests/commands/console.js
Labels: area/console, test-failing

#1436 Update React Fundamental in Compass
  compass/package-lock.json
  compass/package.json
  compass/src/App.scss
  compass/src/components/Api/Forms/ApiDataForm.js
  compass/src/components/Api/Forms/CredentialForms/CredentialsForm.js
  compass/src/components/Api/Forms/CredentialForms/style.scss
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.component.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.component.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.container.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/__snapshots__/ConnectApplicationModal.test.js.snap
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/CreateAPIModal.component.js
  compass/src/components/Application/ApplicationDetails/CreateAPIModal/style.scss
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/UpdateApplicationForm.component.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/UpdateApplicationForm.test.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/__snapshots__/UpdateApplicationForm.test.js.snap
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/MetadataDefinitionDetails.ui.test.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/MetadataDefinitionDetails.unit.test.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/__snapshots__/MetadataDefinitionDetails.ui.test.js.snap
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/test/__snapshots__/MetadataDefinitionDetails.unit.test.js.snap
  compass/src/components/MetadataDefinitions/test/MetadataDefinitions.ui.test.js
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.component.js
  compass/src/components/Runtimes/CreateRuntimeForm/test/CreateRuntimeForm.test.js
  compass/src/components/Runtimes/CreateRuntimeForm/test/__snapshots__/CreateRuntimeForm.test.js.snap
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/ScenarioDetails/shared/AssignEntityToScenarioModal/AssignEntityToScenarioModal.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
  compass/src/components/Shared/MultiChoiceList/style.scss
  compass/src/components/Shared/MultiChoiceList/test/MultiChoiceList.test.js
  compass/src/components/Shared/MultiChoiceList/test/__snapshots__/MultiChoiceList.test.js.snap
  compass/src/components/Shared/ScenariosDisplay/test/ScenarioDisplay.test.js
  compass/src/setupTests.js
  compass/src/shared/components/Modal/Modal.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.component.js
  compass/src/shared/components/ModalWithForm/test/__snapshots__/ModalWithForm.test.js.snap
  components/react/package-lock.json
  core/package-lock.json
  lambda/package-lock.json
  logging/package-lock.json
  package-lock.json
Labels: area/console, bug

#1460 Rewrite ListActions component
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/test/ScenarioApplications.test.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/test/__snapshots__/ScenarioApplications.test.js.snap
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/test/ScenarioRuntimes.test.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/test/__snapshots__/ScenarioRuntimes.test.js.snap
  jsconfig.json
  package-lock.json
  package.json
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/GenericList.scss
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/helpers.js
  shared/components/GenericList/internalRenderers.js
  shared/components/GenericList/test/GenericList.test.js
  shared/components/GenericList/test/__snapshots__/GenericList.test.js.snap
  shared/components/GenericList/test/__snapshots__/internalRenderers.test.js.snap
  shared/components/GenericList/test/internalRenderers.test.js
  shared/components/GenericList/test/mock.js
  shared/components/ListActions/ListActions.js
  shared/components/ListActions/ListActions.scss
  shared/components/ListActions/test/ListActions.test.js
  shared/components/ListActions/test/__snapshots__/ListActions.test.js.snap
  shared/components/__mocks__/popper.js.js
  shared/jestSetup.js
  shared/package.json
Labels: area/console, enhancement

#1463 Fix ModalWithForm behaviour
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.component.js
  compass/src/components/Runtimes/CreateRuntimeForm/CreateRuntimeForm.scss
  compass/src/components/Runtimes/CreateRuntimeForm/test/__snapshots__/CreateRuntimeForm.test.js.snap
  compass/src/shared/components/Modal/ControlledModal.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.component.js
  compass/src/shared/components/ModalWithForm/test/__snapshots__/ModalWithForm.test.js.snap
Labels: area/console, bug

#1470 Prevent popover from opening upwards
  components/angular/generic-list/src/app/modules/list/list-filter/list-filter.component.html
  core/src/styles.scss
Labels: area/console, bug

#1475 Update the main README.md doc
  components/generic-documentation/README.md
Labels: area/documentation

#1480 Show a message if an error occurred while getting bindable resources
  components/react/package-lock.json
  core/package-lock.json
  lambda/package-lock.json
  logging/package-lock.json
  package-lock.json
  package.json
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
Labels: area/console, bug

#1443 Switch from asset-store to rafter resources in documentation-component
  common/src/index.ts
  common/src/services/global/global.types.ts
  common/src/types/index.ts
  common/src/types/rafter.ts
  common/src/types/service-catalog.ts
  components/generic-documentation/src/index.tsx
  components/generic-documentation/src/loader/index.ts
  components/generic-documentation/src/loader/loader.ts
  content/src/components/Content.tsx
  content/src/index.tsx
  content/src/services/clusterAssetGroups.service.ts
  content/src/services/docsTopics.service.ts
  content/src/services/index.ts
  content/src/services/navigation.service.ts
  content/src/services/queries.service.ts
  content/src/services/types.ts
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/queries.js
  service-catalog-ui/catalog/src/testing/serviceClassesMocks.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/test/mocks.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
  service-catalog-ui/instances/src/queries/fragments.js
  service-catalog-ui/instances/src/testing/instanceMocks.js
  tests/ui-tests/tests/docs-ui-test.js
Labels: area/core-and-supporting, area/documentation, enhancement

#1478 Create a view for creating a simple API rule
  core-ui/src/components/ApiRuleCreationDraft/AccessStrategy.js
  core-ui/src/components/ApiRuleCreationDraft/ApiRuleCreationDraft.js
  core-ui/src/components/ApiRules/CreateApiRule/AccessStrategy/AccessStrategy.js
  core-ui/src/components/ApiRules/CreateApiRule/AccessStrategy/test/AccessStrategy.test.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.scss
  core-ui/src/components/ApiRules/CreateApiRule/ServicesDropdown/ServicesDropdown.js
  core-ui/src/components/ApiRules/CreateApiRule/ServicesDropdown/test/ServicesDropdown.test.js
  core-ui/src/components/ApiRules/CreateApiRule/ServicesDropdown/test/__snapshots__/ServicesDropdown.test.js.snap
  core-ui/src/components/ApiRules/CreateApiRule/test/CreateApiRule.test.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/test/Lambdas.test.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/setupTests.js
  core-ui/src/testing/queriesMocks.js
  core-ui/src/testing/servicesMocks.js
  core/src/app/app.config.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.service.ts
  core/src/luigi-config/luigi-config.js
  shared/components/InputWithSuffix/InputWithSuffix.js
  shared/components/InputWithSuffix/InputWithSuffix.scss
  shared/components/InputWithSuffix/test/InputWithSuffix.test.js
  shared/components/K8sNameInput/K8sNameInput.js
  shared/index.js
Labels: area/console, enhancement

#1481 Remove https:// prefix if it's already there
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.html
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts
Labels: area/console, bug

#1482 Use view groups in compass
  compass/src/config/luigi-config/navigation.js
Labels: area/console, enhancement

#1483 IDP Preset overwritten on Lambda Save
  .clusterConfig.default
  core/src/app/app.config.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.service.ts
  lambda/src/app/app.config.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
Labels: area/console, bug

#1487 Fix dead links
  README.md
Labels: area/documentation

#1489 Fix console.err error
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/BindApplicationModal/BindApplicationModal.component.js
Labels: area/console, bug

#1488 Fix colors on namespaces search
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.scss
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/__snapshots__/NamespaceListHeader.test.js.snap
Labels: area/console, bug

#1492 Fix a dead link
  README.md
Labels: area/documentation, bug
