Repository kyma-project/console, pull requests merged in 2019-10, with the labels that each got.

#1292 Namespace list
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/NamespaceList/NamespaceList.js
  core-ui/src/components/NamespaceList/NamespaceList.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.scss
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/NamespaceDetailsCard.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/__snapshots__/NamespaceDetailsCard.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/getPodsRatioColor.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespacesGrid.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespacesGrid.scss
  core-ui/src/components/NamespaceList/NamespacesGrid/test/NamespaceGrid.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/test/__snapshots__/NamespaceGrid.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/NamespaceFilters.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/test/NamespaceFilters.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/test/__snapshots__/NamespaceFilters.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.scss
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.ui.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/__snapshots__/NamespaceListHeader.test.js.snap
  core-ui/src/components/NamespaceList/storage.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
  core-ui/src/queries/queries.js
  core-ui/src/setupTests.js
  core-ui/src/shared/constants.js
  package-lock.json
  package.json
Labels: area/console, enhancement

#1303 Change starting domain for Compass UI
  compass/package.json
Labels: area/console

#1306 Improve namespace card
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.scss
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/NamespaceDetailsCard.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/__snapshots__/NamespaceDetailsCard.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespacesGrid.scss
Labels: area/console, enhancement

#1322 Disable core and lambdas tests
  tests/package.json
Labels: area/console, test-failing

#1323 Create namespace modal improvements
  core-ui/src/components/CreateNamespaceForm/CreateNamespaceForm.js
  core-ui/src/components/CreateNamespaceForm/CreateNamespaceForm.scss
  core-ui/src/components/CreateNamespaceForm/K8sNameField.js
  core-ui/src/components/CreateNamespaceForm/test/CreateNamespaceForm.test.js
  core-ui/src/components/LabelSelectorInput/LabelSelectorInput.js
  core-ui/src/components/LabelSelectorInput/LabelSelectorInput.scss
  core-ui/src/components/LabelSelectorInput/test/LabelSelectorInput.test.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.scss
  core-ui/src/components/typechecking/CustomPropTypes.js
  core-ui/src/components/typechecking/test/CustomPropTypes.test.js
  core-ui/src/setupTests.js
Labels: area/console, enhancement

#1304 Namespace list node integration
  README.md
  core-ui/src/commons/api-url.js
  core-ui/src/commons/builder.js
  core-ui/src/components/App/App.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/__snapshots__/NamespaceDetailsCard.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespacesGrid.js
  core-ui/src/components/NamespaceList/storage.js
  core-ui/src/index.js
  core-ui/src/shared/constants.js
  core/src/app/content/settings/organisation/organisation.component.html
  core/src/app/content/settings/organisation/organisation.component.ts
  core/src/app/shared/constants/constants.ts
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/microfrontend-converter.js
Labels: area/console

#1330 Fix LabelSelectorInput invalid state
  core-ui/src/components/LabelSelectorInput/LabelSelectorInput.js
  core-ui/src/components/LabelSelectorInput/LabelSelectorInput.scss
Labels: area/console, bug

#1319 Lambdas list
  compass/src/App.scss
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/components/Lambdas/test/Lambdas.test.js
  core-ui/src/components/Lambdas/test/__snapshots__/Lambdas.test.js.snap
  core-ui/src/components/NamespaceList/NamespaceList.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/index.scss
  core-ui/src/setupTests.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core-ui/src/shared/components/GenericList/SearchInput.js
  core-ui/src/shared/components/GenericList/actionHandlers/simpleDelete.js
  core-ui/src/shared/components/GenericList/helpers.js
  core-ui/src/shared/components/GenericList/internalRenderers.js
  core-ui/src/shared/components/GenericList/style.scss
  core-ui/src/shared/components/GenericList/test/GenericList.test.js
  core-ui/src/shared/components/GenericList/test/__snapshots__/GenericList.test.js.snap
  core-ui/src/shared/components/GenericList/test/__snapshots__/internalRenderers.test.js.snap
  core-ui/src/shared/components/GenericList/test/internalRenderers.test.js
  core-ui/src/shared/components/GenericList/test/mock.js
  core-ui/src/shared/components/Labels/Labels.js
  core-ui/src/shared/components/Labels/test/Labels.test.js
  core-ui/src/shared/components/Labels/test/__snapshots__/Labels.test.js.snap
  core-ui/src/shared/components/LambdaStatusBadge/LambdaStatusBadge.js
  core-ui/src/shared/components/LambdaStatusBadge/test/LambdaStatusBadge.test.js
  core-ui/src/shared/components/LambdaStatusBadge/test/__snapshots__/LambdaStatusBadge.test.js.snap
  core-ui/src/shared/components/Spinner/Spinner.js
  core-ui/src/shared/constants.js
  core-ui/src/testing/index.js
  core-ui/src/testing/lambdaMocks.js
  core-ui/src/testing/queriesMocks.js
  logging/src/App.scss
  package-lock.json
Labels: area/console, area/serverless, enhancement

#1328 Fix bugged 'submit' button behaviour
  service-catalog-ui/catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
Labels: area/console, bug

#1331 Create function
  components/react/package-lock.json
  core-ui/src/components/App/App.js
  core-ui/src/components/CreateNamespaceForm/CreateNamespaceForm.js
  core-ui/src/components/CreateNamespaceForm/test/CreateNamespaceForm.test.js
  core-ui/src/components/CreateNamespaceForm/test/gqlMocks.js
  core-ui/src/components/K8sNameInput/K8sNameInput.js
  core-ui/src/components/LabelSelectorInput/LabelSelectorInput.js
  core-ui/src/components/LabelSelectorInput/test/LabelSelectorInput.test.js
  core-ui/src/components/LabelSelectorInput/test/__snapshots__/LabelSelectorInput.test.js.snap
  core-ui/src/components/Lambdas/CreateLambdaForm/CreateLambdaForm.js
  core-ui/src/components/Lambdas/CreateLambdaForm/test/CreateLambdaForm.test.js
  core-ui/src/components/Lambdas/CreateLambdaForm/test/gqlMocks.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/gql/mutations.js
  core-ui/src/index.scss
  core-ui/src/testing/index.js
  core/package-lock.json
  lambda/package-lock.json
  logging/package-lock.json
  package-lock.json
Labels: area/console, enhancement

#1336 Update gql type for create application mutation
  compass/src/components/Applications/gql.js
Labels: area/console, enhancement

#1349 fix links
  add-ons/README.md
  content/README.md
  core-ui/README.md
  service-catalog-ui/brokers/README.md
  service-catalog-ui/catalog/README.md
  service-catalog-ui/instances/README.md
Labels: area/documentation

#1342 Read query params to open create namespace modal
  core-ui/src/components/Lambdas/CreateLambdaForm/CreateLambdaForm.js
  core-ui/src/components/Lambdas/test/Lambdas.test.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/NamespaceList/NamespaceList.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.ui.test.js
Labels: area/console, bug

#1353 Scenario improvements [Compass]
  compass/public-luigi/config/config.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.container.js
  compass/src/components/Scenarios/EnititesForScenarioCount.js
  compass/src/components/Scenarios/Scenarios.component.js
  compass/src/components/Scenarios/gql.js
  compass/src/components/Shared/LabelDisplay.js
Labels: area/console, enhancement
