Repository kyma-project/console, pull requests merged in 2019-11, with the labels that each got.

#1365 Fix context switcher 'create namespace' behaviour
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.ui.test.js
Labels: area/console, bug

#1360 Navigate to namespace details after namespace creation
  core-ui/src/components/CreateNamespaceForm/CreateNamespaceForm.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
Labels: area/console, enhancement

#1364 Return to catalog with selected tab
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.component.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesList.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesTable/ServiceInstancesTable.component.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/test/ServiceInstancesList.test.js
Labels: area/console, enhancement

#1367 Runtime List view (un)broken
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Shared/LabelDisplay.js
  compass/src/components/Shared/ScenariosDisplay/ScenariosDisplay.js
  compass/src/components/Shared/ScenariosDisplay/test/ScenarioDisplay.test.js
  compass/src/components/Shared/ScenariosDisplay/test/__snapshots__/ScenarioDisplay.test.js.snap
Labels: area/console, enhancement

#1346 Update Application [Compass]
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/test/ApiDetailsHeader.test.js
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/test/__snapshots__/ApiDetailsHeader.test.js.snap
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/UpdateApplicationForm.component.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/UpdateApplicationForm.container.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/UpdateApplicationForm.test.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/__snapshots__/UpdateApplicationForm.test.js.snap
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/mock.js
  compass/src/components/Application/gql.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Scenarios/ScenarioDetails/shared/AssignEntityToScenarioModal/AssignEntityToScenarioModal.component.js
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
  compass/src/components/Shared/MultiChoiceList/test/__snapshots__/MultiChoiceList.test.js.snap
  compass/src/shared/components/ModalWithForm/ModalWithForm.component.js
  compass/src/shared/components/ModalWithForm/test/ModalWithForm.test.js
  compass/src/shared/utility/areArraysEqual.js
  compass/src/shared/utility/getActualChanges.js
  compass/src/shared/utility/index.js
Labels: area/console, enhancement

#1374 Update system namespaces
  core/src/luigi-config/luigi-config.js
Labels: area/console

#1351 Edit function
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/App/App.js
  core-ui/src/components/EntryNotFound/EntryNotFound.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/test/LambdaDetailsHeader.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/test/__snapshots__/LambdaDetailsHeader.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/test/Code.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/test/Configuration.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/test/__snapshots__/Code.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/test/__snapshots__/Configuration.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/test/mocks.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetailsWrapper.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/__snapshots__/LambdaDetailsWrapper.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/test/gqlMocks.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/index.scss
  core-ui/webpack.config.js
  package-lock.json
Labels: area/console, area/serverless, enhancement

#1377 Manage function dependencies
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaCode.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaDependencies.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/test/CodeTab.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/test/LambdaCode.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/test/LambdaDependencies.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/test/__snapshots__/CodeTab.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/test/__snapshots__/LambdaCode.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/test/__snapshots__/LambdaDependencies.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/Configuration.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/test/Configuration.ui.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/test/__snapshots__/Configuration.ui.test.js.snap
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/test/mocks.js
  shared/components/CollapsiblePanel/CollapsiblePanel.js
  shared/components/CollapsiblePanel/CollapsiblePanel.scss
  shared/components/CollapsiblePanel/test/CollapsiblePanel.ui.test.js
  shared/components/CollapsiblePanel/test/__snapshots__/CollapsiblePanel.ui.test.js.snap
  shared/index.js
  shared/jestSetup.js
Labels: area/console, enhancement

#1388 Connect with Remote Application via Compass UI
  compass/package-lock.json
  compass/package.json
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.component.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.container.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.scss
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.component.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.container.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/mock.js
  compass/src/components/Application/gql.js
  shared/components/Tooltip/Tooltip.js
  shared/index.js
  shared/package-lock.json
  shared/package.json
  shared/webpack.config.js
Labels: area/console, enhancement

#1389 Document management scripts usage
  README.md
Labels: area/console

#1396 Connect with Remote Application (fix)
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.component.js
Labels: area/console, enhancement

#1400 Scenario Details View (no longer) crashes with minified react error
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/ScenarioApplications.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/ScenarioRuntimes.component.js
Labels: area/console, bug

#1410 Support Open API type in compass API details view more
  compass/src/components/Api/ApiDetails/ApiDetails.component.js
Labels: area/console, enhancement

#1414 Meta Information Details view (no longer) crashes for definitions with `/` in the label key
  compass/src/App.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitions.component.js
Labels: area/console

#1393 Expose new information from Cluster-/AddonConfigurations
  add-ons/Makefile
  add-ons/package-lock.json
  add-ons/package.json
  add-ons/setupTests.ts
  add-ons/src/components/AddonConfigurationBadge/AddonConfigurationBadge.tsx
  add-ons/src/components/AddonConfigurationBadge/test/AddonConfigurationBadge.test.tsx
  add-ons/src/components/AddonConfigurationBadge/test/__snapshots__/AddonConfigurationBadge.test.tsx.snap
  add-ons/src/components/AddonList/AddonList.scss
  add-ons/src/components/AddonList/AddonList.tsx
  add-ons/src/components/AddonList/test/AddonList.test.tsx
  add-ons/src/components/AddonList/test/__snapshots__/AddonList.test.tsx.snap
  add-ons/src/components/AddonPanel/AddonPanel.scss
  add-ons/src/components/AddonPanel/AddonPanel.tsx
  add-ons/src/components/AddonPanel/AddonTable/AddonTable.tsx
  add-ons/src/components/AddonPanel/AddonTable/test/AddonTable.test.tsx
  add-ons/src/components/AddonPanel/AddonTable/test/__snapshots__/AddonTable.test.tsx.snap
  add-ons/src/components/AddonPanel/RepositoryTableSegment/RepositoryTableSegment.tsx
  add-ons/src/components/AddonPanel/RepositoryTableSegment/test/RepositoryTableSegment.test.tsx
  add-ons/src/components/AddonPanel/RepositoryTableSegment/test/__snapshots__/RepositoryTableSegment.test.tsx.snap
  add-ons/src/components/AddonPanel/test/AddonPanel.test.tsx
  add-ons/src/components/AddonPanel/test/__snapshots__/AddonPanel.test.tsx.snap
  add-ons/src/components/Atoms/test/InlineHelp.test.tsx
  add-ons/src/components/Atoms/test/__snapshots__/InlineHelp.test.tsx.snap
  add-ons/src/components/CollapsiblePanel/CollapsiblePanel.scss
  add-ons/src/components/CollapsiblePanel/CollapsiblePanel.tsx
  add-ons/src/components/CollapsiblePanel/test/CollapsiblePanel.test.tsx
  add-ons/src/components/CollapsiblePanel/test/__snapshots__/CollapsiblePanel.test.tsx.snap
  add-ons/src/components/LabelDisplay/LabelDisplay.scss
  add-ons/src/components/LabelDisplay/LabelDisplay.tsx
  add-ons/src/components/LabelDisplay/test/LabelDisplay.test.tsx
  add-ons/src/components/LabelDisplay/test/__snapshots__/LabelDisplay.test.tsx.snap
  add-ons/src/components/Modals/DeleteConfigurationModal/DeleteConfigurationModal.component.tsx
  add-ons/src/components/Modals/DeleteUrlModal/DeleteUrlModal.component.tsx
  add-ons/src/components/Modals/DeleteUrlModal/styled.ts
  add-ons/src/components/Table/ActiveFilters.component.tsx
  add-ons/src/components/Table/ActiveFilters.container.tsx
  add-ons/src/components/Table/FilterPopover/FilterPopover.component.tsx
  add-ons/src/components/Table/FilterPopover/FilterPopover.container.tsx
  add-ons/src/components/Table/FilterPopover/FilterPopoverBody.component.tsx
  add-ons/src/components/Table/FilterPopover/styled.ts
  add-ons/src/components/Table/Search/Search.component.tsx
  add-ons/src/components/Table/Search/Search.container.tsx
  add-ons/src/components/Table/Search/styled.ts
  add-ons/src/components/Table/Table.component.tsx
  add-ons/src/components/Table/Table.container.tsx
  add-ons/src/components/Table/TableContent.component.tsx
  add-ons/src/components/Table/styled.ts
  add-ons/src/components/Toolbar/Toolbar.component.tsx
  add-ons/src/components/Toolbar/test/Toolbar.test.tsx
  add-ons/src/components/Toolbar/test/__snapshots__/Toolbar.test.tsx.snap
  add-ons/src/core/App.scss
  add-ons/src/core/App.tsx
  add-ons/src/services/Mutations.service.ts
  add-ons/src/services/Queries.service.ts
  add-ons/src/services/Subscriptions.service.ts
  add-ons/src/types.ts
  common/src/services/notifications/notifications.service.ts
  package-lock.json
  package.json
Labels: area/console, enhancement

#1418 Application & Runtimes choosers in create Scenario form unbroken
  compass/src/components/Scenarios/CreateScenario/CreateScenarioForm/CreateScenarioForm.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
  compass/src/components/Shared/MultiChoiceList/test/MultiChoiceList.test.js
  compass/src/components/Shared/MultiChoiceList/test/__snapshots__/MultiChoiceList.test.js.snap
Labels: area/console

#1412 Move create and filter actions into generic list header
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsApis/ApplicationDetailsApis.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsEventApis/ApplicationDetailsEventApis.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.component.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitions.component.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/test/__snapshots__/ScenarioApplications.test.js.snap
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/test/__snapshots__/ScenarioRuntimes.test.js.snap
  compass/src/components/Scenarios/Scenarios.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/helpers.js
  shared/components/GenericList/style.scss
  shared/components/GenericList/test/GenericList.test.js
  shared/components/GenericList/test/__snapshots__/GenericList.test.js.snap
  shared/components/PageHeader/PageHeader.js
  shared/components/PageHeader/PageHeader.scss
  shared/components/PageHeader/test/PageHeader.test.js
  shared/components/PageHeader/test/__snapshots__/PageHeader.test.js.snap
  shared/index.js
Labels: area/console, enhancement
