Repository kyma-project/console, pull requests merged in 2019-05, with the labels that each got.

#800 add 'system' labels to system namespaces
  core/src/app/content/workspace-overview/namespace-card/namespace-card.component.html
  core/src/app/shared/datamodel/k8s/generic/meta-data.ts
Labels: area/console, enhancement

#784 Use websockets for pods and applications in console core
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.ts
  core/nginx/nginx.conf
  core/package-lock.json
  core/package.json
  core/src/app/app.config.ts
  core/src/app/app.module.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/apis.component.ts
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis.component.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.ts
  core/src/app/content/namespaces/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/namespaces/operation/configmaps/configmaps.component.ts
  core/src/app/content/namespaces/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.spec.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.ts
  core/src/app/content/namespaces/operation/graphql-data-provider.ts
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.html
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/content/namespaces/operation/replica-sets/replica-sets.component.ts
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.ts
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.ts
  core/src/app/content/namespaces/operation/services/services.component.ts
  core/src/app/content/namespaces/services/namespaces.service.spec.ts
  core/src/app/content/namespaces/services/namespaces.service.ts
  core/src/app/content/settings/applications/application-details/application-binding-service.ts
  core/src/app/content/settings/applications/applications-entry-renderer/applications-entry-renderer.component.ts
  core/src/app/content/settings/applications/applications.component.ts
  core/src/app/content/settings/applications/services/applications.service.spec.ts
  core/src/app/content/settings/applications/services/applications.service.ts
  core/src/app/content/settings/idp-presets/idp-presets.component.ts
  core/src/app/content/settings/idp-presets/idp-presets.service.spec.ts
  core/src/app/content/settings/idp-presets/idp-presets.service.ts
  core/src/app/content/settings/service-brokers/service-brokers.component.ts
  core/src/app/shared/components/json-editor-modal/graphql-mutator-modal.component.ts
  core/src/app/shared/components/resource-uploader/services/resource-upload.service.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.ts
  core/src/app/shared/services/graphql-client-service.ts
  core/src/app/ws.ts
  core/src/tsconfig.app.json
Labels: area/console, enhancement

#807 Alter package-lock to remove vulnerable dependency
  components/angular/generic-list/package-lock.json
  core/package-lock.json
  lambda/package-lock.json
Labels: area/console, security/high

#824 Fix websockets in console core lists views
  core/src/app/content/namespaces/operation/graphql-data-provider.ts
Labels: area/console, bug

#827 Fetch all init data with one gql request
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/microfrontend-converter.js
Labels: area/console, enhancement

#844 Fix RegExp for Firefox
  catalog/src/commons/helpers.js
  components/react/src/components/ReactMarkdown/helpers.js
  content/src/components/DocsContent/DocsProcessor.js
  instances/src/commons/helpers.js
Labels: area/console, area/service-catalog, enhancement

#826 Stabilize Lambdas UI test
  tests/ui-tests/tests/lambda-ui-test.js
Labels: WIP, area/console, test-failing

#853 Update CODEOWNERS
  CODEOWNERS
Labels: enhancement

#857 Make sure "Overview" tab comes first in tabs in Catalog and Instances
  catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.component.js
  instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
Labels: area/console, area/documentation, area/service-catalog, enhancement

#829 Use view group caching in the console
  core/package-lock.json
  core/package.json
  core/src/app/content/namespaces/operation/deployments/deployment-entry-renderer/deployment-entry-renderer.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/microfrontend-converter.js
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/app.module.ts
  lambda/src/app/shared/components/empty/empty.component.html
  lambda/src/app/shared/components/empty/empty.component.ts
  package-lock.json
Labels: area/console, enhancement

#842 Add UI test for exposing API
  core/src/app/content/namespaces/configuration/apis/filtered-apis/filtered-apis-entry-renderer/filtered-apis-entry-renderer.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.html
  package.json
  tests/ui-tests/commands/console.js
  tests/ui-tests/setup/k8s-api/index.js
  tests/ui-tests/setup/k8s-api/k8s-api-deployment.js
  tests/ui-tests/setup/k8s-api/k8s-api-namespace.js
  tests/ui-tests/setup/k8s-api/k8s-api-service.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/utils/address.js
  tests/ui-tests/utils/retry.js
Labels: quality/testability

#852 Fix bullet points in note/catution/tip
  components/react/package-lock.json
  components/react/package.json
  components/react/src/components/NotePanel/styled.js
  components/react/src/components/ReactMarkdown/components/Blockquote.js
Labels: area/console, area/documentation, area/service-catalog, enhancement

#862 Consume external link and requiredPermissions
  core/src/luigi-config/luigi-config.js
Labels: WIP

#864 Lambda logs are filtered by container name
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, bug

#872 Fix log ui in Firefox
  logging/src/app/search-form/search-form.component.html
  logging/src/app/search-form/search-form.component.ts
Labels: area/console, bug, quality/observability

#880 Remove adding testing bundle
  tests/README.md
  tests/ui-tests/setup/helm-broker/config.js
  tests/ui-tests/setup/helm-broker/configurer.js
  tests/ui-tests/setup/namespace-manager.js
  tests/ui-tests/setup/test-bundle-installer.js
  tests/ui-tests/tests/catalog-ui-test.js
Labels: area/service-catalog, enhancement

#867 Lambda "Test" tab
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/app.module.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.html
  lambda/src/app/lambdas/lambda-details/lambda-details.component.scss
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/lambdas/list/lambdas.component.ts
  lambda/src/app/shared/components/notification/notification.component.html
  lambda/src/app/shared/components/notification/notification.component.scss
  lambda/src/app/shared/components/notification/notification.component.ts
  lambda/src/tsconfig.app.json
  lambda/tsconfig.json
Labels: area/console, enhancement

#715 Adjust config files to work with 'console-dev.{cluster}...' domain
  config.js
  core/src/app/app.config.ts
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/microfrontend-converter.js
Labels: area/console
