Repository kyma-project/console, pull requests merged in 2020-01, with the labels that each got.

#1500 Experimental view toggle
  core/src/app/content/settings/organisation/organisation.component.html
  core/src/app/content/settings/organisation/organisation.component.ts
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/microfrontend-converter.js
  core/src/luigi-config/navigation-helpers.js
Labels: area/console, enhancement

#1506 Misplaced checkboxes in create namespace modal
  core-ui/src/components/CreateNamespaceForm/CreateNamespaceForm.js
Labels: area/console, bug

#1503 Allow deleting Access Strategy
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/mocks.js
  core-ui/src/components/ApiRules/ApiRules.js
  core-ui/src/components/ApiRules/CreateApiRule/test/CreateApiRule.test.js
  core-ui/src/components/ApiRules/EditApiRule/test/EditApiRule.test.js
  core-ui/src/components/ApiRules/test/ApiRules.test.js
Labels: area/console

#1509 Host value split in half in API Rule Header
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
  shared/components/CopiableText/CopiableText.js
  shared/components/CopiableText/test/CopiableText.test.js
  shared/components/PageHeader/PageHeader.js
Labels: area/console, enhancement

#1512 Fix yes/no prompt in setClusterConfig.sh
  scripts/setClusterConfig.sh
Labels: area/console

#1511 Remove auto polling from catalog-ui and new lambda-ui
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsWrapper.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/shared/constants.js
  service-catalog-ui/catalog/src/components/ServiceClassList/ServiceClassList.js
  service-catalog-ui/catalog/src/variables.js
Labels: area/console, bug, priority/critical

#1397 Create and Delete knative triggers from lambda UI
  lambda/package-lock.json
  lambda/package.json
  lambda/src/app/app.config.ts
  lambda/src/app/app.module.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.spec.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/lambdas/list/lambdas.component.spec.ts
  lambda/src/app/lambdas/list/lambdas.component.ts
  lambda/src/app/triggers/triggers.service.spec.ts
  lambda/src/app/triggers/triggers.service.ts
Labels: area/console, area/serverless, enhancement

#1490 UX DoD Requirements
  CONTRIBUTING.md
Labels: area/console

#1517 Change auth from allow to noop
  core-ui/src/components/ApiRules/AccessStrategy/AccessStrategy.js
  core-ui/src/components/ApiRules/AccessStrategy/test/AccessStrategy.test.js
  core-ui/src/components/ApiRules/ApiRuleDetails/test/ApiRuleDetails.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/mocks.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.js
  core-ui/src/components/ApiRules/CreateApiRule/test/mocks.js
  core-ui/src/components/ApiRules/EditApiRule/test/mocks.js
  core-ui/src/testing/queriesMocks.js
Labels: area/console, enhancement

#1497 Update docs-component styles
  compass/src/shared/components/DocumentationComponent/DocumentationComponent.js
  components/generic-documentation/src/render-engines/open-api/styles/index.ts
  service-catalog-ui/catalog/src/apollo.js
Labels: area/core-and-supporting, bug

#1514 Remove old code from tests
  tests/ui-tests/tests/console-basic-test.js
Labels: area/console, test-failing

#1521 Fix timeouting tests
  core-ui/src/components/ApiRules/CreateApiRule/test/CreateApiRule.test.js
  core-ui/src/components/ApiRules/EditApiRule/test/EditApiRule.test.js
Labels: area/console, enhancement

#1522 New application list
  .clusterConfig.default
  core-ui/src/apollo.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationList/test/ApplicationList.test.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/index.js
  core/src/luigi-config/luigi-config.js
  shared/components/GenericList/GenericList.js
Labels: area/console

#1525 Display list of applications from Compass and Kyma
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/apollo.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.js
  core-ui/src/components/ApiRules/EditApiRule/EditApiRule.js
  core-ui/src/components/ApiRules/useDeleteApiRule.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationList/test/ApplicationList.test.js
  core-ui/src/components/Applications/ApplicationList/test/mocks.js
  core-ui/src/components/Applications/ApplicationList/wsHandler.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/contexts/notifications/index.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
  core-ui/src/index.js
  core-ui/src/setupTests.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/test/ServiceInstanceDetails.test.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/test/ServiceInstancesList.test.js
  service-catalog-ui/instances/src/store/index.js
  shared/components/GenericList/actionHandlers/simpleDelete.js
  shared/contexts/NotificationContext.js
  shared/index.js
  shared/utils/apollo.js
Labels: area/console, enhancement

#1528 Connect Application modal
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationList/test/mocks.js
  core-ui/src/components/Applications/ConnectApplicationModal/ConnectApplicationModal.js
  core-ui/src/components/Applications/ConnectApplicationModal/ConnectApplicationModal.scss
  core-ui/src/components/Applications/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  core-ui/src/components/Applications/ConnectApplicationModal/test/mock.js
  core-ui/src/gql/mutations.js
  shared/components/Modal/Modal.js
  shared/components/Modal/Modal.scss
  shared/index.js
Labels: area/console

#1529 Unify backend and frontend naming in docs
  README.md
  components/angular/generic-list/README.md
  service-catalog-ui/README.md
Labels: area/documentation

#1530 Enable stale bot for epics
  .github/stale.yml
Labels: area/community

#1513 Create Application from IS owned Templates
  compass/src/App.scss
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/CreateApplicationFromTemplateModal/CreateApplicationFromTemplateModal.js
  compass/src/components/Applications/CreateApplicationFromTemplateModal/CreateApplicationFromTemplateModal.scss
  compass/src/components/Applications/CreateApplicationFromTemplateModal/test/CreateApplicationFromTemplateModal.test.js
  compass/src/components/Applications/CreateApplicationFromTemplateModal/test/mocks.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Applications/CreateApplicationModal/styles.scss
  compass/src/components/Applications/gql.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
  compass/src/components/Shared/MultiChoiceList/style.scss
  shared/components/GenericList/SearchInput.js
Labels: area/console, enhancement

#1531 Register application modal
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationList/test/ApplicationList.test.js
  core-ui/src/components/Applications/RegisterApplication/RegisterApplicationForm.js
  core-ui/src/components/Applications/RegisterApplication/test/RegisterApplicationForm.test.js
  core-ui/src/components/Applications/RegisterApplication/test/gqlMocks.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core/src/luigi-config/luigi-config.js
Labels: area/console, area/management-plane

#1538 Compass UI: Connect Application window should display token's raw encoded field only
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.component.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/mock.js
  compass/src/components/Application/gql.js
Labels: area/management-plane, enhancement

#1532 Create application details view
  compass/public/compass-needle.png
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/ScenarioDetails/shared/AssignEntityToScenarioModal/AssignEntityToScenarioModal.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  core-ui/package-lock.json
  core-ui/src/components/App/App.js
  core-ui/src/components/Applications/ApplicationDetails/ApplicationDetails.js
  core-ui/src/components/Applications/ApplicationDetails/test/ApplicationDetails.test.js
  core-ui/src/components/Applications/ApplicationDetails/test/mocks.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/BindNamespaceModal/BindNamespaceModal.js
  core-ui/src/components/Applications/BindNamespaceModal/test/BindNamespaceModal.test.js
  core-ui/src/components/Applications/BindNamespaceModal/test/mocks.js
  core-ui/src/components/Applications/BoundNamespacesList/BoundNamespacesList.js
  core-ui/src/components/Applications/BoundNamespacesList/test/BoundNamespacesList.test.js
  core-ui/src/components/Applications/BoundNamespacesList/test/mocks.js
  core-ui/src/components/Applications/RegisterApplication/RegisterApplicationForm.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/index.scss
  core-ui/src/shared/constants.js
  shared/components/DetailsError/DetailsError.js
  shared/components/DetailsError/test/DetailsError.test.js
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/helpers.js
  shared/components/Labels/Labels.js
  shared/components/Labels/test/Labels.test.js
  shared/components/Labels/test/__snapshots__/Labels.test.js.snap
  shared/constants/constants.js
  shared/index.js
Labels: area/console, enhancement

#1533 Application statuses
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.scss
  core-ui/src/components/Applications/ApplicationList/test/ApplicationList.test.js
Labels: area/console

#1541 Add connect button to app details
  core-ui/src/components/Applications/ApplicationDetails/ApplicationDetails.js
  core-ui/src/components/Applications/ConnectApplicationModal/ConnectApplicationModal.js
  core-ui/src/components/Applications/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  core-ui/src/components/Applications/ConnectApplicationModal/test/mock.js
  core-ui/src/gql/mutations.js
Labels: area/console, enhancement

#1540 Support for legacy connector URL in Connect Application modal
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/ConnectApplicationModal.component.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/mock.js
  compass/src/components/Application/gql.js
Labels: area/management-plane, enhancement
