Repository kyma-project/console, pull requests merged in 2020-03, with the labels that each got.

#1586 Fix links in service instances view
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesTable/ServiceInstancesTable.component.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/test/ServiceInstancesList.test.js
Labels: area/console

#1588 Catalog instances in plan context
  components/generic-documentation/src/index.tsx
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/queries.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/test/ServiceClassDetails.test.js
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/ServiceClassPlansList.js
Labels: area/console, enhancement

#1592 Create API Package modal
  compass/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  compass/src/components/ApiPackages/CreateApiPackageForm/test/CreateApiPackageForm.test.js
  compass/src/components/ApiPackages/CreateApiPackageForm/test/mocks.js
  compass/src/components/ApiPackages/gql.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.component.js
Labels: area/console, area/management-plane

#1598 Fix breadcrumbs on class details view, fix search input on list
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  service-catalog-ui/catalog/src/components/ServiceClassList/ServiceClassToolbar/styled.js
Labels: area/console, bug

#1593 Documentation per plan
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassTabs/ServiceClassTabs.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/queries.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/test/ServiceClassDetails.test.js
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/ServiceClassPlansList.js
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/ServiceClassPlansList.scss
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/queries.js
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/test/ServiceClassPlansList.test.js
  service-catalog-ui/catalog/src/index.scss
  service-catalog-ui/catalog/src/shared/sorting.js
  service-catalog-ui/catalog/src/testing/serviceClassesMocks.js
  service-catalog-ui/catalog/src/variables.js
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/GenericList.scss
  shared/components/GenericList/test/GenericList.test.js
Labels: area/console, enhancement

#1594 Refactor luigi config
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/NamespaceDetailsCard.test.js
  core/package-lock.json
  core/src/app/content/namespaces/namespace-create/namespace-create.component.ts
  core/src/app/content/namespaces/namespace-details/namespace-details.component.ts
  core/src/app/content/settings/organisation/organisation.component.ts
  core/src/app/content/workspace-overview/workspace-overview/workspace-overview.component.ts
  core/src/index.html
  core/src/luigi-config/communication.js
  core/src/luigi-config/config.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/luigi-event-handlers.js
  core/src/luigi-config/navigation/local-development-node-converter.js
  core/src/luigi-config/navigation/microfrontend-converter.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/rbac-rules-matcher.js
  core/src/luigi-config/navigation/rbac-rules-matcher.test.js
  core/src/luigi-config/navigation/static-navigation-model.js
  package-lock.json
  package.json
Labels: area/console, enhancement

#1600 Multiple docs of one type
  components/generic-documentation/src/loader/loader.ts
  components/generic-documentation/src/renderers/Group.renderer.tsx
  components/generic-documentation/src/renderers/SingleAPIcontent.tsx
Labels: area/console, enhancement

#1601 Display plan docs on instances
  components/generic-documentation/src/renderers/Group.renderer.tsx
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
  service-catalog-ui/instances/src/queries/fragments.js
  service-catalog-ui/instances/src/testing/instanceMocks.js
Labels: area/console, enhancement

#1597 Whitesource v2
  components/angular/generic-list/package-lock.json
  components/angular/generic-list/package.json
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/react/package-lock.json
  components/react/package.json
  core/package-lock.json
  core/package.json
  lambda/package-lock.json
  lambda/package.json
  logging/package-lock.json
  package-lock.json
  package.json
  service-catalog-ui/package-lock.json
  service-catalog-ui/package.json
  shared/package-lock.json
  tests/package-lock.json
Labels: area/security

#1605 Display APIs on package list
  compass/src/components/Application/ApplicationDetails/ApplicationApiPackages/ApplicationApiPackages.js
  compass/src/components/Application/ApplicationDetails/ApplicationApiPackages/ApplicationApiPackages.test.js
  compass/src/components/Application/gql.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/Applications.test.js
  compass/src/components/Applications/gql.js
Labels: area/console, enhancement

#1603 Do not store profile information in web storage
  .clusterConfig.default
  core/package-lock.json
  core/package.json
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/microfrontend-converter.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/permissions.js
Labels: area/console, security/medium

#1606 Fix vulnerabilities in generic-documentation component
  compass/src/setupTests.js
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/generic-documentation/src/renderers/styled.ts
  content/src/constants.ts
  service-catalog-ui/catalog/src/testing/queriesMocks.js
Labels: security/medium

#1609 Improve security in log-ui nginx conf
  logging/nginx.conf
Labels: area/console, area/logging, security/medium

#1607 Don't refresh view on every context change
  shared/contexts/ApplicationContext.js
Labels: area/console, area/management-plane, enhancement

#1611 Move the auth data to the package. instead of a specific api
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/ApiDetailsHeader.js
  compass/src/components/Api/ApiHelpers.js
  compass/src/components/Api/CreateApiForm/CreateApiForm.js
  compass/src/components/Api/EditApi/EditApi.component.js
  compass/src/components/Api/EditApi/gql.js
  compass/src/components/Api/Forms/ApiForm.js
  compass/src/components/Api/Forms/EventApiForm.js
  compass/src/components/Api/gql.js
  compass/src/components/ApiPackages/ApiPackageDetails/ApiList/ApiList.js
  compass/src/components/ApiPackages/ApiPackageDetails/ApiPackageDetails.js
  compass/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/EditApiPackageForm.js
  compass/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/test/EditApiPackageForm.test.js
  compass/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/test/mocks.js
  compass/src/components/ApiPackages/ApiPackageDetails/EventList/EventList.js
  compass/src/components/ApiPackages/ApiPackageDetails/Header/ApiPackageDetailsHeader.js
  compass/src/components/ApiPackages/ApiPackagesHelpers.js
  compass/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  compass/src/components/ApiPackages/CreateApiPackageForm/test/CreateApiPackageForm.test.js
  compass/src/components/ApiPackages/CreateApiPackageForm/test/mocks.js
  compass/src/components/ApiPackages/gql.js
  compass/src/components/Application/ApplicationDetails/ApplicationApiPackages/ApplicationApiPackages.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.container.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.js
  compass/src/shared/components/ModalWithForm/test/ModalWithForm.test.js
  compass/src/store/index.js
  shared/components/CredentialForms/BasicCredentialsForm.js
  shared/components/CredentialForms/CredentialsForm.js
  shared/components/CredentialForms/OAuthCredentialsForm.js
  shared/components/CredentialForms/index.js
  shared/components/TextFormItem/TextFormItem.js
  shared/index.js
Labels: area/console, enhancement

#1612 API Packages in core-ui
  core-ui/src/components/ApiPackages/ApiPackageDetails/ApiList/ApiList.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/ApiList/ApiList.scss
  core-ui/src/components/ApiPackages/ApiPackageDetails/ApiPackageDetails.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/AuthDetailsModal/AuthDetailsModal.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/AuthList/AuthList.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/EditApiPackageForm.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/test/EditApiPackageForm.test.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/test/mocks.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EventList/EventList.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EventList/EventList.scss
  core-ui/src/components/ApiPackages/ApiPackageDetails/Header/ApiPackageDetailsHeader.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/Header/ApiPackageDetailsHeader.scss
  core-ui/src/components/ApiPackages/ApiPackageDetails/RequestInputSchemaModal/RequestInputSchemaModal.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/test/CreateApiPackageForm.test.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/test/mocks.js
  core-ui/src/components/ApiPackages/gql.js
  core-ui/src/components/Apis/ApiDetails/ApiDetails.js
  core-ui/src/components/Apis/ApplicationApiPackages/ApplicationApiPackages.js
  core-ui/src/components/Apis/ApplicationApiPackages/ApplicationApiPackages.test.js
  core-ui/src/components/Apis/CreateApiForm/CreateApiForm.js
  core-ui/src/components/Apis/CreateEventForm/CreateEventForm.js
  core-ui/src/components/Apis/EditApi/EditApi.js
  core-ui/src/components/Apis/EditApiHeader/EditApiHeader.js
  core-ui/src/components/Apis/EditEventApi/EditEventApi.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Applications/ApplicationDetails/ApplicationDetails.js
  core-ui/src/components/Applications/ApplicationDetails/test/mocks.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationList/test/ApplicationList.test.js
  core-ui/src/components/Applications/ApplicationList/test/mocks.js
  core-ui/src/components/Applications/CreateApplicationFromTemplateModal/test/mocks.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  shared/components/JSONEditor/JSONEditor.js
  shared/index.js
  shared/package-lock.json
  shared/package.json
Labels: area/console, enhancement

#1616 Fix subscriptions in app details
  core-ui/src/components/Applications/ApplicationDetails/ApplicationDetails.js
Labels: area/console, bug

#1614 Update kind-of package
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
Labels: area/console, area/security

#1615 Don't fetch twice v2
  compass/src/components/Scenarios/ScenarioDetails/shared/AssignEntityToScenarioModal/AssignEntityToScenarioModal.component.js
Labels: area/console, area/management-plane, enhancement

#1623 Remove auth for a specific api in apps view
  core-ui/src/components/Apis/ApiHelpers.js
  core-ui/src/components/Apis/CreateApiForm/CreateApiForm.js
  core-ui/src/components/Apis/EditApi/EditApi.js
  core-ui/src/components/Apis/Forms/CredentialForms/CredentialsForm.js
  core-ui/src/components/Apis/Forms/CredentialForms/OAuthCredentialsForm.js
  package-lock.json
Labels: area/console, enhancement

#1624 Default auth in core-ui API Packages
  core-ui/src/apollo.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/ApiPackageDetails.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/EditApiPackageForm.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/test/EditApiPackageForm.test.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/test/mocks.js
  core-ui/src/components/ApiPackages/ApiPackageHelpers.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/test/CreateApiPackageForm.test.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/test/mocks.js
  core-ui/src/gql/queries.js
Labels: area/console, area/management-plane

#1630 Fix 'docs per plan of null' error
  components/react/package-lock.json
  package-lock.json
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassList/Cards/Card.component.js
  service-catalog-ui/catalog/src/components/ServiceClassList/Cards/Cards.component.js
  service-catalog-ui/catalog/src/components/ServiceClassList/Cards/test/Card.test.js
  service-catalog-ui/catalog/src/testing/serviceClassesMocks.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesTable/ServiceInstancesTable.component.js
  service-catalog-ui/instances/src/variables.js
Labels: area/console, bug

#1631 Don't fetch both API & Event on details view
  compass/src/App.component.js
  compass/src/components/Api/ApiDetails/ApiDetails.component.js
  compass/src/components/Api/ApiDetails/ApiDetails.container.js
  compass/src/components/Api/ApiDetails/ApiDetails.js
  compass/src/components/Api/ApiDetails/ApiDetails.scss
Labels: area/console

#1629 Remove 'npm run bootstrap' reminder when not needed
  scripts/setClusterConfig.sh
Labels: area/console

#1634 Fix namespaces filter dropdown width
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/NamespaceFilters.js
Labels: area/console, bug

#1635 Adjust Application update form
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/UpdateApplicationForm.component.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/UpdateApplicationForm.container.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/UpdateApplicationForm.test.js
  compass/src/components/Application/ApplicationDetails/UpdateApplicationForm/test/mock.js
  compass/src/components/Application/gql.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
Labels: area/console, area/management-plane, bug

#1637 Bump vulnerable handlebars version
  components/generic-documentation/package-lock.json
  components/react/package.json
  package-lock.json
  package.json
Labels: area/console, dependencies

#1642 Redirect to the only plan
  service-catalog-ui/catalog/src/components/ServiceClassDetails/CreateInstanceModal/test/CreateInstanceModal.test.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/test/ServiceClassDetails.test.js
  service-catalog-ui/catalog/src/components/ServiceClassList/Cards/Cards.component.js
  service-catalog-ui/catalog/src/components/ServiceClassList/Cards/test/Cards.test.js
  service-catalog-ui/catalog/src/components/ServiceClassList/queries.js
  service-catalog-ui/catalog/src/components/ServiceClassList/test/ServiceClassList.test.js
  service-catalog-ui/catalog/src/components/ServiceClassList/test/__snapshots__/ServiceClassList.test.js.snap
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/test/ServiceClassPlansList.test.js
  service-catalog-ui/catalog/src/testing/queriesMocks.js
  service-catalog-ui/catalog/src/testing/serviceClassesMocks.js
Labels: area/console, enhancement

#1648 Fix tooltip message for not-installed status
  core-ui/src/components/Applications/ApplicationStatus/ApplicationStatus.js
Labels: area/console, bug

#1649 Show description on packages list
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/ServiceClassPlansList.js
  service-catalog-ui/catalog/src/components/ServiceClassPlansList/queries.js
  service-catalog-ui/catalog/src/index.scss
Labels: area/console, enhancement

#1652 Fix searchbar in instances
  service-catalog-ui/catalog/src/components/ServiceClassList/ServiceClassToolbar/styled.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesToolbar/styled.js
Labels: bug

#1641 Introduce tenant search modal
  compass/package-lock.json
  compass/package.json
  compass/src/App.component.js
  compass/src/components/TenantSearch/TenantSearch.js
  compass/src/components/TenantSearch/TenantSearch.scss
  compass/src/components/TenantSearch/fetchTenants.js
  compass/src/components/TenantSearch/test/TenantSearch.test.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  compass/src/config/luigi-config/navigation.js
Labels: area/console, area/management-plane, enhancement

#1657 Ignore tenant header when calling compass from runtime
  compass/src/store/index.js
  core-ui/src/apollo.js
Labels: area/console, area/management-plane, bug

#1656 Move copy-webpack-plugin to devDepandencies
  components/react/package-lock.json
  components/react/package.json
  lambda/package-lock.json
  lambda/package.json
  package-lock.json
Labels: area/console, area/security, security/high, security/medium

#1655 Improve api package schema editor
  compass/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/EditApiPackageForm.js
  compass/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/EditApiPackageForm.js
  core-ui/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
Labels: area/console, area/management-plane, enhancement

#1660 Improve displaying of the bind credentials
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateCredentialsModal/CreateCredentialsModal.component.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ParametersDataModal/styled.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/styled.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceInfo/styled.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesTable/styled.js
Labels: area/console, bug

#1665 Fix monaco-editor in new lambda view - change CSP
  core-ui/nginx.conf
Labels: area/console, bug
