Repository kyma-project/console, pull requests merged in 2020-11, with the labels that each got.

#2045 Fix Lambda inline editor not showing up
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
Labels: area/console, bug

#2043 Add drawer with secret edit on secrets list and detail
  core-ui/src/components/App/App.js
  core-ui/src/components/Secrets/Details/Json/SecretJson.js
  core-ui/src/components/Secrets/Details/Json/SecretJson.scss
  core-ui/src/components/Secrets/Details/Json/test/SecretJson.test.js
  core-ui/src/components/Secrets/Details/SecretDetails.js
  core-ui/src/components/Secrets/Details/SecretHeader.js
  core-ui/src/components/Secrets/Details/test/SecretDetails.test.js
  core-ui/src/components/Secrets/Details/test/mocks.js
  core-ui/src/components/Secrets/List/SecretList.js
  core-ui/src/components/Secrets/List/test/SecretList.test.js
  core-ui/src/components/Secrets/Secrets.js
  core-ui/src/gql/queries.js
Labels: area/console, enhancement

#2047 Add flags for cypress:test:cluster
  tests/package.json
Labels: area/console

#2049 Fix doughnut charts
  core-ui/src/shared/components/CircleProgress/CircleProgress.js
  core-ui/src/shared/components/CircleProgress/CircleProgress.scss
Labels: area/console, bug

#2050 Fix token expire logout
  core/src/assets/static-views.js
  core/src/nopermissions.html
Labels: area/console, bug

#2052 Fix the TW alias in the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, bug

#2053 Fix fragmentMatcher
  service-catalog-ui/src/apollo.js
Labels: area/console, bug

#2054 "allow" as default strategy
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.js
  core-ui/src/components/ApiRules/CreateApiRule/test/mocks.js
Labels: area/console, bug

#2057 Fix catalog search, optimize filter
  service-catalog-ui/src/components/ServiceClassList/ServiceClassList.js
  service-catalog-ui/src/components/ServiceClassList/ServiceClassToolbar/ServiceClassToolbar.component.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceList.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceToolbar/SearchDropdown.component.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceToolbar/ServiceInstanceToolbar.component.js
  service-catalog-ui/src/helpers/search.js
  service-catalog-ui/src/shared/SearchDropdown.component.js
Labels: area/console, bug

#2058 Fix Firefox instance binding in Functions
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ConfigurationTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
Labels: area/console, bug
