Repository kyma-project/console, pull requests merged in 2020-07, with the labels that each got.

#1874 Fix double underlines
  compass/src/App.scss
  components/react/package-lock.json
  core-ui/src/index.scss
  package-lock.json
  service-catalog-ui/src/index.scss
Labels: area/console, bug

#1877 Fix instances crashing
  service-catalog-ui/src/apollo.js
Labels: area/console, bug

#1878 Fix styling in namespace details view, fix error message in resource editor
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.scss
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.html
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.scss
  core/src/app/shared/components/json-editor-modal/json-editor-modal.component.ts
Labels: area/console, bug

#1879 Fix bug with mishaped object in beautifySchema
  core-ui/src/components/Lambdas/helpers/eventTriggers/beautifyEventSchema.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/test/beautifyEventSchema.test.js
Labels: area/serverless, bug

#1881 Change auths texts
  compass/src/components/ApiPackages/ApiPackageDetails/AuthList/AuthList.js
  compass/src/components/ApiPackages/ApiPackageDetails/EditApiPackageForm/EditApiPackageForm.js
  compass/src/components/ApiPackages/ApiPackagesHelpers.js
  compass/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  compass/src/components/ApiPackages/test/ApiPackagesHelper.test.js
  shared/components/CredentialForms/BasicCredentialsForm.js
  shared/components/CredentialForms/CredentialsForm.js
  shared/components/CredentialForms/OAuthCredentialsForm.js
Labels: area/console, area/management-plane

#1882 Fix multiple calls on search input change in core
  components/angular/generic-list/src/app/modules/list/generic-list/generic-list.component.ts
  core/src/app/content/namespaces/operation/graphql-data-provider.ts
Labels: area/console, bug

#1883 Remove lolo suffix from labels in catalog
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
Labels: area/console, bug

#1884 Fix logs view not hiding
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.test.js
  core-ui/src/components/Lambdas/helpers/lambdas/index.js
  core-ui/src/components/Lambdas/helpers/lambdas/logsViewHelpers.js
  core-ui/src/components/Lambdas/helpers/misc/test/useLogsView.test.js
  core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
Labels: area/console, bug

#1887 Bump lodash
  compass/package-lock.json
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/test/__snapshots__/ScenarioApplications.test.js.snap
  components/angular/generic-list/package-lock.json
  components/react/package-lock.json
  core-ui/package-lock.json
  core/package-lock.json
  core/package.json
  core/src/tsconfig.app.json
  core/src/tsconfig.spec.json
  logging/package-lock.json
  package-lock.json
  package.json
  shared/package-lock.json
  tests/package-lock.json
Labels: area/console

#1886 Show successful notifications as message toast
  shared/components/Notification/Notification.js
  shared/components/Notification/Notification.scss
Labels: area/console, enhancement

#1890 Unify UI texts
  core-ui/src/components/Lambdas/constants.js
  package-lock.json
Labels: area/documentation

#1889 Adjustment after triggers refactor
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useCreateManyEventTriggers.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useDeleteEventTrigger.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateManyEventTriggers.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useDeleteEventTrigger.js
  core-ui/src/components/Lambdas/gql/mutations.js
  core-ui/src/components/Lambdas/gql/queries.js
  core-ui/src/components/Lambdas/gql/subscriptions.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/serializeEvents.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/test/serializeEvents.test.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
Labels: area/console

#1894 Compass kubeconfig
  compass/package-lock.json
  compass/package.json
  compass/src/components/Runtimes/InfiniteList.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Runtimes/Runtimes.js
  compass/src/components/Runtimes/test/Runtime.test.js
  compass/src/config/luigi-config/settings.js
  compass/src/shared/hooks/useGetKubeconfig.js
Labels: area/management-plane

#1896 Realtime statuses on namespace view
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/namespaceWorkloadsHelpers.js
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/test/NamespaceWorkloads.test.js
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/test/mocks.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
  core-ui/src/shared/components/CircleProgress/CircleProgress.js
  core-ui/src/shared/components/CircleProgress/test/CircleProgress.test.js
Labels: area/console

#1898 Fix API details unit tests
  core-ui/src/components/ApiRules/ApiRuleDetails/test/ApiRuleDetails.test.js
  core-ui/src/components/ApiRules/gql/mocks/useDeleteApiRule.js
  core-ui/src/components/ApiRules/gql/test/useDeleteApiRule.test.js
  core-ui/src/components/Lambdas/helpers/testing/MutationComponent.js
Labels: area/console, bug

#1899 Fix logs view not hiding
  core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
Labels: area/console, bug

#1901 Fix small text issues, wrap notification text
  compass/src/components/Api/ApiHelpers.js
  compass/src/components/Api/CreateApiForm/CreateApiForm.js
  compass/src/components/Api/CreateEventApiForm/CreateEventApiForm.js
  compass/src/components/MetadataDefinitions/CreateMDmodal/CreateMDmodal.component.js
  compass/src/components/Shared/FileInput/FileInput.js
  compass/src/components/Shared/FileInput/FileInput.scss
  service-catalog-ui/src/components/ServiceInstanceList/test/ServiceInstanceList.test.js
  shared/components/FileInput/FileInput.scss
  shared/components/Notification/Notification.scss
  shared/components/PageHeader/PageHeader.js
  shared/components/PageHeader/PageHeader.scss
  shared/components/StatusBadge/StatusBadge.scss
  shared/components/Tooltip/Tooltip.js
  shared/components/Tooltip/Tooltip.scss
Labels: area/console

#1906 Capitalize maps for consistency with the rest
  core/src/luigi-config/navigation/static-navigation-model.js
Labels: area/console
