Repository kyma-project/console, pull requests merged in 2020-06, with the labels that each got.

#1808 Make more restricted function's forms
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/test/CodeAndDependencies.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/SingleVariableInput.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/validation.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/validation.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/test/ResourceManagement.test.js
  core-ui/src/components/Lambdas/LambdasList/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/CreateLambdaModal.js
  core-ui/src/components/Lambdas/LambdasList/LambdasListWrapper.js
  core-ui/src/components/Lambdas/LambdasList/helpers.js
  core-ui/src/components/Lambdas/LambdasList/test/CreateLambdaModal.test.js
  core-ui/src/components/Lambdas/components/LambdaNameInput/LambdaNameInput.js
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useLambdaQuery.test.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
  core-ui/src/components/Lambdas/helpers/resources/cpuHelpers.js
  core-ui/src/components/Lambdas/helpers/resources/index.js
  core-ui/src/components/Lambdas/helpers/resources/memoryHelpers.js
  core-ui/src/components/Lambdas/helpers/resources/parseCpu.js
  core-ui/src/components/Lambdas/helpers/resources/test/constants.test.js
  core-ui/src/components/Lambdas/helpers/resources/test/cpuHelpers.test.js
  core-ui/src/components/Lambdas/helpers/resources/test/memoryHelpers.test.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
Labels: area/console, area/serverless, enhancement

#1819 Fix log in mechanism in UI tests but better
  tests/helpers.js
Labels: area/console, test-failing

#1823 Fix failing unit tests for functions view
  core-ui/src/components/Lambdas/LambdasList/test/CreateLambdaModal.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useLambdaQuery.test.js
Labels: test-failing

#1822 Change apiVersion and kind for trigger's subscriber in functions view
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useCreateManyEventTriggers.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateManyEventTriggers.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/createSubscriberRef.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/test/createSubscriberRef.test.js
  core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
Labels: area/console, area/serverless, enhancement

#1829 Update serverless to forbid scale-to-zero
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/test/ResourceManagement.test.js
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
Labels: area/documentation, area/serverless, enhancement

#1825 Fix validation error for logQL regex in log ui advanced search
  logging/src/components/Shared/QueryInput/QueryInput.js
Labels: area/console, area/logging, bug

#1830 Fix regexp to match k8s naming conversion for create application
  core-ui/src/components/Applications/RegisterApplication/RegisterApplicationForm.js
Labels: area/console, bug

#1836 Add proper handling for k8s label schema
  core/src/app/shared/components/labels-input/labels-input.component.spec.ts
  core/src/app/shared/components/labels-input/labels-input.component.ts
Labels: area/console, bug

#1839 Update caniuse-lite and browserslist package
  components/generic-documentation/package-lock.json
  components/react/package-lock.json
  core/package-lock.json
  core/package.json
  package-lock.json
  shared/package-lock.json
  shared/package.json
Labels: area/console

#1850 Update serverless domain to use config from configmap
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/test/ResourceManagement.test.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/components/Lambdas/LambdasList/LambdasListWrapper.js
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/queries/index.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useConfigMapQuery.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/testMocks/index.js
  core-ui/src/components/Lambdas/gql/hooks/queries/testMocks/useConfigMapQuery.js
  core-ui/src/components/Lambdas/gql/hooks/queries/testMocks/useEventActivationsQuery.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useConfigMapQuery.js
  core-ui/src/components/Lambdas/gql/queries.js
  core-ui/src/components/Lambdas/helpers/misc/index.js
  core-ui/src/components/Lambdas/helpers/misc/useConfigData.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
Labels: area/console, area/serverless, enhancement

#1857 Fix namespaces title
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.test.js
Labels: area/console, bug

#1856 Enable tests for Service Catalog
  service-catalog-ui/Dockerfile
Labels: area/console, enhancement

#1855 Fix legacy applications
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.ts
Labels: area/console, bug

#1860 Unify infinite list
  compass/src/components/Runtimes/InfiniteList.js
Labels: area/console, area/management-plane, enhancement

#1861 Update alpine to fix protecode vulns
  add-ons/Dockerfile
  compass/Dockerfile
  content/Dockerfile
  core-ui/Dockerfile
  core/Dockerfile
  logging/Dockerfile
  service-catalog-ui/Dockerfile
Labels: area/console

#1864 Rewrite service details to React
  core-ui/src/components/App/App.js
  core-ui/src/components/Services/ServiceDetails/ServiceApiRules/ApiRuleStatus.js
  core-ui/src/components/Services/ServiceDetails/ServiceApiRules/ServiceApiRules.js
  core-ui/src/components/Services/ServiceDetails/ServiceApiRules/test/ApiRuleStatus.test.js
  core-ui/src/components/Services/ServiceDetails/ServiceApiRules/test/ServiceApiRules.test.js
  core-ui/src/components/Services/ServiceDetails/ServiceApiRules/test/mocks.js
  core-ui/src/components/Services/ServiceDetails/ServiceDetails.js
  core-ui/src/components/Services/ServiceDetails/ServiceDetailsHeader/ServiceDetailsHeader.js
  core-ui/src/components/Services/ServiceDetails/ServiceDetailsHeader/test/ServiceDetailsHeader.test.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/shared/components/ResourceSpecModal/ResourceSpecModal.js
  core-ui/src/shared/components/ResourceSpecModal/test/ResourceSpecModal.test.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/api-definition-entry-renderer/api-definition-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/api-definition-header-renderer/api-definition-header-renderer.component.html
  core/src/app/content/namespaces/configuration/apis/api-definition-header-renderer/api-definition-header-renderer.component.ts
  core/src/app/content/namespaces/configuration/apis/apis.component.html
  core/src/app/content/namespaces/configuration/apis/apis.component.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.html
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.scss
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.spec.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.component.ts
  core/src/app/content/namespaces/operation/services/service-details/expose-api/expose-api.service.ts
  core/src/app/content/namespaces/operation/services/service-details/service-api-rules/gql.ts
  core/src/app/content/namespaces/operation/services/service-details/service-api-rules/service-api-rules.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-api-rules/service-api-rules.component.ts
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.html
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.scss
  core/src/app/content/namespaces/operation/services/service-details/service-details.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/components/JSONEditor/JSONEditor.js
  shared/components/Labels/Labels.js
Labels: area/console

#1862 Accessibilty for buttons
  add-ons/src/components/AddonPanel/AddonPanel.tsx
  add-ons/src/components/AddonPanel/RepositoryTableSegment/RepositoryTableSegment.tsx
  add-ons/src/components/CollapsiblePanel/CollapsiblePanel.tsx
  add-ons/src/components/CollapsiblePanel/test/__snapshots__/CollapsiblePanel.test.tsx.snap
  add-ons/src/components/Modals/DeleteConfigurationModal/DeleteConfigurationModal.component.tsx
  add-ons/src/components/Modals/DeleteUrlModal/DeleteUrlModal.component.tsx
  compass/src/components/ApiPackages/ApiPackageDetails/ApiList/ApiList.js
  compass/src/components/ApiPackages/ApiPackageDetails/EventList/EventList.js
  compass/src/components/Application/ApplicationDetails/ApplicationApiPackages/ApplicationApiPackages.js
  components/angular/generic-list/src/app/modules/list/list-search/list-search.component.html
  content/src/components/NavigationGroup.tsx
  content/src/components/styled.ts
  core-ui/src/components/ApiPackages/ApiPackageDetails/ApiList/ApiList.js
  core-ui/src/components/ApiPackages/ApiPackageDetails/EventList/EventList.js
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.js
  core-ui/src/components/ApiRules/ApiRules.js
  core-ui/src/components/Apis/ApiList/ApiList.js
  core-ui/src/components/Apis/ApplicationApiPackages/ApplicationApiPackages.js
  core-ui/src/components/Apis/EventApiList/EventApiList.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaStatusCard.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/LambdasList/LambdasList.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  logging/src/components/Shared/AdvancedSettings/AdvancedSettings.js
  logging/src/components/Shared/AdvancedSettings/test/__snapshots__/AdvancedSettings.test.js.snap
  logging/src/components/Shared/LabelsDisplay/LabelsDisplay.js
  logging/src/components/Shared/LabelsDisplay/test/__snapshots__/LabelsDisplay.test.js.snap
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  service-catalog-ui/src/components/ServiceClassList/Cards/Card.component.js
  service-catalog-ui/src/components/ServiceClassPlansList/ServiceClassPlansList.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/styled.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/styled.js
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/test/GenericList.test.js
  shared/components/ModalWithForm/ModalWithForm.js
  tests/tests/tests.js
Labels: area/console, enhancement

#1869 Fix tenant list styles
  compass/src/config/luigi-config/helpers/navigation-helpers.js
Labels: area/console, bug
