Repository kyma-project/console, pull requests merged in 2020-05, with the labels that each got.

#1761 Hide the Kyma version placeholder if the Kyma version is unknown
  core/src/luigi-config/navigation/navigation-data-init.js
Labels: area/console, bug

#1768 Use "services" as default tab in Catalog and Instances
  components/react/src/commons/instances-tab-utils.js
  components/react/src/components/Tabs/index.js
  service-catalog-ui/catalog/src/components/ServiceClassList/ServiceClassList.js
  service-catalog-ui/catalog/src/components/ServiceClassList/test/ServiceClassList.test.js
  service-catalog-ui/catalog/src/variables.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesList.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/test/ServiceInstancesList.test.js
  service-catalog-ui/instances/src/variables.js
Labels: area/console, enhancement

#1771 Change UsageKind for Function CR
  core-ui/src/components/Lambdas/constants.js
Labels: area/console, area/serverless

#1780 Add config file for functions view
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/ServiceBindingsWrapper.test.js
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateServiceBindingUsage.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useServiceBindingUsagesQuery.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useServiceBindingUsagesQuery.js
Labels: area/console, area/serverless, enhancement

#1773 Rewrite logging test
  logging/package.json
  logging/src/components/CompactHeader/test/CompactHeader.test.js
  logging/src/components/CompactHeader/test/__snapshots__/CompactHeader.test.js.snap
  logging/src/components/Header/test/Header.test.js
  logging/src/components/Header/test/__snapshots__/Header.test.js.snap
  logging/src/components/Logs/test/Logs.test.js
  logging/src/components/Logs/test/__snapshots__/Logs.test.js.snap
  logging/src/components/Shared/AdvancedSettings/test/AdvancedSettings.test.js
  logging/src/components/Shared/AdvancedSettings/test/__snapshots__/AdvancedSettings.test.js.snap
  logging/src/components/Shared/ResultsOptionsDropdown/ResultsOptionsDropdown.js
  logging/src/components/Shared/ResultsOptionsDropdown/test/ResultOptionsDropdown.test.js
  logging/src/components/Shared/ResultsOptionsDropdown/test/__snapshots__/ResultOptionsDropdown.test.js.snap
  logging/src/components/Shared/SelectDropdown/test/SelectDropdown.test.js
  logging/src/components/Shared/SelectDropdown/test/__snapshots__/SelectDropdown.test.js.snap
  logging/src/setupTests.js
Labels: area/console

#1783 Fix auth method dropdown in API Rules
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ServicesDropdown/test/ServicesDropdown.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/mocks.js
Labels: area/community, bug

#1777 Bump acorn
  components/angular/generic-list/package-lock.json
  core/package-lock.json
  package-lock.json
  shared/package-lock.json
Labels: area/console, dependencies

#1776 Upgrde https proxy agent
  components/angular/generic-list/package-lock.json
  core/package-lock.json
Labels: area/console, dependencies

#1785 Fix create application name input in Compass
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
Labels: area/console, area/management-plane, bug

#1781 Support HEAD and PATCH methods in API Rule UI
  core-ui/src/components/ApiRules/AccessStrategy/test/AccessStrategy.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.js
  core-ui/src/components/ApiRules/CreateApiRule/test/mocks.js
  core-ui/src/components/ApiRules/accessStrategyTypes.js
Labels: area/console, enhancement

#1788 Update makefile and dockerfile for new content job
  content/Dockerfile
  content/Makefile
  content/package.json
Labels: area/console

#1797 Bump odata-react in generic documentation
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/react/package-lock.json
  package-lock.json
Labels: area/console, enhancement

#1790 Write missing tests in functions view
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/test/CodeAndDependencies.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ConfigurationTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/test/EventTriggersWrapper.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/TableElements/Input.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/test/ResourceManagement.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/test/ConfigurationTab.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetailsWrapper.test.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useEventActivationsQuery.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useEventTriggersQuery.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useLambdaQuery.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useServiceInstancesQuery.test.js
  core-ui/src/components/Lambdas/helpers/resources/constants.js
  core-ui/src/components/Lambdas/helpers/resources/index.js
  core-ui/src/components/Lambdas/helpers/resources/parseCpu.js
  core-ui/src/components/Lambdas/helpers/resources/test/parseCpu.test.js
Labels: area/serverless, test-missing

#1714 Add more smoke tests
  components/react/src/components/Toolbar/index.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core/src/app/content/namespaces/operation/kubernetes-element-list.component.html
  core/src/app/content/settings/applications/applications.component.html
  logging/src/components/Header/Header.js
  logging/src/components/Shared/LabelsInput/DropdownRenderer/DropdownRenderer.js
  logging/src/components/Shared/LabelsInput/DropdownRenderer/test/__snapshots__/DropdownRenderer.test.js.snap
  logging/src/components/Shared/LabelsInput/DropdownRenderer/test/__snapshots__/DropdownRenderer.ui.test.js.snap
  service-catalog-ui/src/components/ServiceBrokers/ServiceBrokers.component.js
  service-catalog-ui/src/components/ServiceClassList/ServiceClassToolbar/ServiceClassToolbar.component.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceToolbar/ServiceInstanceToolbar.component.js
  shared/components/PageHeader/PageHeader.js
  tests/config.js
  tests/helpers.js
  tests/package-lock.json
  tests/package.json
  tests/tests/tests.js
Labels: area/console, enhancement

#1806 Display Api type in dropdown placeholder if there is no display name
  components/generic-documentation/src/renderers/helpers/ApiSelector.tsx
Labels: area/console, enhancement

#1811 Improve settings view
  core/src/app/app.module.ts
  core/src/app/content/settings/organisation/organisation.component.scss
  core/src/app/content/settings/preferences/preferences.component.html
  core/src/app/content/settings/preferences/preferences.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
Labels: area/console, enhancement

#1814 XSRF and XSS countermeasures documented
  README.md
Labels: area/console, security/medium

#1817 Fix login mechanism in smoke tests
  tests/helpers.js
Labels: area/console, test-failing

#1810 Do not request oauth token as we do not need it
  core/src/luigi-config/auth.js
Labels: area/console, security/low
