Repository kyma-project/console, pull requests merged in 2020-08, with the labels that each got.

#1916 Fix brokers list
  service-catalog-ui/src/components/App/App.js
  service-catalog-ui/src/components/ServiceBrokers/ServiceBrokers.component.js
  service-catalog-ui/src/components/ServiceBrokers/ServiceBrokers.component.scss
  service-catalog-ui/src/components/ServiceBrokers/ServiceBrokers.container.js
  service-catalog-ui/src/components/ServiceBrokers/ServiceBrokers.js
  service-catalog-ui/src/components/ServiceBrokers/styled.js
  service-catalog-ui/src/components/ServiceBrokers/test/ServiceBrokers.test.js
  service-catalog-ui/src/components/ServiceBrokers/test/mocks.js
Labels: area/console, bug

#1909 Fix double fetch on Instances
  service-catalog-ui/src/builder.js
Labels: area/console, bug

#1912 Restrict Namespace list response
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/NamespaceDetailsCard.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespacesGrid.js
  core-ui/src/components/NamespaceList/NamespacesGrid/getPodsCounts.js
  core-ui/src/components/NamespaceList/NamespacesGrid/test/NamespaceGrid.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/test/getPodsCounts.test.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
Labels: area/console, bug

#1914 Resolve Github vulnerabilities
  package-lock.json
  package.json
Labels: area/console, area/security

#1915 Make categories collapsible
  core/src/luigi-config/navigation/static-navigation-model.js
  tests/helpers.js
  tests/tests/tests.js
Labels: area/console

#1920 Add info when some parts of service details view are hidden
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.component.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceTabs/ServiceInstanceTabs.component.js
Labels: area/console

#1904 OAuth Clients
  core-ui/src/apollo.js
  core-ui/src/components/App/App.js
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/namespaceWorkloadsHelpers.js
  core-ui/src/components/OAuthClients/Create/CreateOAuthClient.js
  core-ui/src/components/OAuthClients/Create/test/CreateOAuthClient.test.js
  core-ui/src/components/OAuthClients/Create/test/mocks.js
  core-ui/src/components/OAuthClients/Details/OAuthClientDetails.js
  core-ui/src/components/OAuthClients/Details/OAuthClientHeader.js
  core-ui/src/components/OAuthClients/Details/OAuthClientSpecPanel.js
  core-ui/src/components/OAuthClients/Details/Secret/OAuthClientSecret.js
  core-ui/src/components/OAuthClients/Details/Secret/OAuthClientSecret.scss
  core-ui/src/components/OAuthClients/Details/Secret/test/OAuthClientSecret.test.js
  core-ui/src/components/OAuthClients/Details/Secret/test/mocks.js
  core-ui/src/components/OAuthClients/Details/test/OAuthClientDetails.test.js
  core-ui/src/components/OAuthClients/Details/test/OAuthClientHeader.test.js
  core-ui/src/components/OAuthClients/Details/test/OAuthClientSpecPanel.test.js
  core-ui/src/components/OAuthClients/Details/test/mocks.js
  core-ui/src/components/OAuthClients/Form/CheckboxFormControl.js
  core-ui/src/components/OAuthClients/Form/OAuthClientForm.js
  core-ui/src/components/OAuthClients/Form/OAuthClientForm.scss
  core-ui/src/components/OAuthClients/Form/test/CheckboxFormControl.test.js
  core-ui/src/components/OAuthClients/Form/test/OAuthClientForm.test.js
  core-ui/src/components/OAuthClients/Form/test/mocks.js
  core-ui/src/components/OAuthClients/List/OAuthClientLink.js
  core-ui/src/components/OAuthClients/List/OAuthClientsList.js
  core-ui/src/components/OAuthClients/List/test/OAuthClientsList.test.js
  core-ui/src/components/OAuthClients/List/test/mocks.js
  core-ui/src/components/OAuthClients/Status/OAuthClientStatus.js
  core-ui/src/components/OAuthClients/Status/test/OAuthClientStatus.test.js
  core-ui/src/components/OAuthClients/common.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
  core-ui/src/shared/constants.js
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/components/GenericList/actionHandlers/simpleDelete.js
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/PageHeader/PageHeader.js
  shared/components/PageHeader/PageHeader.scss
  shared/index.js
  shared/utils/handleSubscriptionArrayEvent.js
  shared/utils/handleSubscriptionEvent.js
  shared/utils/test/handleSubscriptionArrayEvent.test.js
  shared/utils/test/handleSubscriptionEvent.test.js
Labels: area/console

#1933 Handle empty range limits
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.ts
Labels: area/console, bug

#1934 Window titles
  add-ons/src/components/Toolbar/Toolbar.component.tsx
  add-ons/src/constants.ts
  content/src/core/App.tsx
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/shared/constants.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/configuration/resources/resources.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resources.component.ts
  core/src/app/content/namespaces/operation/configmaps/configmaps.component.spec.ts
  core/src/app/content/namespaces/operation/configmaps/configmaps.component.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.spec.ts
  core/src/app/content/namespaces/operation/deployments/deployments.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.spec.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/content/namespaces/operation/replica-sets/replica-sets.component.spec.ts
  core/src/app/content/namespaces/operation/replica-sets/replica-sets.component.ts
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.spec.ts
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.spec.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.ts
  core/src/app/content/namespaces/operation/services/services.component.spec.ts
  core/src/app/content/namespaces/operation/services/services.component.ts
  core/src/app/content/settings/applications/application-details/application-details.component.spec.ts
  core/src/app/content/settings/applications/application-details/application-details.component.ts
  core/src/app/content/settings/applications/applications.component.ts
  core/src/app/content/settings/preferences/preferences.component.ts
  core/src/app/shared/components/permissions/permissions.component.ts
  core/src/app/shared/components/permissions/role-details/role-details.component.ts
  core/src/app/shared/services/window-title.service.ts
  core/src/index.html
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/settings.js
  logging/src/components/LogsContainer.js
  service-catalog-ui/src/components/App/App.js
  service-catalog-ui/src/shared/constants.js
  shared/hooks/index.js
  shared/hooks/useWindowTitle.js
Labels: area/console

#1940 Fix namespaces dropdown
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.scss
Labels: area/console, bug

#1927 Allow user to choose Function runtime
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.scss
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaLabels.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/LambdasList/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/LambdasList.js
  core-ui/src/components/Lambdas/LambdasList/RuntimeDropdown.js
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useUpdateLambda.js
  core-ui/src/components/Lambdas/gql/queries.js
  core-ui/src/components/Lambdas/gql/subscriptions.js
  core-ui/src/components/Lambdas/helpers/runtime/index.js
  core-ui/src/components/Lambdas/helpers/runtime/runtime.js
  core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
  core-ui/webpack.config.js
Labels: area/console, area/serverless, enhancement

#1945 Update python runtime version
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/runtime/runtime.js
  core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
Labels: area/serverless

#1937 Cypress POC
  tests/.dockerignore
  tests/.testcaferc.json
  tests/Dockerfile
  tests/README.md
  tests/config.js
  tests/cypress.json
  tests/helpers.js
  tests/package-lock.json
  tests/package.json
  tests/plugins/index.js
  tests/support/commands.js
  tests/support/iframe-commands.js
  tests/support/index.js
  tests/tests/console-smoke-tests.spec.js
  tests/tests/tests.js
Labels: area/console

#1936 Improvements after review
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/components/OAuthClients/List/OAuthClientsList.js
  core-ui/src/shared/constants.js
Labels: area/console

#1948 Addons ui fixes
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  core-ui/src/index.scss
  shared/components/ListActions/ListActions.scss
Labels: area/console

#1943 Remove host used in old UI tests
  package.json
Labels: area/console

#1951 Use GQL in resource upload
  core-ui/src/components/NamespaceDetails/DeployResourceModal/DeployResourceModal.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/deployResourceHelpers.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/test/DeployResourceModal.test.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/test/deployResourceHelpers.test.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/test/mocks.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
  core-ui/src/gql/mutations.js
  core/src/app/content/namespaces/services/namespaces.service.spec.ts
  core/src/app/content/namespaces/services/namespaces.service.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts
  core/src/app/shared/components/resource-uploader/services/resource-upload.service.ts
  core/src/app/shared/components/resource-uploader/uploader/uploader.component.ts
Labels: area/console
