Repository kyma-project/console, pull requests merged in 2020-12, with the labels that each got.

#2059 Remove content-ui
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
  README.md
  components/generic-documentation/src/index.tsx
  components/generic-documentation/src/layouts/ContentUI.tsx
  components/generic-documentation/src/layouts/index.ts
  components/generic-documentation/src/layouts/styled.ts
  components/generic-documentation/src/loader/loader.ts
  content/.dockerignore
  content/.env
  content/Dockerfile
  content/Makefile
  content/OWNERS
  content/README.md
  content/config-overrides.js
  content/nginx.conf
  content/package-lock.json
  content/package.json
  content/public/config/config.js
  content/public/fonts/72-Bold.woff
  content/public/fonts/72-Bold.woff2
  content/public/fonts/72-Regular.woff
  content/public/fonts/72-Regular.woff2
  content/public/fonts/SAP-icons.ttf
  content/public/fonts/SAP-icons.woff
  content/public/fonts/SAP-icons.woff2
  content/public/index.html
  content/src/components/Content.tsx
  content/src/components/Navigation.tsx
  content/src/components/NavigationGroup.tsx
  content/src/components/NavigationItem.tsx
  content/src/components/NavigationList.tsx
  content/src/components/styled.ts
  content/src/constants.ts
  content/src/core/App.tsx
  content/src/core/styled.ts
  content/src/index.tsx
  content/src/react-app-env.d.ts
  content/src/services/clusterAssetGroups.service.ts
  content/src/services/index.ts
  content/src/services/navigation.service.ts
  content/src/services/queries.service.ts
  content/src/services/types.ts
  content/tsconfig.json
  core/src/luigi-config/navigation/navigation-data-init.js
  gulpfile.js
  lerna.json
  tests/config.js
  tests/package.json
  tests/tests/console-smoke-tests.spec.js
  tslint.json
Labels: area/console

#2062 Require at least one method
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/accessStrategyTypes.js
Labels: area/console

#2064 Add delete to services
  core-ui/src/components/Services/ServiceDetails/ServiceDetailsHeader/ServiceDetailsHeader.js
  core-ui/src/components/Services/ServicesList/ServicesList.js
  core-ui/src/gql/mutations.js
Labels: area/console

#2055 Use Pamela on pod list
  .clusterConfig.default
  core-ui/src/components/App/App.js
  core-ui/src/components/Pods/PodList/PodList.js
  core-ui/src/components/Pods/Pods.js
  core-ui/src/components/Pods/constants.js
  core-ui/src/shared/constants.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.html
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.html
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.scss
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.spec.ts
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.spec.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  package-lock.json
  package.json
  shared/contexts/ConfigContext.js
  shared/contexts/ConfigContext.test.js
  shared/hooks/PamelaAPI/config.js
  shared/hooks/PamelaAPI/index.js
  shared/hooks/PamelaAPI/useGet.js
  shared/hooks/PamelaAPI/useMutation.js
  shared/hooks/PamelaAPI/useSubscription.js
  shared/hooks/index.js
  shared/package-lock.json
  shared/package.json
Labels: enhancement

#2065 Remove unused uploader component
  core/package-lock.json
  core/package.json
  core/src/app/app.module.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-component/resource-uploader.component.html
  core/src/app/shared/components/resource-uploader/resource-uploader-component/resource-uploader.component.scss
  core/src/app/shared/components/resource-uploader/resource-uploader-component/resource-uploader.component.spec.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-component/resource-uploader.component.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.html
  core/src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.spec.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts
  core/src/app/shared/components/resource-uploader/services/resource-upload.service.ts
  core/src/app/shared/components/resource-uploader/uploader/uploader.component.html
  core/src/app/shared/components/resource-uploader/uploader/uploader.component.scss
  core/src/app/shared/components/resource-uploader/uploader/uploader.component.spec.ts
  core/src/app/shared/components/resource-uploader/uploader/uploader.component.ts
  package-lock.json
Labels: area/console

#2068 Fix target _blank issue
  components/generic-documentation/src/render-engines/open-api/components/OperationTag.tsx
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
Labels: area/console, bug

#2067 Disable unstable apps smoke test
  tests/tests/console-smoke-tests.spec.js
Labels: area/console, test-failing

#2066 Add regex for search in angular components
  components/angular/generic-list/src/app/modules/list/list-search/list-search.component.ts
Labels: area/console, bug

#2073 Add "Deploy new workload" dropdown
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaModal.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/DeployResourceModal.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/test/DeployResourceModal.test.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.scss
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/test/NamespaceDetailsHeader.test.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/test/mocks.js
Labels: area/console, enhancement

#2074 Rework navigation structure
  core/src/luigi-config/navigation/static-navigation-model.js
  tests/tests/console-smoke-tests.spec.js
Labels: area/console, enhancement
