Repository kyma-project/console, pull requests merged in 2020-02, with the labels that each got.

#1545 Fix storing default credentials on API def add
  compass/src/components/Api/CreateApiForm/CreateApiForm.component.js
Labels: area/console, area/management-plane, bug

#1546 Update fundamental version
  compass/package-lock.json
  compass/package.json
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Applications/BindNamespaceModal/test/BindNamespaceModal.test.js
  core-ui/src/components/Applications/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  core/package-lock.json
  logging/package-lock.json
  package-lock.json
  package.json
  shared/components/ListActions/test/ListActions.test.js
  shared/components/ListActions/test/__snapshots__/ListActions.test.js.snap
  shared/package.json
  shared/webpack.config.js
Labels: area/console

#1552 Fix runtimes unassign from scenarios view
  compass/src/components/Scenarios/ScenarioDetails/ScenarioRuntimes/ScenarioRuntimes.container.js
Labels: area/console, bug

#1556 Fix the 'ReadOnly' flag handling in old Applications view
  core/src/app/content/settings/applications/application-details/application-details.component.html
Labels: area/console, bug

#1555 Remove unused actions from the applications list
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
Labels: area/console

#1549 Pass tenantId to compass views and change paths to show compass in console
  compass/src/components/Api/ApiDetails/ApiDetails.component.js
  compass/src/components/Api/EditApi/EditApi.component.js
  compass/src/components/Api/EditEventApi/EditEventApi.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioDetailsHeader/ScenarioDetailsHeader.js
  compass/src/components/Shared/ResourceNotFound.component.js
  compass/src/config/luigi-config/navigation.js
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#1553 App details subscription
  core-ui/src/components/Apis/CreateApiForm/CreateApiForm.js
  core-ui/src/components/Apis/CreateEventForm/CreateEventForm.js
  core-ui/src/components/Applications/ApplicationDetails/ApplicationDetails.js
  core-ui/src/components/Applications/ApplicationDetails/test/ApplicationDetails.test.js
  core-ui/src/components/Applications/ApplicationDetails/test/mocks.js
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/ApplicationStatus/ApplicationStatus.js
  core-ui/src/components/Applications/BoundNamespacesList/BoundNamespacesList.js
  core-ui/src/gql/queries.js
Labels: area/console, enhancement

#1554 Remove possibility to add and delete runtimes
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Runtimes/Runtimes.component.js
  shared/components/StatusBadge/StatusBadge.js
  shared/components/StatusBadge/test/StatusBadge.test.js
  shared/components/StatusBadge/test/__snapshots__/StatusBadge.test.js.snap
  shared/index.js
Labels: area/console, enhancement

#1560 Group dependent navigation
  .clusterConfig.default
  core/package-lock.json
  core/package.json
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/permissions.js
Labels: area/console, enhancement

#1559 Remove mocked connected status from applications
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
Labels: area/console

#1563 Store users data in session storage instead of local storage
  compass/public-luigi/index.html
  compass/src/config/luigi-config/auth.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  core/src/luigi-config/luigi-config.js
Labels: area/console, enhancement

#1561 Register Application from template
  core-ui/src/components/Applications/ApplicationList/ApplicationList.js
  core-ui/src/components/Applications/CreateApplicationFromTemplateModal/CreateApplicationFromTemplateModal.js
  core-ui/src/components/Applications/CreateApplicationFromTemplateModal/CreateApplicationFromTemplateModal.scss
  core-ui/src/components/Applications/CreateApplicationFromTemplateModal/test/CreateApplicationFromTemplateModal.test.js
  core-ui/src/components/Applications/CreateApplicationFromTemplateModal/test/mocks.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/ModalWithForm/test/__snapshots__/ModalWithForm.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/NamespaceDetailsCard.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/__snapshots__/NamespaceDetailsCard.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesGrid/test/NamespaceGrid.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/test/__snapshots__/NamespaceGrid.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/test/NamespaceFilters.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/test/__snapshots__/NamespaceFilters.test.js.snap
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.ui.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/__snapshots__/NamespaceListHeader.test.js.snap
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/index.scss
  core/package-lock.json
  lambda/package-lock.json
  logging/package-lock.json
  package-lock.json
  package.json
  shared/components/Dropdown/Dropdown.js
  shared/package.json
Labels: area/console

#1543 Apply filter by labels in api rules view in core-ui
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/mocks.js
  core-ui/src/components/ApiRules/CreateApiRule/test/mocks.js
  core-ui/src/components/ApiRules/EditApiRule/test/mocks.js
  core-ui/src/components/ApiRules/constants.js
  core-ui/src/gql/queries.js
Labels: area/console, enhancement

#1566 Rewrite namespace tests
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/NamespaceDetailsCard.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/NamespaceDetailsCard.test.js
  core-ui/src/components/NamespaceList/NamespacesGrid/NamespaceDetailsCard/test/mocks.js
  core-ui/src/components/NamespaceList/NamespacesGrid/test/NamespaceGrid.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/NamespaceFilters.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespaceFilters/test/NamespaceFilters.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/NamespacesListHeader.scss
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.test.js
  core-ui/src/components/NamespaceList/NamespacesListHeader/test/NamespaceListHeader.ui.test.js
Labels: area/console, enhancement

#1565 Update node and nginx in console docker images to fix vulnerabilites
  add-ons/Dockerfile
  compass/Dockerfile
  content/Dockerfile
  core-ui/Dockerfile
  core/Dockerfile
  lambda/Dockerfile
  logging/Dockerfile
  service-catalog-ui/Dockerfile
Labels: area/console

#1564 Add a random string to the test namespace name
  tests/ui-tests/commands/common.js
  tests/ui-tests/setup/k8s-api/index.js
  tests/ui-tests/setup/k8s-api/k8s-api-namespace.js
  tests/ui-tests/tests/console-basic-test.js
Labels: area/console, test-failing

#1562 Display Kyma version in the footer
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/queries.js
Labels: area/console, enhancement

#1576 Fix non-existing Counter element & key-prop error
  service-catalog-ui/catalog/src/components/ServiceClassList/ServiceClassList.js
  service-catalog-ui/catalog/src/components/ServiceClassList/test/ServiceClassList.test.js
  service-catalog-ui/instances/src/components/ServiceInstanceDetails/ServiceInstanceBindings/StatusIndicator/StatusIndicator.component.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/ServiceInstancesList.js
  service-catalog-ui/instances/src/components/ServiceInstancesList/test/ServiceInstancesList.test.js
Labels: area/console, bug

#1577 Unify API Rules naming
  core-ui/src/components/ApiRules/ApiRules.js
  core-ui/src/components/ApiRules/test/ApiRules.test.js
Labels: area/console, area/documentation

#1579 Lambda triggers purely based on knative triggers
  lambda/src/app/app.module.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.spec.ts
  lambda/src/app/lambdas/lambda-details/lambda-details.component.ts
  lambda/src/app/lambdas/list/lambdas.component.spec.ts
  lambda/src/app/lambdas/list/lambdas.component.ts
  lambda/src/app/subscriptions/subscriptions.service.spec.ts
  lambda/src/app/subscriptions/subscriptions.service.ts
Labels: area/console, area/serverless

#1583 Api package on service details and modal
  service-catalog-ui/catalog/src/components/App/App.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/CreateInstanceModal/test/CreateInstanceModal.test.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetails.scss
  service-catalog-ui/catalog/src/components/ServiceClassDetails/ServiceClassDetailsHeader/ServiceClassDetailsHeader.component.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/test/ServiceClassDetails.test.js
  service-catalog-ui/catalog/src/components/ServiceClassList/Cards/Card.component.js
  service-catalog-ui/catalog/src/shared/constants.js
  service-catalog-ui/catalog/src/testing/queriesMocks.js
  service-catalog-ui/catalog/src/testing/serviceClassesMocks.js
Labels: area/console, enhancement

#1578 Fix log lines in log UI
  logging/src/components/LogTable/LogTable.js
Labels: area/console, area/logging, enhancement
