Repository kyma-project/console, pull requests merged in 2020-04, with the labels that each got.

#1667 Assign codeownership of the new lambd view to new team
  CODEOWNERS
Labels: area/console, enhancement

#1666 Extend GenericList with collapsing content and ModalWithForm with popup message
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/ModalWithForm/test/ModalWithForm.test.js
  core-ui/src/components/ModalWithForm/test/__snapshots__/ModalWithForm.test.js.snap
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/GenericList.scss
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/components.js
  shared/components/GenericList/constants.js
  shared/components/GenericList/helpers.js
  shared/components/GenericList/test/GenericList.test.js
  shared/components/PageHeader/PageHeader.js
  shared/components/Spinner/Spinner.js
  shared/contexts/NotificationContext.js
Labels: area/console, enhancement

#1659 luigi rc1 meets compass
  .clusterConfig.default
  compass/package-lock.json
  compass/package.json
  compass/public-luigi/config/config.js
  compass/public-luigi/logout.html
  compass/public/config/config.js
  compass/src/components/Api/ApiDetails/ApiDetailsHeader/ApiDetailsHeader.js
  compass/src/components/Api/EditApi/EditApi.component.js
  compass/src/components/Api/EditApiHeader/EditApiHeader.component.js
  compass/src/components/Api/EditEventApi/EditEventApi.component.js
  compass/src/components/ApiPackages/ApiPackageDetails/ApiList/ApiList.js
  compass/src/components/ApiPackages/ApiPackageDetails/EventList/EventList.js
  compass/src/components/ApiPackages/ApiPackageDetails/Header/ApiPackageDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationApiPackages/ApplicationApiPackages.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.component.js
  compass/src/components/Applications/Applications.component.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Labels/CreateLabelModal/CreateLabelModal.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitionDetails/MetadataDefinitionDetails.component.js
  compass/src/components/MetadataDefinitions/MetadataDefinitions.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetailsHeader/RuntimeDetailsHeader.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Runtimes/Runtimes.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioModal/CreateScenarioModal.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/ScenarioApplications.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioDetailsHeader/ScenarioDetailsHeader.js
  compass/src/components/Scenarios/ScenarioDetails/shared/AssignEntityToScenarioModal/AssignEntityToScenarioModal.component.js
  compass/src/components/Scenarios/ScenarioDetails/shared/unassignScenarioHandler.js
  compass/src/components/Scenarios/Scenarios.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  compass/src/components/Shared/ResourceNotFound.component.js
  compass/src/components/TenantSearch/TenantSearch.js
  compass/src/components/TenantSearch/test/TenantSearch.test.js
  compass/src/config/luigi-config/auth.js
  compass/src/config/luigi-config/clusterConfig.js
  compass/src/config/luigi-config/helpers/getAlternativePath.js
  compass/src/config/luigi-config/helpers/getAlternativePath.test.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  compass/src/config/luigi-config/main.js
  compass/src/config/luigi-config/navigation.js
  compass/src/setupTests.js
  compass/src/shared/components/Modal/Modal.js
  compass/src/shared/components/ModalWithForm/ModalWithForm.js
  compass/src/store/getConfigValue.js
  compass/src/store/index.js
  compass/webpack-generateConfig.config.js
Labels: area/console, area/management-plane, enhancement

#1680 fix links
  CONTRIBUTING.md
Labels: area/documentation

#1675 Common API documentation tab with a chooser
  components/generic-documentation/src/constants.ts
  components/generic-documentation/src/layouts/CatalogUI.tsx
  components/generic-documentation/src/loader/loader.ts
  components/generic-documentation/src/renderers/Group.renderer.tsx
  components/generic-documentation/src/renderers/SingleAPIcontent.tsx
  components/generic-documentation/src/renderers/helpers/ApiSelector.tsx
  components/generic-documentation/src/renderers/helpers/styled.ts
  components/react/package-lock.json
  service-catalog-ui/catalog/src/index.js
  service-catalog-ui/instances/src/index.js
Labels: area/console, enhancement

#1645 Add the first test using Testcafe
  tests/.babelrc
  tests/.dockerignore
  tests/.eslinterrc
  tests/.gitignore
  tests/Dockerfile
  tests/README.md
  tests/config.js
  tests/helpers.js
  tests/jest-setup.js
  tests/package-lock.json
  tests/package.json
  tests/tests/tests.js
  tests/ui-tests/commands/catalog.js
  tests/ui-tests/commands/common.js
  tests/ui-tests/commands/console.js
  tests/ui-tests/commands/docs.js
  tests/ui-tests/commands/lambdas.js
  tests/ui-tests/commands/logging.js
  tests/ui-tests/config.js
  tests/ui-tests/setup/k8s-api/index.js
  tests/ui-tests/setup/k8s-api/k8s-api-deployment.js
  tests/ui-tests/setup/k8s-api/k8s-api-service.js
  tests/ui-tests/setup/kubeconfig.js
  tests/ui-tests/setup/namespace-manager.js
  tests/ui-tests/setup/test-pluggable.js
  tests/ui-tests/tests/applications-test.js
  tests/ui-tests/tests/console-basic-test.js
  tests/ui-tests/tests/docs-ui-test.js
  tests/ui-tests/tests/lambda-ui-test.js
  tests/ui-tests/tests/logging-test.js
  tests/ui-tests/utils/address.js
  tests/ui-tests/utils/logging.js
  tests/ui-tests/utils/retry.js
  tests/ui-tests/utils/skip.js
  tests/ui-tests/utils/testContext.js
Labels: area/console, enhancement

#1681 Fix Compass UI views are getting unsynchronized after modifying entity
  compass/src/components/Scenarios/EnititesForScenarioCount.js
  compass/src/components/Scenarios/EntitiesForScenarioCounter/EnititesForScenarioCounter.js
  compass/src/components/Scenarios/EntitiesForScenarioCounter/test/EntitiesForScenarioCounter.test.js
  compass/src/components/Scenarios/EntitiesForScenarioCounter/test/mocks.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/ScenarioApplications.js
  compass/src/components/Scenarios/Scenarios.component.js
Labels: area/console, area/management-plane, bug

#1683 Hide system namespaces toggle for non-runtime-admins
  core/src/app/content/settings/organisation/organisation.component.html
  core/src/app/content/settings/organisation/organisation.component.ts
Labels: area/console, enhancement

#1685 Fix documentation for instances
  components/generic-documentation/package.json
  components/generic-documentation/src/layouts/InstancesUI.tsx
  components/generic-documentation/tsconfig.dev.json
  scripts/setClusterConfig.sh
Labels: area/console, bug

#1677 Add displayName in generic documentation
  common/src/types/rafter.ts
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/generic-documentation/src/layouts/CatalogUI.tsx
  components/generic-documentation/src/layouts/InstancesUI.tsx
  components/generic-documentation/src/loader/loader.ts
  components/generic-documentation/src/renderers/Group.renderer.tsx
  components/generic-documentation/src/renderers/helpers/ApiSelector.tsx
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  service-catalog-ui/catalog/src/components/ServiceClassDetails/queries.js
  service-catalog-ui/instances/src/queries/fragments.js
  service-catalog-ui/instances/src/testing/instanceMocks.js
Labels: WIP, area/console, area/documentation, enhancement

#1690 Fix catalog UI test
  tests/helpers.js
  tests/package.json
  tests/tests/tests.js
Labels: area/console, test-failing

#1687 Improve Service Bindings and Event Triggers panels UX
  core-ui/src/components/Lambdas/CreateEventTriggerForm/CreateEventTriggerForm.js
  core-ui/src/components/Lambdas/CreateServiceBindingForm/test/gqlMocks.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/CreateEventTriggerModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/EventTriggers.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/EventTriggersWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindingsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/CreateServiceBindingForm.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/ServiceBindings.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/ServiceBindingsWrapper.test.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useCreateManyEventTriggers.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateManyEventTriggers.js
  core-ui/src/components/Lambdas/gql/hooks/queries/index.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useEventActivationsQuery.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useServiceInstancesQuery.js
  core-ui/src/components/Lambdas/gql/queries.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/serializeEvents.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/test/serializeEvents.test.js
  core-ui/src/components/Lambdas/helpers/serviceBindingUsages/filterServiceInstances.js
  core-ui/src/components/Lambdas/helpers/serviceBindingUsages/index.js
  core-ui/src/components/Lambdas/helpers/serviceBindingUsages/test/filterServiceInstances.test.js
Labels: area/console, bug

#1678 Show lambda build and execution logs in UI
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.ui.test.js
  core-ui/src/components/Lambdas/helpers/misc/test/useLogsView.test.js
  core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
  logging/src/components/LogsContainer.js
Labels: area/console, area/serverless, enhancement

#1703 Allow connection to remote compass-gateway APIs
  compass/nginx.conf
  core-ui/nginx.conf
Labels: area/management-plane, bug

#1705 API dropdown fixes
  components/generic-documentation/src/index.tsx
  components/generic-documentation/src/loader/loader.ts
  components/generic-documentation/src/renderers/helpers/ApiSelector.tsx
  components/generic-documentation/src/renderers/helpers/styled.ts
Labels: area/console

#1713 Remember navigation state after logout in compass
  compass/src/config/luigi-config/auth.js
  compass/src/config/luigi-config/helpers/navigation-helpers.js
  compass/src/config/luigi-config/helpers/navigation-helpers.test.js
  package-lock.json
Labels: area/console, enhancement

#1712 Legacy applications: count events and apis
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.ts
Labels: area/console

#1704 Default Application scenario [UI]
  .clusterConfig.default
  compass/src/App.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.container.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.test.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationScenarioModal.container.js
  compass/src/components/Application/gql.js
  compass/src/components/Applications/Applications.test.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioApplications/ScenarioApplications.js
  compass/src/components/Scenarios/gql.js
Labels: area/console, area/management-plane, enhancement

#1715 Add resources and replicas management to Functions CR
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/Configuration.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/TableElements/Input.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/TableElements/Row.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useUpdateLambda.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useUpdateLambda.js
  core-ui/src/components/Lambdas/helpers/testing/MutationComponent.js
Labels: area/console, area/serverless, enhancement

#1711 Improve new lambda details view with status information
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.scss
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/EditLambdaLabelsModal.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.scss
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaLabels.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaStatusCard.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/test/EditLambdaLabelsModal.test.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/test/LambdaStatusCard.test.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/test/CodeAndDependencies.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ConfigurationTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/test/EventTriggersWrapper.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindingsService.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindingsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/CreateServiceBindingModal.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/ServiceBindings.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/ServiceBindingsService.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/ServiceBindingsWrapper.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/test/gqlMocks.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/test/ConfigurationTab.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetailsWrapper.test.js
  core-ui/src/components/Lambdas/Lambdas.js
  core-ui/src/components/Lambdas/LambdasList/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/CreateLambdaModal.js
  core-ui/src/components/Lambdas/LambdasList/LambdasList.js
  core-ui/src/components/Lambdas/LambdasList/LambdasList.scss
  core-ui/src/components/Lambdas/LambdasList/LambdasListWrapper.js
  core-ui/src/components/Lambdas/LambdasList/test/CreateLambdaModal.test.js
  core-ui/src/components/Lambdas/LambdasList/test/LambdasList.test.js
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.js
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.scss
  core-ui/src/components/Lambdas/components/LambdaNameInput/LambdaNameInput.js
  core-ui/src/components/Lambdas/components/LambdaNameInput/LambdaNameInput.scss
  core-ui/src/components/Lambdas/components/index.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/index.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateServiceBindingUsage.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useDeleteLambda.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useDeleteServiceBindingUsage.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useEventTriggersQuery.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useLambdasQuery.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useServiceBindingUsagesQuery.js
  core-ui/src/components/Lambdas/gql/mutations.js
  core-ui/src/components/Lambdas/helpers/lambdas/index.js
  core-ui/src/components/Lambdas/helpers/lambdas/logsViewHelpers.js
  core-ui/src/components/Lambdas/helpers/lambdas/statusType.js
  core-ui/src/components/Lambdas/helpers/misc/constants.js
  core-ui/src/components/Lambdas/helpers/misc/test/useLogsView.test.js
  core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
Labels: area/console, area/serverless, enhancement

#1718 Add Lambdas/constants.js to responsibilities of technical writers
  CODEOWNERS
Labels: area/documentation, enhancement

#1717 Change back button text
  content/src/constants.ts
Labels: area/console

#1706 Create Environment Variables Panel in new lambdas view
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaEnvs.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/SingleVariableInput.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/validation.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/validation.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.scss
  core-ui/src/components/Lambdas/components/LambdaNameInput/LambdaNameInput.scss
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/beautifyEventSchema.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/index.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/newVariableModel.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
  core-ui/src/components/Lambdas/helpers/misc/test/useLogsView.test.js
  core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
  shared/components/GenericList/components.js
  shared/components/GenericList/test/GenericList.test.js
  shared/components/ListActions/ListActions.js
Labels: area/serverless, enhancement

#1721 Fix text in lambda UI in resources & replicas section
  core-ui/src/components/Lambdas/constants.js
Labels: area/documentation, area/serverless, enhancement

#1725 Display runtime labels
  compass/src/App.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.component.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.container.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeDetails.scss
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Shared/LabelsTable/LabelsTable.js
  compass/src/components/Shared/LabelsTable/test/LabelsTable.test.js
  compass/src/components/TenantSearch/TenantSearch.js
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
  core-ui/src/components/Applications/ConnectApplicationModal/ConnectApplication.js
  shared/components/CopiableText/CopiableText.js
  shared/components/CopiableText/CopiableText.scss
  shared/components/CopiableText/test/CopiableText.test.js
  shared/components/GenericList/GenericList.scss
  shared/components/Link/CopiableLink.js
  shared/components/Link/Link.js
  shared/index.js
Labels: area/console, area/management-plane, enhancement

#1724 Remove import of not existing file
  core-ui/public/index.html
Labels: area/console, bug

#1733 Fix ownerRef for Event Triggers and some texts in Function views
  core-ui/src/components/Lambdas/LambdasList/LambdasList.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/createOwnerRef.js
  core-ui/src/components/Lambdas/helpers/eventTriggers/test/createOwnerRef.test.js
  shared/components/K8sNameInput/K8sNameInput.js
Labels: area/console, area/serverless, bug

#1735 Add applications labels
  compass/src/App.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.component.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.container.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetails.scss
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsHeader/ApplicationDetailsHeader.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.js
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.test.js
  compass/src/components/Application/ApplicationDetails/test/ApplicationDetails.test.js
  compass/src/components/Applications/Applications.component.js
Labels: area/console, area/management-plane, enhancement

#1741 Remove deprecated part of the API Definition query
  core-ui/src/gql/queries.js
Labels: area/console, bug

#1738 Fix bugs connected with resource management section in Function UI view
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/test/ResourceManagement.test.js
  core-ui/src/components/Lambdas/constants.js
Labels: area/console, area/serverless

#1742 Read groups info from luigi context
  core/src/app/content/settings/organisation/organisation.component.ts
Labels: area/console, bug

#1743 Add missed namespace arg for functions/triggers mutations.
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useCreateManyEventTriggers.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useDeleteEventTrigger.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useDeleteLambda.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateManyEventTriggers.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useDeleteEventTrigger.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useDeleteLambda.js
  core-ui/src/components/Lambdas/gql/mutations.js
Labels: area/console, area/serverless, bug

#1749 Show not enough permissions message
  components/generic-documentation/package-lock.json
  core/angular.json
  core/package-lock.json
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/nopermissions.html
  logging/package-lock.json
Labels: area/console, enhancement

#1759 Fix texts for replicas management
  core-ui/src/components/Lambdas/constants.js
Labels: area/serverless, enhancement, priority/critical

#1758 Stabilize ui tests
  tests/.testcaferc.json
  tests/helpers.js
  tests/package.json
  tests/tests/tests.js
Labels: area/console, test-failing
