Repository kyma-project/console, pull requests merged in 2020-09, with the labels that each got.

#1960 Add the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, enhancement

#1958 Rewrite permissions
  core-ui/src/components/App/App.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/ClusterRoleBindingList.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/CreateClusterRoleBindingModal.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/ClusterRoleBindingList.test.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/CreateClusterRoleBindingModal.test.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/mocks.js
  core-ui/src/components/Permissions/ClusterRoleList/ClusterRoleList.js
  core-ui/src/components/Permissions/ClusterRoleList/test/ClusterRoleList.test.js
  core-ui/src/components/Permissions/PermissionList/GlobalPermissions.js
  core-ui/src/components/Permissions/PermissionList/NamespacePermissions.js
  core-ui/src/components/Permissions/PermissionList/PermissionList.scss
  core-ui/src/components/Permissions/RoleBindingList/CreateRoleBindingModal.js
  core-ui/src/components/Permissions/RoleBindingList/RoleBindingList.js
  core-ui/src/components/Permissions/RoleBindingList/test/CreateRoleBindingModal.test.js
  core-ui/src/components/Permissions/RoleBindingList/test/RoleBindingList.test.js
  core-ui/src/components/Permissions/RoleBindingList/test/mocks.js
  core-ui/src/components/Permissions/RoleDetails/ClusterRoleDetails.js
  core-ui/src/components/Permissions/RoleDetails/RoleCard/RoleCard.js
  core-ui/src/components/Permissions/RoleDetails/RoleCard/RoleCard.scss
  core-ui/src/components/Permissions/RoleDetails/RoleDetails.js
  core-ui/src/components/Permissions/RoleDetails/RoleDetails.scss
  core-ui/src/components/Permissions/RoleDetails/test/ClusterRoleDetails.test.js
  core-ui/src/components/Permissions/RoleDetails/test/RoleDetails.test.js
  core-ui/src/components/Permissions/RoleList/RoleList.js
  core-ui/src/components/Permissions/RoleList/test/RoleList.test.js
  core-ui/src/components/Permissions/Shared/InvalidGroupMessage.js
  core-ui/src/components/Permissions/Shared/RoleCombobox/RoleCombobox.js
  core-ui/src/components/Permissions/Shared/RoleCombobox/RoleCombobox.scss
  core-ui/src/components/Permissions/Shared/RoleCombobox/test/RoleCombobox.test.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/index.scss
  core-ui/src/setupTests.js
  core/src/app/app.config.ts
  core/src/app/app.module.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/app/shared/components/permissions/bindings/binding-entry-renderer/binding-entry-renderer.component.html
  core/src/app/shared/components/permissions/bindings/binding-entry-renderer/binding-entry-renderer.component.ts
  core/src/app/shared/components/permissions/bindings/binding-header-renderer/binding-header-renderer.component.html
  core/src/app/shared/components/permissions/bindings/binding-header-renderer/binding-header-renderer.component.ts
  core/src/app/shared/components/permissions/bindings/bindings.component.html
  core/src/app/shared/components/permissions/bindings/bindings.component.ts
  core/src/app/shared/components/permissions/permissions.component.html
  core/src/app/shared/components/permissions/permissions.component.ts
  core/src/app/shared/components/permissions/role-details/role-details.component.html
  core/src/app/shared/components/permissions/role-details/role-details.component.ts
  core/src/app/shared/components/permissions/roles/roles-entry-renderer/roles-entry-renderer.component.html
  core/src/app/shared/components/permissions/roles/roles-entry-renderer/roles-entry-renderer.component.ts
  core/src/app/shared/components/permissions/roles/roles-header-renderer/roles-header-renderer.component.html
  core/src/app/shared/components/permissions/roles/roles-header-renderer/roles-header-renderer.component.ts
  core/src/app/shared/components/permissions/roles/roles.component.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.html
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.scss
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.spec.ts
  core/src/app/shared/components/role-binding-modal/role-binding-modal.component.ts
  core/src/app/shared/datamodel/k8s/role-binding.ts
  core/src/app/shared/datamodel/k8s/role.ts
  core/src/app/shared/services/rbac.service.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/components/GenericList/GenericList.js
Labels: area/console

#1969 Fix tests
  core/src/luigi-config/navigation/static-navigation-model.js
Labels: area/console

#1971 Fetch services via cbs
  components/react/package-lock.json
  core-ui/src/components/App/App.js
  core-ui/src/components/Services/ServiceDetails/ServiceDetailsHeader/ServiceDetailsHeader.js
  core-ui/src/components/Services/Services.js
  core-ui/src/components/Services/ServicesList/ServicesList.js
  core-ui/src/components/Services/ServicesList/test/ServicesList.test.js
  core-ui/src/components/Services/constants.js
  core-ui/src/gql/queries.js
  core-ui/src/testing/servicesMocks.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/operation/services/services-entry-renderer/services-entry-renderer.component.html
  core/src/app/content/namespaces/operation/services/services-entry-renderer/services-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/services/services-header-renderer/services-header-renderer.component.html
  core/src/app/content/namespaces/operation/services/services-header-renderer/services-header-renderer.component.ts
  core/src/app/content/namespaces/operation/services/services.component.spec.ts
  core/src/app/content/namespaces/operation/services/services.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/components/GenericList/GenericList.js
  shared/components/ListActions/ListActions.js
Labels: area/console, enhancement

#1967 Rewrite secrets
  core-ui/src/components/App/App.js
  core-ui/src/components/Secrets/Details/Json/SecretJson.js
  core-ui/src/components/Secrets/Details/Json/SecretJson.scss
  core-ui/src/components/Secrets/Details/Json/test/SecretJson.test.js
  core-ui/src/components/Secrets/Details/Secret/SecretData.js
  core-ui/src/components/Secrets/Details/Secret/SecretData.scss
  core-ui/src/components/Secrets/Details/Secret/test/SecretData.test.js
  core-ui/src/components/Secrets/Details/SecretDetails.js
  core-ui/src/components/Secrets/Details/SecretHeader.js
  core-ui/src/components/Secrets/Details/test/SecretDetails.test.js
  core-ui/src/components/Secrets/Details/test/SecretHeader.test.js
  core-ui/src/components/Secrets/Details/test/mocks.js
  core-ui/src/components/Secrets/List/SecretList.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
  core-ui/src/shared/constants.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.html
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.scss
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.spec.ts
  core/src/app/content/namespaces/operation/secrets/secret-detail/secret-detail.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.html
  core/src/app/content/namespaces/operation/secrets/secrets-entry-renderer/secrets-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets-header-renderer/secrets-header-renderer.component.html
  core/src/app/content/namespaces/operation/secrets/secrets-header-renderer/secrets-header-renderer.component.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.spec.ts
  core/src/app/content/namespaces/operation/secrets/secrets.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/components/PageHeader/PageHeader.js
  shared/components/PageHeader/PageHeader.scss
Labels: area/console, enhancement

#1988 Fix system namespaces switch
  shared/hooks/test/useShowSystemNamespaces.test.js
  shared/hooks/useShowSystemNamespaces.js
Labels: area/console

#1972 Unification of object statuses
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaDetailsHeader.scss
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/LambdaStatusCard.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsHeader/test/LambdaStatusCard.test.js
  core-ui/src/components/Lambdas/LambdaStatusBadge/LambdaStatusBadge.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/LambdasList.js
  core-ui/src/components/Lambdas/helpers/lambdas/statusType.js
  core/src/app/content/settings/applications/application-details/application-details.component.html
  core/src/app/content/settings/applications/application-details/application-details.component.ts
  core/src/app/content/settings/applications/applications-entry-renderer/applications-entry-renderer.component.ts
  core/src/app/content/settings/applications/services/applications.service.ts
  package-lock.json
  service-catalog-ui/src/components/ServiceClassDetails/ProvisionOnlyOnceInfo/ProvisionOnlyOnceInfo.component.js
  service-catalog-ui/src/components/ServiceClassDetails/ProvisionOnlyOnceInfo/styled.js
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.component.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/styled.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/InstanceParametersModal.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.scss
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/StatusPanel.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/styled.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/test/ServiceInstanceInfo.test.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/test/StatusPanel.test.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/test/__snapshots__/StatusPanel.test.js.snap
  service-catalog-ui/src/components/ServiceInstanceDetails/test/ServiceInstanceDetails.test.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceRowRenderer.js
  service-catalog-ui/src/helpers/constants.js
  service-catalog-ui/src/index.scss
  service-catalog-ui/src/shared/ServiceInstanceStatus.js
  shared/components/Modal/Modal.js
  shared/components/ModalWithForm/ModalWithForm.js
  shared/components/PageHeader/PageHeader.js
Labels: area/console

#1994 Disable compass tests
  compass/package.json
Labels: area/console

#1995 Checkmarx fixes
  compass/src/serviceWorker.js
  components/angular/generic-list/karma.conf.js
  core/karma.conf.js
  core/src/app/app.module.ts
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.html
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.scss
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.spec.ts
  core/src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts
  core/src/app/content/settings/idp-presets/idp-presets-entry-renderer/idp-presets-entry-renderer.component.html
  core/src/app/content/settings/idp-presets/idp-presets-entry-renderer/idp-presets-entry-renderer.component.ts
  core/src/app/content/settings/idp-presets/idp-presets-header-renderer/idp-presets-header-renderer.component.html
  core/src/app/content/settings/idp-presets/idp-presets-header-renderer/idp-presets-header-renderer.component.ts
  core/src/app/content/settings/idp-presets/idp-presets.component.html
  core/src/app/content/settings/idp-presets/idp-presets.component.ts
  core/src/app/content/settings/idp-presets/idp-presets.service.spec.ts
  core/src/app/content/settings/idp-presets/idp-presets.service.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/app/shared/components/url-link/url-link.component.html
Labels: area/console

#1996 adjusting log-ui to new log labelling
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  logging/src/constants.js
Labels: area/logging

#1993 Fix unstable binding test
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/CreateClusterRoleBindingModal.test.js
  core-ui/src/components/Permissions/RoleBindingList/test/CreateRoleBindingModal.test.js
Labels: area/console

#1997 [CVE-2020-7707] Bump property-expr
  core-ui/package-lock.json
  package-lock.json
  package.json
Labels: area/console, security/medium

#2001 Implement side drawer with yaml
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
  core-ui/src/gql/queries.js
  shared/components/SideDrawer/SideDrawer.js
  shared/components/SideDrawer/SideDrawer.scss
  shared/hooks/useSideDrawer.js
Labels: area/console, enhancement

#1998 Fix dropdowns for logs
  logging/src/components/Shared/SelectDropdown/SelectDropdown.js
  logging/src/components/Shared/SelectDropdown/SelectDropdown.scss
Labels: area/console, bug

#2004 Drawer fixes
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
Labels: area/console

#2002 Wait for frame to load in ui tests
  tests/support/iframe-commands.js
Labels: area/console, test-failing
