Repository kyma-project/console, pull requests merged in 2020-10, with the labels that each got.

#2007 Checkmarx fixes 2
  core/nginx/conf.d/default.conf
  core/nginx/fastcgi_params
  core/nginx/koi-utf
  core/nginx/koi-win
  core/nginx/modules
  core/nginx/nginx.conf
  core/nginx/scgi_params
  core/nginx/uwsgi_params
  core/nginx/win-utf
  core/src/app/app.config.ts
Labels: area/console, area/security

#2009 Set valid viewgroups
  core/src/luigi-config/navigation/static-navigation-model.js
Labels: area/console

#2010 Remove smoke tests for logs
  core-ui/src/components/NamespaceDetails/DeployResourceModal/DeployResourceModal.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/test/NamespaceDetailsHeader.test.js
  shared/components/Link/Link.js
  shared/components/LogsLink/LogsLink.js
  shared/components/LogsLink/test/LogsLink.test.js
  shared/index.js
  tests/config.js
  tests/tests/console-smoke-tests.spec.js
Labels: area/console, area/logging, hacktoberfest-accepted

#2011 Disable logs view if Rafter is disabled
  core/src/luigi-config/navigation/navigation-data-init.js
  tests/config.js
  tests/tests/console-smoke-tests.spec.js
Labels: area/console

#2006 Add a button to copy drawer content
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
  core-ui/src/components/ApiRules/ApiRuleDetails/test/ApiRuleDetails.test.js
  package-lock.json
  package.json
  shared/components/CopiableText/CopiableText.js
  shared/components/Link/CopiableLink.js
  shared/components/SideDrawer/SideDrawer.js
  shared/components/SideDrawer/SideDrawer.scss
  shared/hooks/useSideDrawer.js
Labels: area/console, enhancement

#1999 Add ability to see secret in lambda env configuration.
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaEnvs.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
Labels: area/console, enhancement

#2000 Configurable build resources in Function UI
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ConfigurationTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/test/ConfigurationTab.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/TableElements/Input.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/TableElements/Row.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/shared.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/test/ResourceManagement.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagementTab.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.test.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/LambdasList.js
  core-ui/src/components/Lambdas/components/DropdownInput/DropdownInput.js
  core-ui/src/components/Lambdas/components/DropdownInput/DropdownInput.scss
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useUpdateLambda.js
  core-ui/src/components/Lambdas/gql/queries.js
  core-ui/src/components/Lambdas/gql/subscriptions.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/misc/useConfigData.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
Labels: area/console, area/documentation, area/serverless, enhancement

#2025 [CVE-2020-26870] Bump DOMPurify
  components/generic-documentation/package-lock.json
  components/generic-documentation/src/render-engines/markdown/custom-renderers/ListItem.tsx
  package-lock.json
  package.json
Labels: area/console, security/critical

#2013 Fix namespaces subscription
  core-ui/src/components/NamespaceList/NamespaceList.js
  core-ui/src/components/NamespaceList/test/wsHandler.test.js
  core-ui/src/components/NamespaceList/wsHandler.js
Labels: area/console

#2031 Fix the execute of monaco inline script
  core-ui/nginx.conf
Labels: area/console, area/serverless, bug, priority/critical

#2032 Fix resource upload on Windows
  core-ui/src/components/NamespaceDetails/DeployResourceModal/deployResourceHelpers.js
  core-ui/src/components/NamespaceDetails/DeployResourceModal/test/deployResourceHelpers.test.js
Labels: area/console, bug

#2038 Bump angular from 6 to 8 in core
  components/angular/generic-list/src/app/modules/list/list-element-actions/list-element-actions.component.ts
  components/angular/generic-list/src/app/modules/list/plain-list/plain-list.component.ts
  components/angular/generic-list/src/app/modules/list/plain-table/plain-table.component.ts
  core/angular.json
  core/package-lock.json
  core/package.json
  core/src/app/auth/token.interceptor.spec.ts
  core/src/app/content/namespaces/configuration/resources/resources.component.ts
  core/src/app/content/namespaces/namespaces-container/namespaces-container.component.ts
  core/src/app/content/namespaces/operation/abstract-graphql-element-list.component.ts
  core/src/app/content/namespaces/operation/abstract-kubernetes-element-list.component.ts
  core/src/app/content/settings/applications/application-details/application-details.component.ts
  core/src/app/content/settings/applications/application-details/bindings-details-modal/bindings-details-modal.component.ts
  core/src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts
  core/src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.ts
  core/src/app/content/settings/applications/applications.component.ts
  core/src/app/content/settings/applications/create-application-modal/create-application-modal.component.ts
  core/src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.ts
  core/src/app/shared/components/confirmation-modal/confirmation-modal.component.ts
  core/src/app/shared/components/copy2clipboard-modal/copy2clipboard-modal.component.ts
  core/src/app/shared/components/edit-resource/edit-resource.component.ts
  core/src/app/shared/components/information-modal/information-modal.component.ts
  core/src/app/shared/components/json-editor-modal/json-editor-modal.component.ts
  core/src/app/shared/components/labels-input/labels-input.component.spec.ts
  core/src/app/shared/components/labels-input/labels-input.component.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-component/resource-uploader.component.ts
  core/src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts
  core/src/app/shared/components/resource-uploader/uploader/uploader.component.ts
  core/src/polyfills.ts
  core/tsconfig.json
  core/tslint.json
  core/webpack-extra.config.js
  package-lock.json
Labels: area/console, enhancement

#2015 Use new node chromium image in core dockerfile
  core/Dockerfile
Labels: area/console, enhancement

#2034 Resources on namespace view
  core-ui/public/index.html
  core-ui/src/components/CreateNamespaceForm/CreateNamespaceForm.js
  core-ui/src/components/CreateNamespaceForm/test/gqlMocks.js
  core-ui/src/components/NamespaceDetails/LimitRanges/LimitRanges.js
  core-ui/src/components/NamespaceDetails/LimitRanges/test/LimitRanges.test.js
  core-ui/src/components/NamespaceDetails/NamespaceApplications/NamespaceApplications.js
  core-ui/src/components/NamespaceDetails/NamespaceDetails.js
  core-ui/src/components/NamespaceDetails/NamespaceDetails.scss
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/components/NamespaceDetails/NamespaceWorkloads/NamespaceWorkloads.scss
  core-ui/src/components/NamespaceDetails/ResourceQuotas/ResourceQuotas.js
  core-ui/src/components/NamespaceDetails/ResourceQuotas/test/ResourceQuotas.test.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-entry-renderer/limit-range-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-header-renderer/limit-range-header-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-header-renderer/limit-range-header-renderer.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-range-header-renderer/limit-range-header-renderer.component.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.html
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/limit-ranges/limit-ranges.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-entry-renderer/resource-quota-entry-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-entry-renderer/resource-quota-entry-renderer.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-entry-renderer/resource-quota-entry-renderer.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-header-renderer/resource-quota-header-renderer.component.html
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-header-renderer/resource-quota-header-renderer.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quota-header-renderer/resource-quota-header-renderer.component.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.html
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resource-quotas/resource-quotas.component.ts
  core/src/app/content/namespaces/configuration/resources/resources.component.html
  core/src/app/content/namespaces/configuration/resources/resources.component.scss
  core/src/app/content/namespaces/configuration/resources/resources.component.spec.ts
  core/src/app/content/namespaces/configuration/resources/resources.component.ts
  core/src/app/content/namespaces/namespaces-container/namespaces-container.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/components/GenericList/GenericList.js
  shared/components/Notification/Notification.scss
  shared/components/SideDrawer/SideDrawer.js
  shared/components/SideDrawer/SideDrawer.scss
  shared/contexts/YamlEditorContext.js
  shared/index.js
Labels: area/console, enhancement, hacktoberfest-accepted

#2039 Update json pointer in core-ui
  core-ui/package-lock.json
Labels: area/console, enhancement

#2040 Fix routing to ServiceClassPlansList
  service-catalog-ui/src/components/App/App.js
Labels: area/console, bug, hacktoberfest-accepted

#2042 Apply drawer component on k8s services
  core-ui/src/components/Services/ServiceDetails/ServiceDetails.js
  core-ui/src/components/Services/ServiceDetails/ServiceDetailsHeader/ServiceDetailsHeader.js
  core-ui/src/components/Services/Services.js
  core-ui/src/components/Services/ServicesList/ServicesList.js
  core-ui/src/components/Services/ServicesList/test/ServicesList.test.js
  core-ui/src/gql/queries.js
  core-ui/src/shared/components/ResourceSpecModal/ResourceSpecModal.js
  core-ui/src/shared/components/ResourceSpecModal/test/ResourceSpecModal.test.js
  core-ui/src/testing/servicesMocks.js
  core/src/luigi-config/settings.js
  package-lock.json
  package.json
  shared/contexts/YamlEditorContext.js
Labels: area/console
