Repository kyma-project/console, pull requests merged in 2021-01, with the labels that each got.

#2075 Sanitize angular inputs
  components/angular/generic-list/src/app/modules/list/list-search/list-search.component.ts
  core/src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.ts
Labels: area/console, bug

#2077 Remove unused docs from react components
  components/react/README.md
  components/react/docs/build/1.3ae25e80.js
  components/react/docs/build/bundle.2b16510c.js
  components/react/docs/index.html
  components/react/package-lock.json
  components/react/package.json
  components/react/styleguide.config.js
  package-lock.json
Labels: area/console

#2081 Resolve WS-2020-0218 aka merge1.2.1
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/generic-documentation/src/index.tsx
  components/react/package-lock.json
  components/react/package.json
  package-lock.json
  package.json
Labels: area/console, security/high

#2071 Event Subscriptions
  .clusterConfig.default
  core-ui/src/components/ApiRules/ApiRuleDetails/ApiRuleDetails.js
  core-ui/src/components/ApiRules/ApiRuleDetails/test/ApiRuleDetails.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesList.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/LambdaEventsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/helpers.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.test.js
  core-ui/src/components/Services/ServiceDetails/ServiceDetails.js
  core-ui/src/components/Services/ServiceDetails/ServiceEventTriggers/ServiceEventsWrapper.js
  core-ui/src/components/Services/ServiceDetails/ServiceEventTriggers/helpers.js
  core-ui/src/components/Services/constants.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core-ui/src/gql/subscriptions.js
  core-ui/src/shared/components/EventSubscriptions/BebEventSubscription.js
  core-ui/src/shared/components/EventSubscriptions/CreateSubscriptionModal.js
  core-ui/src/shared/components/EventSubscriptions/CreateSubscriptionModal.scss
  core-ui/src/shared/components/EventSubscriptions/helpers.js
  core-ui/src/shared/components/EventSubscriptions/test/BebEventSubscription.test.js
  core-ui/src/shared/components/EventSubscriptions/test/CreateSubscriptionModal.test.js
  core-ui/src/shared/components/EventSubscriptions/test/mocks.js
  core-ui/src/shared/constants.js
  shared/components/ListActions/ListActions.js
Labels: area/console

#2087 Revert Pamela related changes
  .clusterConfig.default
  core-ui/src/components/App/App.js
  core-ui/src/components/Deployments/DeploymentList/DeploymentList.js
  core-ui/src/components/Deployments/Deployments.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/BasicData.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/CreateWorkloadForm.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/CreateWorkloadForm.scss
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/ScalingData.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/ServiceData.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/helpers.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/test/BasicData.test.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/test/ScalingData.test.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/test/ServiceData.test.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/test/__snapshots__/helpers.test.js.snap
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/test/helpers.test.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
  core-ui/src/components/Pods/PodList/PodList.js
  core-ui/src/components/Pods/Pods.js
  core-ui/src/shared/constants.js
  core/src/app/app.module.ts
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.html
  core/src/app/content/namespaces/operation/pods/pods-entry-renderer/pods-entry-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.html
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.scss
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.spec.ts
  core/src/app/content/namespaces/operation/pods/pods-header-renderer/pods-header-renderer.component.ts
  core/src/app/content/namespaces/operation/pods/pods.component.spec.ts
  core/src/app/content/namespaces/operation/pods/pods.component.ts
  core/src/app/navigation/app-routing.module.ts
  core/src/luigi-config/navigation/static-navigation-model.js
  package-lock.json
  package.json
  shared/components/ModalWithForm/ModalWithForm.js
  shared/contexts/ConfigContext.js
  shared/contexts/ConfigContext.test.js
  shared/hooks/PamelaAPI/config.js
  shared/hooks/PamelaAPI/index.js
  shared/hooks/PamelaAPI/useGenericCreate.js
  shared/hooks/PamelaAPI/useGet.js
  shared/hooks/PamelaAPI/useMutation.js
  shared/hooks/PamelaAPI/useSubscription.js
  shared/hooks/index.js
  shared/package-lock.json
  shared/package.json
Labels: area/console

#2084 Create a generic resources list with Pamela
  core-ui/src/components/App/App.js
  core-ui/src/components/Deployments/DeploymentList/DeploymentList.js
  core-ui/src/components/Deployments/Deployments.js
  core-ui/src/components/Pods/PodList/PodList.js
  core-ui/src/components/Pods/Pods.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core/src/luigi-config/navigation/static-navigation-model.js
Labels: area/console, enhancement

#2089 Beb fixes
  core-ui/nginx.conf
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventTriggers/LambdaEventsWrapper.js
  core-ui/src/components/Lambdas/gql/mutations.js
  core-ui/src/components/Services/ServiceDetails/ServiceEventTriggers/ServiceEventsWrapper.js
Labels: area/console, bug

#2093 Use api server for creating (cluster)roleBindings
  .clusterConfig.default
  core-ui/src/components/Permissions/ClusterRoleBindingList/ClusterRoleBindingList.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/CreateClusterRoleBindingModal.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/ClusterRoleBindingList.test.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/CreateClusterRoleBindingModal.test.js
  core-ui/src/components/Permissions/RoleBindingList/CreateRoleBindingModal.js
  core-ui/src/components/Permissions/RoleBindingList/RoleBindingList.js
  core-ui/src/components/Permissions/RoleBindingList/test/CreateRoleBindingModal.test.js
  core-ui/src/components/Permissions/RoleBindingList/test/RoleBindingList.test.js
  core-ui/src/components/Permissions/helpers.js
Labels: area/console

#2095 Disable caching for get function gql query
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetailsWrapper.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/test/useLambdaQuery.test.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useLambdaQuery.js
  core-ui/src/components/Lambdas/gql/hooks/queries/useLambdasQuery.js
Labels: area/console, area/serverless, bug

#2099 Extendable generic views
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Pods.list.js
  core-ui/src/components/Predefined/Replicaset.details.js
  core-ui/src/components/Predefined/Replicasets.list.js
  core-ui/src/components/Predefined/index.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core/src/luigi-config/navigation/static-navigation-model.js
  package-lock.json
  shared/index.js
  shared/typechecking/CustomColumns.js
Labels: area/console

#2100 OIDC flow
  core-ui/src/components/NamespaceDetails/NamespaceDetails.js
  core-ui/src/components/NamespaceList/NamespaceList.js
  core/package.json
  core/src/luigi-config/auth.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/test/util.test.js
  core/src/luigi-config/navigation/util.js
Labels: area/console

#2098 Show function envs applied from ConfigMaps and Secrets
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.test.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
Labels: area/serverless

#2104 Generic pods list
  core-ui/src/components/Predefined/Pods.list.js
  shared/hooks/PamelaAPI/useMutation.js
Labels: area/console, enhancement

#2106 Unhardcode oidc flow (#2097)
  core/package-lock.json
  core/package.json
  core/src/luigi-config/auth/auth-params.js
  core/src/luigi-config/auth/index.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/permissions.js
Labels: area/console
