Repository kyma-project/console, pull requests merged in 2021-03, with the labels that each got.

#2137 Remove deprecated fields from MILV config
  milv.config.yaml
Labels: area/documentation, enhancement

#2140 Create for OAuth clients
  core-ui/src/components/OAuthClients/Create/CreateOAuthClient.js
  core-ui/src/components/OAuthClients/Create/test/CreateOAuthClient.test.js
  core-ui/src/components/OAuthClients/Create/test/mocks.js
  core-ui/src/components/OAuthClients/Details/OAuthClientDetails.js
  core-ui/src/components/OAuthClients/Details/OAuthClientHeader.js
  core-ui/src/components/OAuthClients/Details/OAuthClientSpecPanel.js
  core-ui/src/components/OAuthClients/Details/Secret/OAuthClientSecret.js
  core-ui/src/components/OAuthClients/Details/Secret/OAuthClientSecret.scss
  core-ui/src/components/OAuthClients/Details/Secret/test/OAuthClientSecret.test.js
  core-ui/src/components/OAuthClients/Details/Secret/test/mocks.js
  core-ui/src/components/OAuthClients/Details/test/OAuthClientDetails.test.js
  core-ui/src/components/OAuthClients/Details/test/OAuthClientHeader.test.js
  core-ui/src/components/OAuthClients/Details/test/OAuthClientSpecPanel.test.js
  core-ui/src/components/OAuthClients/Details/test/mocks.js
  core-ui/src/components/OAuthClients/Form/OAuthClientForm.js
  core-ui/src/components/OAuthClients/Form/OAuthClientForm.scss
  core-ui/src/components/OAuthClients/Form/test/CheckboxFormControl.test.js
  core-ui/src/components/OAuthClients/Form/test/OAuthClientForm.test.js
  core-ui/src/components/OAuthClients/Form/test/mocks.js
  core-ui/src/components/OAuthClients/List/OAuthClientLink.js
  core-ui/src/components/OAuthClients/List/OAuthClientsList.js
  core-ui/src/components/OAuthClients/List/test/OAuthClientsList.test.js
  core-ui/src/components/OAuthClients/List/test/mocks.js
  core-ui/src/components/OAuthClients/Status/OAuthClientStatus.js
  core-ui/src/components/OAuthClients/Status/test/OAuthClientStatus.test.js
  core-ui/src/components/OAuthClients/common.js
  core-ui/src/components/Predefined/Create/OAuthClients/CheckboxFormControl.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/createOAuthClient.js
  core-ui/src/components/Predefined/Create/OAuthClients/helpers.js
  core-ui/src/components/Predefined/Create/OAuthClients/test/CheckboxFormControl.test.js
  core-ui/src/components/Predefined/Create/OAuthClients/test/__snapshots__/createOAuthClient.test.js.snap
  core-ui/src/components/Predefined/Create/OAuthClients/test/createOAuthClient.test.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/index.scss
  shared/components/ResourcesList/ResourcesList.js
Labels: area/console

#2139 New old workload modals 2/3
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/createLambdaInput.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/test/useCreateLambda.test.js
  core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
  core-ui/src/components/Lambdas/gql/mutations.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/ScalingData.js
  core-ui/src/components/NamespaceDetails/CreateWorkloadForm/test/ScalingData.test.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.scss
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceLabels/NamespaceLabels.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceLabels/test/NamespaceLabels.test.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceLabels/test/mocks.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/test/NamespaceDetailsHeader.test.js
  core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/test/mocks.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.scss
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/ScalingData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/ServiceData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/helpers.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/BasicData.test.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/ServiceData.test.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/__snapshots__/helpers.test.js.snap
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/helpers.test.js
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Pods.list.js
  shared/hooks/PamelaAPI/index.js
  shared/hooks/PamelaAPI/useGenericCreate.js
Labels: area/console

#2141 Create rolebindings and clusterrolebindings
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Create/ClusterRoleBindings.create.js
  core-ui/src/components/Predefined/Create/RoleBindings.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleCombobox.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleCombobox.scss
  core-ui/src/components/Predefined/Create/index.js
  shared/hooks/navigate.js
Labels: enhancement

#2151 Remove kyma version from the init call
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
Labels: area/console, bug

#2149 OIDC logout
  core/src/luigi-config/auth.js
Labels: area/console

#2147 Add details for apirules with create and edit
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/JwtDetails/test/JwtDetails.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ServicesDropdown/ServicesDropdown.js
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  core-ui/src/components/ApiRules/helpers.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  core-ui/src/components/Predefined/Details/Service.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/components/Predefined/List/index.js
  logging/src/components/Header/test/Header.test.js
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/navigate.js
Labels: area/console, enhancement

#2162 Deprecate nodejs10 fn runtime
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
Labels: area/serverless
