Repository kyma-project/console, pull requests merged in 2021-02, with the labels that each got.

#2112 Fix permissions validation (#2108)
  core-ui/src/components/Permissions/ClusterRoleBindingList/CreateClusterRoleBindingModal.js
  core-ui/src/components/Permissions/RoleBindingList/CreateRoleBindingModal.js
  core-ui/src/components/Permissions/Shared/InvalidGroupMessage.js
Labels: area/console, bug

#2129 Adapt Roles and Roles Bindings to use the general components approach and work with k8s API
  core-ui/src/components/Permissions/ClusterRoleBindingList/ClusterRoleBindingList.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/CreateClusterRoleBindingModal.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/ClusterRoleBindingList.test.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/CreateClusterRoleBindingModal.test.js
  core-ui/src/components/Permissions/ClusterRoleBindingList/test/mocks.js
  core-ui/src/components/Permissions/ClusterRoleList/ClusterRoleList.js
  core-ui/src/components/Permissions/ClusterRoleList/test/ClusterRoleList.test.js
  core-ui/src/components/Permissions/PermissionList/GlobalPermissions.js
  core-ui/src/components/Permissions/PermissionList/NamespacePermissions.js
  core-ui/src/components/Permissions/PermissionList/PermissionList.scss
  core-ui/src/components/Permissions/RoleBindingList/CreateRoleBindingModal.js
  core-ui/src/components/Permissions/RoleBindingList/RoleBindingList.js
  core-ui/src/components/Permissions/RoleBindingList/test/CreateRoleBindingModal.test.js
  core-ui/src/components/Permissions/RoleBindingList/test/RoleBindingList.test.js
  core-ui/src/components/Permissions/RoleBindingList/test/mocks.js
  core-ui/src/components/Permissions/RoleDetails/ClusterRoleDetails.js
  core-ui/src/components/Permissions/RoleDetails/RoleCard/RoleCard.js
  core-ui/src/components/Permissions/RoleDetails/RoleCard/RoleCard.scss
  core-ui/src/components/Permissions/RoleDetails/RoleDetails.js
  core-ui/src/components/Permissions/RoleDetails/RoleDetails.scss
  core-ui/src/components/Permissions/RoleDetails/test/ClusterRoleDetails.test.js
  core-ui/src/components/Permissions/RoleDetails/test/RoleDetails.test.js
  core-ui/src/components/Permissions/RoleList/RoleList.js
  core-ui/src/components/Permissions/RoleList/test/RoleList.test.js
  core-ui/src/components/Permissions/Shared/InvalidGroupMessage.js
  core-ui/src/components/Permissions/Shared/RoleCombobox/RoleCombobox.js
  core-ui/src/components/Permissions/Shared/RoleCombobox/RoleCombobox.scss
  core-ui/src/components/Permissions/Shared/RoleCombobox/test/RoleCombobox.test.js
  core-ui/src/gql/mutations.js
  core-ui/src/gql/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  shared/utils/getComponentForResource.js
Labels: area/console

#2132 Remove catalog configmap (#2084)
  resources/web/deployment-service-catalog.yaml
Labels: area/console

#2134 Add renamed fields to MILV config
  milv.config.yaml
Labels: area/documentation, enhancement
